#Do mobs spin?
mobsSpin = true
#Spin speed multiplier.
# Default: 1.0
# Range: 0.0 ~ 10.0
spinSpeed = 1.0
#Camera tilt in degrees.
# Default: 15.0
# Range: -90.0 ~ 90.0
tiltDegrees = 15.0
#Render mobs at full brightness?
fullBright = true
#Should mobs play idle animation?
idleAnimation = true
#Should mobs play walk animation?
walkAnimation = false
