
[general]
	disable_mod = false
	auto_start = false
	space_modules = true
	shadow_text = true
	animations = true
	animationSpeed = 1.0
	fontScale = 1.1
	background_color = 0
	hide_debug_crosshair = false
	hide_sidebar = false
	hide_bossbar = false
	always_show_profiler = false
	always_show_tps = false

[[modules_left]]
	name = "minecraft"
	name_color = 10506797
	value_color = 43520
	enabled = true

	[modules_left.lines]
		minecraft = true

[[modules_left]]
	name = "fps"
	color_high = 5635925
	color_med = 16777045
	color_low = 16733525
	enabled = true

	[modules_left.lines]
		fps = true

[[modules_left]]
	name = "graphics"
	name_color = 16755200
	value_color = 5636095
	enabled = true

	[modules_left.lines]
		render_distance = true
		graphics = true
		clouds = false
		biome_blend_radius = false
		shader = true

[[modules_left]]
	name = "server"
	name_color = 11184810
	value_color = 16777045
	enabled = true

	[modules_left.lines]
		server_tick = true
		packets_sent = false
		packets_received = false

[[modules_left]]
	name = "location"
	name_color = 43520
	value_color = 5636095
	enabled = true

	[modules_left.lines]
		dimension = false
		facing = true
		rotation = false
		light = false
		light_server = false
		highest_block = false
		highest_block_server = false
		biome = false
		local_difficulty = false
		day_ticks = false
		days_played = true
		slime_chunk = false

[[modules_left]]
	name = "empty"
	empty_lines = 1
	enabled = true

	[modules_left.lines]
		nothing = true

[[modules_right]]
	name = "system"
	name_color = 16755200
	value_color = 5636095
	memory_color_toggle = true
	time_format = "HH:mm:ss"
	enabled = true

	[modules_right.lines]
		time = true
		java_version = true
		memory_usage = true
		allocation_rate = true
		allocated_memory = true
		cpu = true
		display = true
		gpu = true
		gpu_utilization = true
		opengl_version = true
		gpu_driver = true

