#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Aug 27 22:38:48 YEKT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
