version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 7
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEPTH"
leavesCullingAmount = 1
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
modularforcefields = true
extrastorage = true
fastitemframes = true
mcwfences = true
farmersdelight = true
create_new_age = true
mcwbyg = true
projectred_core = true
cold_sweat = true
cookingforblockheads = true
betternether = true
adchimneys = true
mcwstairs = true
alexscaves = true
runes = true
copycats = true
extradisks = true
integratedterminals = true
domum_ornamentum = true
comforts = true
advanced_ae = true
allthecompressed = true
alltheores = true
aether = true
morered = true
ftbquests = true
chisel = true
extendedcrafting = true
voltaic = true
evolvedmekanism = true
hybrid-aquatic = true
mekanism_turrets = true
netherex = true
apotheosis = true
paladins = true
create_confectionery = true
deeperdarker = true
ldlib2 = true
create = true
overgeared = true
minecolonies = true
multipiston = true
createoreexcavation = true
glassential = true
createmetalwork = true
biomeswevegone = true
visualworkbench = true
ballistix = true
nautec = true
hearth_and_timber = true
fdbosses = true
fdlib = true
projectred_exploration = true
unusualend = true
refinedstorage_mekanism_integration = true
dragonlib = true
refinedstorage = true
mcwfurnitures = true
alchemists_garden = true
cb_multipart = true
sophisticatedstorage = true
additional_lights = true
astages = true
immeng = true
sliceanddice = true
waystones = true
apothic_enchanting = true
appliedpneumatics = true
born_in_chaos_v1 = true
projectred_illumination = true
ftbpc = true
alexsmobs = true
megacells = true
neovitae = true
createpropulsion = true
more_immersive_wires = true
hostilenetworks = true
hostile_neural_industrialization = true
igleelib = true
quark = true
mcwquark = true
abyssal_decor = true
the_afterdark = true
darkutils = true
create_sa = true
mcwlights = true
block_factorys_bosses = true
livingthings = true
pneumaticcraft = true
treechop = true
mekanismadditions = true
mcwdoors = true
factory_blocks = true
cabletiers = true
mekanism = true
aeronautics = true
immersivepetroleum = true
deep_aether = true
simulated = true
productivemetalworks = true
trashcans = true
rogues = true
create_dragons_plus = true
tombstone = true
dynamicelectricity = true
industrialization_overdrive = true
ae2 = true
draconicevolution = true
thirst = true
bosses_of_mass_destruction = true
archers = true
oritech = true
diagonalwindows = true
mekmm = true
gaze = true
create_integrated_farming = true
azurelib = true
generatorgalore = true
integratedtunnels = true
spectrum = true
stellaris = true
aoacore = true
refurbished_furniture = true
furniture = true
actuallyadditions = true
ifeu = true
arcanelanterns = true
immersive_furniture = true
mcwbridges = true
taxov = true
railways = true
handcrafted = true
eternalnether = true
modern_industrialization = true
offroad = true
spell_engine = true
mekanism_lasers = true
nightlights = true
supplementaries = true
industrialforegoing = true
endrem = true
createrailwaysnavigator = true
mahoutsukai = true
databank = true
minecraft = true
occultism = true
mowziesmobs = true
undergarden = true
moa_decor_electronics = true
rsrequestify = true
createaddition = true
powergrid = true
astral_dimension = true
createframed = true
creeperoverhaul = true
hammerlib = true
industrialforegoingsouls = true
ironfurnaces = true
immersiveengineering = true
createnuclear = true
interdimensionalwirelesstransmitter = true
create_aquatic_ambitions = true
chemicalscience = true
integratedcrafting = true
mcwroofs = true
eternal_starlight = true
oritechthings = true
mcwwindows = true
oceansdelight = true
cataclysm = true
betterend = true
create_furnitures = true
mcwpaths = true
diagonalwalls = true
expandedae = true
citadel = true
createdieselgenerators = true
nuclearscience = true
farmingforblockheads = true
bellsandwhistles = true
psi = true
fastpaintings = true
mcwtrpdoors = true
mekanismgenerators = true
botanypots = true
amendments = true
ftboceanmobs = true
electrodynamics = true
eclipticseasons = true
extended_industrialization = true
projectred_expansion = true
diagonalfences = true
moonlight = true
alloyed = true
integrateddynamics = true
sophisticatedbackpacks = true
assemblyline = true
cnb = true
theurgy = true
chipped = true
solarflux = true
aquaculture = true
structurize = true
blastcraft = true
corail_woodcutter = true
architects_palette = true
draconicadditions = true
lootr = true
decorativerailings = true
regions_unexplored = true
createdeco = true
betterarcheology = true
avaritia = true
malum = true
endermanoverhaul = true
jewelry = true
moderndynamics = true
mm_farming = true
forbidden_arcanus = true
crittersandcompanions = true
extendedae = true
macabre = true
rechiseled = true
enderio = true
