#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Aug 25 19:23:46 YEKT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=20
shaderPack=FreshEdit-1.0-ComplementaryReim-r5.2.1
enableShaders=true
