#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Aug 10 23:32:23 EDT 2026
allowUnknownShaders=true
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=6
shaderPack=ComplementaryUnbound_r5.8.1_EP1.9.3
