// AoA KubeJS: aoa_astages_01b_mekanism_addon_machines.js
// Machine Staging Contract pass (2026-05-28) -- Mekanism-family addon machines.
//
// Evolved Mekanism, Mekanism Machine Multiblocks (mekmm), Mekanism Lasers, and
// Mekanism Turrets ship advanced/dense/quantum/multiversal-tier processing,
// storage, logistics, solar, and combat blocks that were entirely unlocked.
// None of this is Industrial Revolution content; it extends Mekanism's endgame.
//
// Era-tiered placement (additive to aoa_astages_01_item_restrictions.js, which
// is left untouched):
//   basic / advanced / elite / ultimate / overclocked          -> atomic
//   quantum / dense / multiversal                              -> otherworldly
// dense re-staged 2026-08-07: the jar recipes build every dense_* item FROM its
// quantum_* counterpart, so dense sits ABOVE quantum in the mod ladder.
// creative_* tiers and items already locked in the main file are excluded.
//
// Recipe spot-checks (2026-05-28) confirm the floor: e.g.
// evolvedmekanism:solidification_chamber is otherwise IR-craftable (infused
// alloy + steel casing); mekmm machines route through c:circuits/elite|ultimate
// (already atomic-locked) so atomic is at or above their natural recipe ceiling.
// No tier is locked earlier than its ingredients -> no softlock introduced.

;(function () {
  if (typeof AStages === 'undefined') return

  function applySoftItemPolicy(restriction) {
    // AStages 2.5 defaults keep locked entries hidden in EMI and conceal their names.
    return restriction
      .allowInventoryStorage()
      .allowContainerStorage()
      .allowPickup()
      .disableBlockInteraction()
  }

  function softItemLock(stage, item, kind) {
    if (typeof Item !== 'undefined' && typeof Item.exists === 'function' && !Item.exists(item)) {
      console.warn('[AoA AStages addon] Skipped missing item ' + item + ' (' + kind + ', stage=' + stage + ')')
      return
    }
    const id = 'aoa/item/' + kind + '/' + stage + '/' + item.replace(/[^a-zA-Z0-9_]/g, '_')
    try {
      applySoftItemPolicy(AStages.addRestrictionForItem(id, stage, item))
    } catch (e) {
      console.warn('[AoA AStages addon] Skipped missing item ' + item + ' (' + kind + ', stage=' + stage + '): ' + e)
    }
  }

  const itemLocks = [
    ["atomic", "evolvedmekanism:advanced_alloying_factory", "block_item"],
    ["atomic", "evolvedmekanism:advanced_personal_barrel", "block_item"],
    ["atomic", "evolvedmekanism:advanced_personal_chest", "block_item"],
    ["atomic", "evolvedmekanism:advanced_solar_generator", "block_item"],
    ["atomic", "evolvedmekanism:apt_casing", "block_item"],
    ["atomic", "evolvedmekanism:basic_alloying_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:dense_alloying_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:dense_bin", "block_item"],
    ["otherworldly", "evolvedmekanism:dense_chemical_tank", "block_item"],
    ["otherworldly", "evolvedmekanism:dense_combining_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:dense_compressing_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:dense_crushing_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:dense_enriching_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:dense_fluid_tank", "block_item"],
    ["otherworldly", "evolvedmekanism:dense_induction_cell", "block_item"],
    ["otherworldly", "evolvedmekanism:dense_induction_provider", "block_item"],
    ["otherworldly", "evolvedmekanism:dense_infusing_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:dense_injecting_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:dense_logistical_transporter", "block_item"],
    ["otherworldly", "evolvedmekanism:dense_mechanical_pipe", "block_item"],
    ["otherworldly", "evolvedmekanism:dense_personal_barrel", "block_item"],
    ["otherworldly", "evolvedmekanism:dense_personal_chest", "block_item"],
    ["otherworldly", "evolvedmekanism:dense_pressurized_tube", "block_item"],
    ["otherworldly", "evolvedmekanism:dense_purifying_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:dense_sawing_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:dense_smelting_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:dense_solar_generator", "block_item"],
    ["otherworldly", "evolvedmekanism:dense_thermodynamic_conductor", "block_item"],
    ["otherworldly", "evolvedmekanism:dense_universal_cable", "block_item"],
    ["atomic", "evolvedmekanism:elite_alloying_factory", "block_item"],
    ["atomic", "evolvedmekanism:elite_personal_barrel", "block_item"],
    ["atomic", "evolvedmekanism:elite_personal_chest", "block_item"],
    ["atomic", "evolvedmekanism:elite_solar_generator", "block_item"],
    ["otherworldly", "evolvedmekanism:multiversal_alloying_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:multiversal_bin", "block_item"],
    ["otherworldly", "evolvedmekanism:multiversal_chemical_tank", "block_item"],
    ["otherworldly", "evolvedmekanism:multiversal_combining_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:multiversal_compressing_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:multiversal_crushing_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:multiversal_enriching_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:multiversal_fluid_tank", "block_item"],
    ["otherworldly", "evolvedmekanism:multiversal_induction_cell", "block_item"],
    ["otherworldly", "evolvedmekanism:multiversal_induction_provider", "block_item"],
    ["otherworldly", "evolvedmekanism:multiversal_infusing_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:multiversal_injecting_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:multiversal_logistical_transporter", "block_item"],
    ["otherworldly", "evolvedmekanism:multiversal_mechanical_pipe", "block_item"],
    ["otherworldly", "evolvedmekanism:multiversal_personal_barrel", "block_item"],
    ["otherworldly", "evolvedmekanism:multiversal_personal_chest", "block_item"],
    ["otherworldly", "evolvedmekanism:multiversal_pressurized_tube", "block_item"],
    ["otherworldly", "evolvedmekanism:multiversal_purifying_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:multiversal_sawing_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:multiversal_smelting_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:multiversal_solar_generator", "block_item"],
    ["otherworldly", "evolvedmekanism:multiversal_thermodynamic_conductor", "block_item"],
    ["otherworldly", "evolvedmekanism:multiversal_universal_cable", "block_item"],
    ["atomic", "evolvedmekanism:overclocked_alloying_factory", "block_item"],
    ["atomic", "evolvedmekanism:overclocked_bin", "block_item"],
    ["atomic", "evolvedmekanism:overclocked_chemical_tank", "block_item"],
    ["atomic", "evolvedmekanism:overclocked_combining_factory", "block_item"],
    ["atomic", "evolvedmekanism:overclocked_compressing_factory", "block_item"],
    ["atomic", "evolvedmekanism:overclocked_crushing_factory", "block_item"],
    ["atomic", "evolvedmekanism:overclocked_enriching_factory", "block_item"],
    ["atomic", "evolvedmekanism:overclocked_fluid_tank", "block_item"],
    ["atomic", "evolvedmekanism:overclocked_induction_cell", "block_item"],
    ["atomic", "evolvedmekanism:overclocked_induction_provider", "block_item"],
    ["atomic", "evolvedmekanism:overclocked_infusing_factory", "block_item"],
    ["atomic", "evolvedmekanism:overclocked_injecting_factory", "block_item"],
    ["atomic", "evolvedmekanism:overclocked_logistical_transporter", "block_item"],
    ["atomic", "evolvedmekanism:overclocked_mechanical_pipe", "block_item"],
    ["atomic", "evolvedmekanism:overclocked_personal_barrel", "block_item"],
    ["atomic", "evolvedmekanism:overclocked_personal_chest", "block_item"],
    ["atomic", "evolvedmekanism:overclocked_pressurized_tube", "block_item"],
    ["atomic", "evolvedmekanism:overclocked_purifying_factory", "block_item"],
    ["atomic", "evolvedmekanism:overclocked_sawing_factory", "block_item"],
    ["atomic", "evolvedmekanism:overclocked_smelting_factory", "block_item"],
    ["atomic", "evolvedmekanism:overclocked_solar_generator", "block_item"],
    ["atomic", "evolvedmekanism:overclocked_thermodynamic_conductor", "block_item"],
    ["atomic", "evolvedmekanism:overclocked_universal_cable", "block_item"],
    ["otherworldly", "evolvedmekanism:quantum_alloying_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:quantum_bin", "block_item"],
    ["otherworldly", "evolvedmekanism:quantum_chemical_tank", "block_item"],
    ["otherworldly", "evolvedmekanism:quantum_combining_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:quantum_compressing_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:quantum_crushing_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:quantum_enriching_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:quantum_fluid_tank", "block_item"],
    ["otherworldly", "evolvedmekanism:quantum_induction_cell", "block_item"],
    ["otherworldly", "evolvedmekanism:quantum_induction_provider", "block_item"],
    ["otherworldly", "evolvedmekanism:quantum_infusing_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:quantum_injecting_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:quantum_logistical_transporter", "block_item"],
    ["otherworldly", "evolvedmekanism:quantum_mechanical_pipe", "block_item"],
    ["otherworldly", "evolvedmekanism:quantum_personal_barrel", "block_item"],
    ["otherworldly", "evolvedmekanism:quantum_personal_chest", "block_item"],
    ["otherworldly", "evolvedmekanism:quantum_pressurized_tube", "block_item"],
    ["otherworldly", "evolvedmekanism:quantum_purifying_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:quantum_sawing_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:quantum_smelting_factory", "block_item"],
    ["otherworldly", "evolvedmekanism:quantum_solar_generator", "block_item"],
    ["otherworldly", "evolvedmekanism:quantum_thermodynamic_conductor", "block_item"],
    ["otherworldly", "evolvedmekanism:quantum_universal_cable", "block_item"],
    ["atomic", "evolvedmekanism:solidification_chamber", "block_item"],
    ["atomic", "evolvedmekanism:ultimate_alloying_factory", "block_item"],
    ["atomic", "evolvedmekanism:ultimate_personal_barrel", "block_item"],
    ["atomic", "evolvedmekanism:ultimate_personal_chest", "block_item"],
    ["atomic", "evolvedmekanism:ultimate_solar_generator", "block_item"],
    ["atomic", "mekmm:advanced_centrifuging_factory", "block_item"],
    ["atomic", "mekmm:advanced_crystallizing_factory", "block_item"],
    ["atomic", "mekmm:advanced_dissolving_factory", "block_item"],
    ["atomic", "mekmm:advanced_lathing_factory", "block_item"],
    ["atomic", "mekmm:advanced_liquifying_factory", "block_item"],
    ["atomic", "mekmm:advanced_max_chemical_tank", "block_item"],
    ["atomic", "mekmm:advanced_mid_chemical_tank", "block_item"],
    ["atomic", "mekmm:advanced_oxidizing_factory", "block_item"],
    ["atomic", "mekmm:advanced_planting_factory", "block_item"],
    ["atomic", "mekmm:advanced_pressurised_reacting_factory", "block_item"],
    ["atomic", "mekmm:advanced_recycling_factory", "block_item"],
    ["atomic", "mekmm:advanced_replicating_factory", "block_item"],
    ["atomic", "mekmm:advanced_rolling_mill_factory", "block_item"],
    ["atomic", "mekmm:advanced_stamping_factory", "block_item"],
    ["atomic", "mekmm:advanced_washing_factory", "block_item"],
    ["atomic", "mekmm:basic_centrifuging_factory", "block_item"],
    ["atomic", "mekmm:basic_crystallizing_factory", "block_item"],
    ["atomic", "mekmm:basic_dissolving_factory", "block_item"],
    ["atomic", "mekmm:basic_lathing_factory", "block_item"],
    ["atomic", "mekmm:basic_liquifying_factory", "block_item"],
    ["atomic", "mekmm:basic_max_chemical_tank", "block_item"],
    ["atomic", "mekmm:basic_mid_chemical_tank", "block_item"],
    ["atomic", "mekmm:basic_oxidizing_factory", "block_item"],
    ["atomic", "mekmm:basic_planting_factory", "block_item"],
    ["atomic", "mekmm:basic_pressurised_reacting_factory", "block_item"],
    ["atomic", "mekmm:basic_recycling_factory", "block_item"],
    ["atomic", "mekmm:basic_replicating_factory", "block_item"],
    ["atomic", "mekmm:basic_rolling_mill_factory", "block_item"],
    ["atomic", "mekmm:basic_stamping_factory", "block_item"],
    ["atomic", "mekmm:basic_washing_factory", "block_item"],
    ["otherworldly", "mekmm:dense_centrifuging_factory", "block_item"],
    ["otherworldly", "mekmm:dense_crystallizing_factory", "block_item"],
    ["otherworldly", "mekmm:dense_dissolving_factory", "block_item"],
    ["otherworldly", "mekmm:dense_lathing_factory", "block_item"],
    ["otherworldly", "mekmm:dense_liquifying_factory", "block_item"],
    ["otherworldly", "mekmm:dense_oxidizing_factory", "block_item"],
    ["otherworldly", "mekmm:dense_planting_factory", "block_item"],
    ["otherworldly", "mekmm:dense_pressurised_reacting_factory", "block_item"],
    ["otherworldly", "mekmm:dense_recycling_factory", "block_item"],
    ["otherworldly", "mekmm:dense_replicating_factory", "block_item"],
    ["otherworldly", "mekmm:dense_rolling_mill_factory", "block_item"],
    ["otherworldly", "mekmm:dense_stamping_factory", "block_item"],
    ["otherworldly", "mekmm:dense_washing_factory", "block_item"],
    ["atomic", "mekmm:elite_centrifuging_factory", "block_item"],
    ["atomic", "mekmm:elite_crystallizing_factory", "block_item"],
    ["atomic", "mekmm:elite_dissolving_factory", "block_item"],
    ["atomic", "mekmm:elite_lathing_factory", "block_item"],
    ["atomic", "mekmm:elite_liquifying_factory", "block_item"],
    ["atomic", "mekmm:elite_max_chemical_tank", "block_item"],
    ["atomic", "mekmm:elite_mid_chemical_tank", "block_item"],
    ["atomic", "mekmm:elite_oxidizing_factory", "block_item"],
    ["atomic", "mekmm:elite_planting_factory", "block_item"],
    ["atomic", "mekmm:elite_pressurised_reacting_factory", "block_item"],
    ["atomic", "mekmm:elite_recycling_factory", "block_item"],
    ["atomic", "mekmm:elite_replicating_factory", "block_item"],
    ["atomic", "mekmm:elite_rolling_mill_factory", "block_item"],
    ["atomic", "mekmm:elite_stamping_factory", "block_item"],
    ["atomic", "mekmm:elite_washing_factory", "block_item"],
    ["atomic", "mekmm:large_chemical_infuser", "block_item"], // sole chemical-infusing machine since mekmm 1.3.3; the 8 *_chemical_infusing_factory tier locks were deleted 2026-07-31 (ids removed upstream, no successors)
    ["atomic", "mekmm:large_heat_generator", "block_item"],
    ["atomic", "mekmm:large_rotary_condensentrator", "block_item"],
    ["otherworldly", "mekmm:multiversal_centrifuging_factory", "block_item"],
    ["otherworldly", "mekmm:multiversal_crystallizing_factory", "block_item"],
    ["otherworldly", "mekmm:multiversal_dissolving_factory", "block_item"],
    ["otherworldly", "mekmm:multiversal_lathing_factory", "block_item"],
    ["otherworldly", "mekmm:multiversal_liquifying_factory", "block_item"],
    ["otherworldly", "mekmm:multiversal_oxidizing_factory", "block_item"],
    ["otherworldly", "mekmm:multiversal_planting_factory", "block_item"],
    ["otherworldly", "mekmm:multiversal_pressurised_reacting_factory", "block_item"],
    ["otherworldly", "mekmm:multiversal_recycling_factory", "block_item"],
    ["otherworldly", "mekmm:multiversal_replicating_factory", "block_item"],
    ["otherworldly", "mekmm:multiversal_rolling_mill_factory", "block_item"],
    ["otherworldly", "mekmm:multiversal_stamping_factory", "block_item"],
    ["otherworldly", "mekmm:multiversal_washing_factory", "block_item"],
    ["atomic", "mekmm:overclocked_centrifuging_factory", "block_item"],
    ["atomic", "mekmm:overclocked_crystallizing_factory", "block_item"],
    ["atomic", "mekmm:overclocked_dissolving_factory", "block_item"],
    ["atomic", "mekmm:overclocked_lathing_factory", "block_item"],
    ["atomic", "mekmm:overclocked_liquifying_factory", "block_item"],
    ["atomic", "mekmm:overclocked_oxidizing_factory", "block_item"],
    ["atomic", "mekmm:overclocked_planting_factory", "block_item"],
    ["atomic", "mekmm:overclocked_pressurised_reacting_factory", "block_item"],
    ["atomic", "mekmm:overclocked_recycling_factory", "block_item"],
    ["atomic", "mekmm:overclocked_replicating_factory", "block_item"],
    ["atomic", "mekmm:overclocked_rolling_mill_factory", "block_item"],
    ["atomic", "mekmm:overclocked_stamping_factory", "block_item"],
    ["atomic", "mekmm:overclocked_washing_factory", "block_item"],
    ["atomic", "mekmm:planting_station", "block_item"],
    ["otherworldly", "mekmm:quantum_centrifuging_factory", "block_item"],
    ["otherworldly", "mekmm:quantum_crystallizing_factory", "block_item"],
    ["otherworldly", "mekmm:quantum_dissolving_factory", "block_item"],
    ["otherworldly", "mekmm:quantum_lathing_factory", "block_item"],
    ["otherworldly", "mekmm:quantum_liquifying_factory", "block_item"],
    ["otherworldly", "mekmm:quantum_oxidizing_factory", "block_item"],
    ["otherworldly", "mekmm:quantum_planting_factory", "block_item"],
    ["otherworldly", "mekmm:quantum_pressurised_reacting_factory", "block_item"],
    ["otherworldly", "mekmm:quantum_recycling_factory", "block_item"],
    ["otherworldly", "mekmm:quantum_replicating_factory", "block_item"],
    ["otherworldly", "mekmm:quantum_rolling_mill_factory", "block_item"],
    ["otherworldly", "mekmm:quantum_stamping_factory", "block_item"],
    ["otherworldly", "mekmm:quantum_washing_factory", "block_item"],
    ["atomic", "mekmm:ultimate_centrifuging_factory", "block_item"],
    ["atomic", "mekmm:ultimate_crystallizing_factory", "block_item"],
    ["atomic", "mekmm:ultimate_dissolving_factory", "block_item"],
    ["atomic", "mekmm:ultimate_lathing_factory", "block_item"],
    ["atomic", "mekmm:ultimate_liquifying_factory", "block_item"],
    ["atomic", "mekmm:ultimate_max_chemical_tank", "block_item"],
    ["atomic", "mekmm:ultimate_mid_chemical_tank", "block_item"],
    ["atomic", "mekmm:ultimate_oxidizing_factory", "block_item"],
    ["atomic", "mekmm:ultimate_planting_factory", "block_item"],
    ["atomic", "mekmm:ultimate_pressurised_reacting_factory", "block_item"],
    ["atomic", "mekmm:ultimate_recycling_factory", "block_item"],
    ["atomic", "mekmm:ultimate_replicating_factory", "block_item"],
    ["atomic", "mekmm:ultimate_rolling_mill_factory", "block_item"],
    ["atomic", "mekmm:ultimate_stamping_factory", "block_item"],
    ["atomic", "mekmm:ultimate_washing_factory", "block_item"],
    ["atomic", "mekmm:wireless_charging_station", "block_item"],
    ["atomic", "mekanism_lasers:advanced_laser", "block_item"],
    ["atomic", "mekanism_lasers:advanced_toggleable_laser", "block_item"],
    ["atomic", "mekanism_lasers:basic_toggleable_laser", "block_item"],
    ["atomic", "mekanism_lasers:elite_laser", "block_item"],
    ["atomic", "mekanism_lasers:elite_toggleable_laser", "block_item"],
    ["atomic", "mekanism_lasers:energy_storage_casing", "block_item"],
    ["atomic", "mekanism_lasers:energy_storage_cell", "block_item"],
    ["atomic", "mekanism_lasers:laser_splitter", "block_item"],
    ["atomic", "mekanism_lasers:laser_stopper", "block_item"],
    ["atomic", "mekanism_lasers:ore_generator", "block_item"],
    ["atomic", "mekanism_lasers:ultimate_laser", "block_item"],
    ["atomic", "mekanism_lasers:ultimate_toggleable_laser", "block_item"],
    ["atomic", "mekanism_turrets:advanced_laser_turret", "block_item"],
    ["atomic", "mekanism_turrets:elite_laser_turret", "block_item"],
    ["atomic", "mekanism_turrets:ultimate_laser_turret", "block_item"],
  ]

  itemLocks.forEach(function (entry) { softItemLock(entry[0], entry[1], entry[2]) })
})()
