;(function () {
  if (typeof AStages === 'undefined') return

  // Ore blocks/tags are disguised as plain stone in-world by the ore-visibility
  // swap, and AStages' RightClickBlock hook tests the TARGET block against the
  // BLOCK_INTERACTIONS attribute. Locking interaction on a hidden ore made
  // placing a torch/block against it fail ("You don't know how to use the <ore>").
  // Allow block interaction for ore-like ids/tags only; machines stay guarded so
  // their GUIs can't be opened pre-stage. (Omitted arg => stays locked.)
  function aoaOreLikeId(id) {
    return /_ore$|:ore[a-z_]|deepslateore|rawore/.test(id)
  }
  function applySoftItemPolicy(restriction, allowBlockInteraction) {
    var configured = restriction
      .allowInventoryStorage()
      .allowContainerStorage()
      .allowPickup()
    if (allowBlockInteraction !== true) configured.disableBlockInteraction()
    // AStages 2.5 defaults keep locked entries hidden in EMI and conceal their names.
    return configured
  }

  function softItemLock(stage, item, kind) {
    if (typeof Item !== 'undefined' && typeof Item.exists === 'function' && !Item.exists(item)) {
      console.warn('[AoA AStages] Skipped missing item ' + item + ' (' + kind + ', stage=' + stage + ')')
      return
    }

    const id = 'aoa/item/' + kind + '/' + stage + '/' + item.replace(/[^a-zA-Z0-9_]/g, '_')
    try {
      applySoftItemPolicy(AStages.addRestrictionForItem(id, stage, item), aoaOreLikeId(item))
    } catch (e) {
      console.warn('[AoA AStages] Skipped missing item ' + item + ' (' + kind + ', stage=' + stage + '): ' + e)
    }
  }

  function softTagLock(stage, tag, kind) {
    const id = 'aoa/item_tag/' + kind + '/' + stage + '/' + tag.replace(/[^a-zA-Z0-9_]/g, '_')
    try {
      applySoftItemPolicy(AStages.addRestrictionForTag(id, stage, tag), aoaOreLikeId(tag))
    } catch (e) {
      console.warn('[AoA AStages] Skipped missing tag ' + tag + ' (' + kind + ', stage=' + stage + '): ' + e)
    }
  }

  const itemLocks = [
    ["ascension", "draconicevolution:chaotic_core", "item"],
    ["ascension", "extendedcrafting:ultimate_table", "item"],
    ["ascension", "oritech:unstable_container", "item"],
    ["ascension", "oritech:black_hole_block", "item"],
    ["otherworldly", "draconicevolution:draconium_ingot", "item"],
    // AvaritiaNeo prestige ingots â€” Weave 6 (Oritech unstable_container) consumes
    // crystal_matrix and neutron ingots as Ascension reagents. Lock them so the
    // weave's prestige framing isn't bypassed by earlier Avaritia crafting.
    ["ascension", "avaritia:crystal_matrix_ingot", "item"],
    ["ascension", "avaritia:neutronium_ingot", "item"],
    ["ascension", "avaritia:infinity_ingot", "item"],
    ["atomic", "alltheores:raw_uranium", "item"],
    ["atomic", "alltheores:raw_uranium_block", "item"],
    ["atomic", "alltheores:uranium_dust", "item"],
    ["atomic", "alltheores:uranium_ingot", "item"],
    ["atomic", "alltheores:uranium_nugget", "item"],
    ["atomic", "chemicalscience:circuitorganic", "item"],
    ["atomic", "chemicalscience:dust_plutoniumhydroxide", "item"],
    ["atomic", "chemicalscience:dust_plutoniumoxide", "item"],
    ["atomic", "chemicalscience:dust_thorium", "item"],
    ["atomic", "chemicalscience:dust_uranium", "item"],
    ["atomic", "chemicalscience:dust_uraniumoxide", "item"],
    ["atomic", "chemicalscience:impuredust_thorium", "item"],
    ["atomic", "chemicalscience:impuredust_uranium", "item"],
    ["atomic", "chemicalscience:platinum_thorium_catalyst", "item"],
    ["atomic", "electrodynamics:circuitelite", "item"],
    ["atomic", "electrodynamics:circuitultimate", "item"],
    ["atomic", "electrodynamics:raworeblockthorium", "item"],
    ["atomic", "electrodynamics:raworeblockuranium", "item"],
    ["atomic", "electrodynamics:raworethorium", "item"],
    ["atomic", "electrodynamics:raworeuranium", "item"],
    ["atomic", "mekanism:dust_uranium", "item"],
    ["atomic", "mekanism:ingot_uranium", "item"],
    ["atomic", "mekanism:nugget_uranium", "item"],
    ["atomic", "mekanism:raw_uranium", "item"],
    ["gilded_age", "oritech:overcharged_crystal", "item"],
    ["atomic", "oritech:prometheum_ingot", "item"],
    ["atomic", "oritech:plutonium_pellet", "item"],
    ["gilded_age", "oritech:flux_gate", "item"],
    ["atomic", "oritech:machine_core_6", "block_item"],
    ["atomic", "oritech:atomic_forge_block", "block_item"],
    ["atomic", "oritech:arcane_augment_station", "item"],
    ["atomic", "oritech:advanced_augment_station", "block_item"],
    ["atomic", "oritech:accelerator_controller", "item"],
    ["atomic", "oritech:enchantment_catalyst_block", "item"],
    ["atomic", "oritech:laser_arm_block", "item"],
    ["atomic", "ballistix:missiletier1", "item"],
    ["atomic", "createnuclear:reactor_controller", "item"],
    ["atomic", "nuclearscience:fissionreactorcore", "item"],
    ["atomic", "refinedstorage:wireless_grid", "item"],
    ["atomic", "refinedstorage:wireless_autocrafting_monitor", "item"],
    ["atomic", "refinedstorage:range_upgrade", "item"],
    ["atomic", "advanced_ae:adv_pattern_provider", "item"],
    ["atomic", "advanced_ae:small_adv_pattern_provider", "item"],
    ["atomic", "advanced_ae:adv_pattern_provider_upgrade", "item"],
    ["atomic", "advanced_ae:adv_pattern_provider_capacity_upgrade", "item"],
    ["atomic", "extendedae:ex_pattern_provider", "item"],
    ["atomic", "extendedae:ex_molecular_assembler", "item"],
    ["atomic", "extendedae:assembler_matrix_crafter", "item"],
    ["atomic", "hostile_neural_industrialization:electric_simulation_chamber", "item"],
    ["atomic", "hostile_neural_industrialization:large_simulation_chamber", "item"],
    ["atomic", "hostile_neural_industrialization:large_loot_fabricator", "item"],
    ["atomic", "hostile_neural_industrialization:mono_loot_fabricator", "item"],
    ["atomic", "mekanism:digital_miner", "item"],
    ["atomic", "industrialforegoing:infinity_drill", "item"],
    // Machine Staging Contract (2026-05-28): MEG basic/renewable generators are
    // Gilded-era power, not Atomic. gas_burning stays Atomic (burns Mekanism
    // gases = Atomic chemistry); fission/fusion/turbine stay Atomic/OW.
    ["gilded_age", "mekanismgenerators:wind_generator", "item"],
    ["gilded_age", "mekanismgenerators:solar_generator", "item"],
    ["gilded_age", "mekanismgenerators:solar_panel", "item"],
    ["gilded_age", "mekanismgenerators:advanced_solar_generator", "item"],
    ["gilded_age", "mekanismgenerators:bio_generator", "item"],
    ["atomic", "mekanismgenerators:gas_burning_generator", "item"],
    ["atomic", "mekanismgenerators:fission_reactor_casing", "item"],
    ["atomic", "mekanismgenerators:fission_fuel_assembly", "item"],
    ["atomic", "mekanismgenerators:fission_reactor_port", "item"],
    ["atomic", "mekanismgenerators:fission_reactor_logic_adapter", "item"],
    ["atomic", "mekanismgenerators:control_rod_assembly", "item"],
    ["atomic", "mekanismgenerators:reactor_glass", "item"],
    ["atomic", "mekanismgenerators:turbine_casing", "item"],
    ["atomic", "mekanismgenerators:turbine_valve", "item"],
    ["atomic", "mekanismgenerators:turbine_vent", "item"],
    ["atomic", "mekanismgenerators:turbine_rotor", "item"],
    ["atomic", "mekanismgenerators:turbine_blade", "item"],
    ["atomic", "mekanismgenerators:rotational_complex", "item"],
    ["atomic", "mekanismgenerators:electromagnetic_coil", "item"],
    ["atomic", "mekanismgenerators:saturating_condenser", "item"],
    ["gilded_age", "mekanismgenerators:heat_generator", "item"],
    ["atomic", "solarflux:photovoltaic_cell_4", "item"],
    ["atomic", "solarflux:photovoltaic_cell_5", "item"],
    ["atomic", "solarflux:photovoltaic_cell_6", "item"],
    ["atomic", "generatorgalore:diamond_generator", "item"],
    ["atomic", "generatorgalore:emerald_generator", "item"],
    ["atomic", "generatorgalore:ender_generator", "item"],
    ["atomic", "generatorgalore:diamond_generator_8x", "item"],
    ["atomic", "generatorgalore:emerald_generator_8x", "item"],
    ["atomic", "generatorgalore:ender_generator_8x", "item"],
    // 2026-08-08 owner ruling: obsidian generator joins its gem-tier siblings at atomic
    // (lock symmetry; block registration evidenced by the mod's own
    // data/generatorgalore/loot_table/blocks/obsidian_generator*.json in
    // generatorgalore-1.21.1-1.6.3.jar).
    ["atomic", "generatorgalore:obsidian_generator", "item"],
    ["atomic", "generatorgalore:obsidian_generator_8x", "item"],
    ["atomic", "mekanism:hazmat_mask", "item"],
    ["atomic", "mekanism:hazmat_gown", "item"],
    ["atomic", "mekanism:hazmat_pants", "item"],
    ["atomic", "mekanism:hazmat_boots", "item"],
    ["atomic", "nuclearscience:hazmathelmet", "item"],
    ["atomic", "nuclearscience:hazmatplate", "item"],
    ["atomic", "nuclearscience:hazmatlegs", "item"],
    ["atomic", "nuclearscience:hazmatboots", "item"],
    ["atomic", "nuclearscience:reinforcedhazmathelmet", "item"],
    ["atomic", "nuclearscience:reinforcedhazmatplate", "item"],
    ["atomic", "nuclearscience:reinforcedhazmatlegs", "item"],
    ["atomic", "nuclearscience:reinforcedhazmatboots", "item"],
    ["atomic", "alexscaves:hazmat_mask", "item"],
    ["atomic", "alexscaves:hazmat_chestplate", "item"],
    ["atomic", "alexscaves:hazmat_leggings", "item"],
    ["atomic", "alexscaves:hazmat_boots", "item"],
    ["atomic", "enderio:energetic_photovoltaic_module", "item"],
    ["atomic", "enderio:pulsating_photovoltaic_module", "item"],
    ["atomic", "enderio:vibrant_photovoltaic_module", "item"],
    ["atomic", "enderio:advanced_capacitor_bank", "item"],
    ["atomic", "enderio:vibrant_capacitor_bank", "item"],
    // Qliphoth arena-locator eyes gated to each sephirah's age (boss-ladder BL1, 2026-07-02):
    // Chesed = IR co-required exam, Malkuth = Gilded co-required exam, Geburah stays Atomic.
    ["gilded_age", "fdbosses:eye_of_malkuth", "item"],
    ["industrial_revolution", "fdbosses:eye_of_chesed", "item"],
    ["atomic", "fdbosses:eye_of_geburah", "item"],
    ["atomic", "macabre:valamon_heart", "item"],
    ["atomic", "macabre:gomoria_heart", "item"],
    ["atomic", "macabre:gargamaw_heart", "item"],
    ["atomic", "macabre:baal_heart", "item"],
    ["atomic", "macabre:morphegor_heart", "item"],
    // Perturbation summons the Dead God. Gated to Otherworldly so an Atomic player holding all five
    // prophet hearts cannot craft-and-summon the finale early. Master gate on the OW Macabre arc.
    ["otherworldly", "macabre:perturbation", "item"],
    ["atomic", "alltheores:uranium_block", "block_item"],
    ["atomic", "alltheores:raw_uranium_block", "block_item"],
    ["atomic", "chemicalscience:block_element_pu", "block_item"],
    ["atomic", "chemicalscience:block_element_th", "block_item"],
    ["atomic", "chemicalscience:block_element_u", "block_item"],
    ["atomic", "chemicalscience:ore_thorium_mars", "block_item"],
    ["atomic", "chemicalscience:ore_thorium_mercury", "block_item"],
    ["atomic", "chemicalscience:ore_thorium_moon", "block_item"],
    ["atomic", "chemicalscience:ore_thorium_venus", "block_item"],
    ["atomic", "chemicalscience:ore_uranium_mars", "block_item"],
    ["atomic", "chemicalscience:ore_uranium_mercury", "block_item"],
    ["atomic", "chemicalscience:ore_uranium_moon", "block_item"],
    ["atomic", "chemicalscience:ore_uranium_venus", "block_item"],
    ["atomic", "electrodynamics:deepslateorethorium", "block_item"],
    ["atomic", "electrodynamics:deepslateoreuranium", "block_item"],
    ["atomic", "electrodynamics:orethorium", "block_item"],
    ["atomic", "electrodynamics:oreuranium", "block_item"],
    ["atomic", "electrodynamics:raworeblockthorium", "block_item"],
    ["atomic", "electrodynamics:raworeblockuranium", "block_item"],
    ["atomic", "mekanism:block_uranium", "block_item"],
    ["atomic", "mekanism:block_raw_uranium", "block_item"],
    ["the_renaissance", "minecraft:deepslate_emerald_ore", "item"],
    ["the_renaissance", "minecraft:emerald", "item"],
    ["the_renaissance", "minecraft:emerald_block", "item"],
    ["the_renaissance", "minecraft:emerald_ore", "item"],
    ["otherworldly", "moderndynamics:superconductor_cable", "item"],
    ["gilded_age", "oritech:processing_unit", "item"],
    // R5 Prompt 04: Oritech core-one augment station belongs to IR, not Gilded.
    ["industrial_revolution", "oritech:simple_augment_station", "item"],
    ["gilded_age", "oritech:biosteel_ingot", "item"],
    ["gilded_age", "oritech:enderic_lens", "item"],
    ["gilded_age", "theurgy:mercury_catalyst", "item"],
    ["gilded_age", "occultism:book_of_binding_afrit", "item"],
    ["gilded_age", "ae2:molecular_assembler", "item"],
    ["gilded_age", "ae2:pattern_provider", "item"],
    ["gilded_age", "ae2:cable_pattern_provider", "item"],
    ["gilded_age", "ae2:wireless_access_point", "item"],
    ["gilded_age", "ae2:wireless_terminal", "item"],
    ["gilded_age", "ae2:wireless_crafting_terminal", "item"],
    ["gilded_age", "ae2:wireless_receiver", "item"],
    ["gilded_age", "ae2:wireless_booster", "item"],
    ["gilded_age", "ae2wtlib:wireless_universal_terminal", "item"],
    ["gilded_age", "ae2wtlib:wireless_pattern_access_terminal", "item"],
    ["gilded_age", "ae2wtlib:wireless_pattern_encoding_terminal", "item"],
    ["gilded_age", "integratedcrafting:part_interface_crafting", "item"],
    ["gilded_age", "integratedcrafting:part_crafting_writer", "item"],
    ["gilded_age", "hostilenetworks:deep_learner", "item"],
    ["gilded_age", "hostilenetworks:sim_chamber", "item"],
    ["gilded_age", "hostilenetworks:loot_fabricator", "item"],
    ["gilded_age", "hostilenetworks:blank_data_model", "item"],
    ["gilded_age", "hostilenetworks:prediction_matrix", "item"],
    ["gilded_age", "mekanismtools:bronze_paxel", "item"],
    ["gilded_age", "mekanismtools:iron_paxel", "item"],
    ["gilded_age", "mekanismtools:gold_paxel", "item"],
    ["gilded_age", "mekanismtools:diamond_paxel", "item"],
    // NauTec is the Gilded oceanic/biotech anchor. Keep its signature surfaces
    // in Gilded without making common cast/prismarine substrates inventory-hostage items.
    ["gilded_age", "nautec:aquatic_catalyst", "block_item"],
    ["gilded_age", "nautec:aquatic_chip", "item"],
    ["gilded_age", "nautec:damaged_aquatic_chip", "item"],
    ["gilded_age", "nautec:deep_sea_drain", "block_item"],
    ["gilded_age", "nautec:bacterial_analyzer", "block_item"],
    ["gilded_age", "nautec:bacterial_containment_shield", "block_item"],
    ["gilded_age", "nautec:prismarine_laser_relay", "block_item"],
    ["gilded_age", "nautec:long_distance_laser", "block_item"],
    ["gilded_age", "nautec:laser_junction", "block_item"],
    ["gilded_age", "nautec:aquarine_steel_ingot", "item"],
    ["gilded_age", "nautec:aquarine_steel_compound", "item"],
    ["gilded_age", "nautec:prismatic_battery", "item"],
    ["gilded_age", "nautec:augmentation_station", "block_item"],
    ["gilded_age", "nautec:augmentation_station_extension", "block_item"],
    ["gilded_age", "nautec:bio_reactor", "block_item"],
    ["gilded_age", "nautec:incubator", "block_item"],
    ["gilded_age", "nautec:mutator", "block_item"],
    ["gilded_age", "nautec:mixer", "block_item"],
    ["gilded_age", "industrialforegoing:laser_drill", "item"],
    ["gilded_age", "industrialforegoing:ore_laser_base", "item"],
    ["gilded_age", "industrialforegoing:fluid_laser_base", "item"],
    ["gilded_age", "industrialforegoing:simulated_hydroponic_bed", "item"],
    ["gilded_age", "industrialforegoing:hydroponic_simulation_processor", "item"],
    ["gilded_age", "industrialforegoingsouls:soul_laser_base", "item"],
    ["gilded_age", "industrialforegoingsouls:soul_surge", "item"],
    // R5 Prompt 04: Create Ore Excavation is an IR resource-system lesson.
    ["industrial_revolution", "createoreexcavation:vein_finder", "item"],
    ["industrial_revolution", "createoreexcavation:drilling_machine", "item"],
    ["industrial_revolution", "createoreexcavation:extractor", "item"],
    ["atomic", "oritech:deep_drill_block", "item"],
    ["gilded_age", "oritech:quarry_addon", "item"],
    ["gilded_age", "enderio:crafter", "item"],
    ["gilded_age", "enderio:powered_spawner", "item"],
    ["gilded_age", "enderio:wireless_charger", "item"],
    ["gilded_age", "enderio:wireless_charger_antenna", "item"],
    ["gilded_age", "enderio:wireless_charger_antenna_advanced", "item"],
    ["the_renaissance", "minecraft:emerald_block", "block_item"],
    ["the_renaissance", "minecraft:emerald_ore", "block_item"],
    ["the_renaissance", "minecraft:deepslate_emerald_ore", "block_item"],
    ["industrial_revolution", "ae2:inscriber", "item"],
    ["industrial_revolution", "bosses_of_mass_destruction:obsidian_heart", "item"],
    ["industrial_revolution", "cataclysm:lava_power_cell", "item"],
    ["industrial_revolution", "mekanism:alloy_atomic", "item"],
    ["industrial_revolution", "mekanism:basic_energy_cube", "item"],
    ["industrial_revolution", "mekanism:basic_control_circuit", "item"],
    ["industrial_revolution", "mekanismtools:wood_paxel", "item"],
    ["industrial_revolution", "mekanismtools:stone_paxel", "item"],
    // Mekanism core machine access starts in Industrial Revolution. These
    // locks prevent Renaissance loot, trades, quest rewards, or accidental
    // crafting routes from opening the Mekanism machine body early.
    ["industrial_revolution", "mekanism:metallurgic_infuser", "block_item"],
    ["industrial_revolution", "mekanism:enrichment_chamber", "block_item"],
    ["industrial_revolution", "mekanism:crusher", "block_item"],
    ["industrial_revolution", "mekanism:energized_smelter", "block_item"],
    ["industrial_revolution", "mekanism:osmium_compressor", "block_item"],
    ["industrial_revolution", "mekanism:combiner", "block_item"],
    ["industrial_revolution", "mekanism:purification_chamber", "block_item"],
    ["industrial_revolution", "mekanism:chemical_injection_chamber", "block_item"],
    ["industrial_revolution", "mekanism:chemical_infuser", "block_item"],
    ["industrial_revolution", "mekanism:electrolytic_separator", "block_item"],
    ["industrial_revolution", "mekanism:pressurized_reaction_chamber", "block_item"],
    ["industrial_revolution", "mekanism:precision_sawmill", "block_item"],
    ["industrial_revolution", "mekanism:formulaic_assemblicator", "block_item"],
    ["industrial_revolution", "mekanism:rotary_condensentrator", "block_item"],
    ["industrial_revolution", "mekanism:resistive_heater", "block_item"],
    ["industrial_revolution", "mekanism:fuelwood_heater", "block_item"],
    ["industrial_revolution", "mekanism:chargepad", "block_item"],
    ["industrial_revolution", "mekanism:security_desk", "block_item"],
    ["industrial_revolution", "mekanism:basic_bin", "block_item"],
    ["industrial_revolution", "mekanism:basic_fluid_tank", "block_item"],
    ["industrial_revolution", "mekanism:basic_chemical_tank", "block_item"],
    ["industrial_revolution", "mekanism:basic_universal_cable", "block_item"],
    ["industrial_revolution", "mekanism:basic_logistical_transporter", "block_item"],
    ["industrial_revolution", "mekanism:restrictive_transporter", "block_item"],
    ["industrial_revolution", "mekanism:diversion_transporter", "block_item"],
    ["industrial_revolution", "mekanism:basic_mechanical_pipe", "block_item"],
    ["industrial_revolution", "mekanism:basic_pressurized_tube", "block_item"],
    ["industrial_revolution", "mekanism:basic_thermodynamic_conductor", "block_item"],
    ["industrial_revolution", "mekanism:basic_smelting_factory", "block_item"],
    ["industrial_revolution", "mekanism:basic_enriching_factory", "block_item"],
    ["industrial_revolution", "mekanism:basic_crushing_factory", "block_item"],
    ["industrial_revolution", "mekanism:basic_compressing_factory", "block_item"],
    ["industrial_revolution", "mekanism:basic_combining_factory", "block_item"],
    ["industrial_revolution", "mekanism:basic_purifying_factory", "block_item"],
    ["industrial_revolution", "mekanism:basic_injecting_factory", "block_item"],
    ["industrial_revolution", "mekanism:basic_infusing_factory", "block_item"],
    ["industrial_revolution", "mekanism:basic_sawing_factory", "block_item"],
    ["industrial_revolution", "mekanism:dynamic_tank", "block_item"],
    ["industrial_revolution", "mekanism:dynamic_valve", "block_item"],
    ["industrial_revolution", "mekanism:thermal_evaporation_block", "block_item"],
    ["industrial_revolution", "mekanism:thermal_evaporation_controller", "block_item"],
    ["industrial_revolution", "mekanism:thermal_evaporation_valve", "block_item"],
    // Machine Staging Contract pass (2026-05-28) â€” Mekanism gating gaps.
    // electric_pump + fluidic_plenisher are IR-tier siblings of the core machines
    // above but were unlocked; lock to IR for anti-leak parity.
    ["industrial_revolution", "mekanism:electric_pump", "block_item"],
    ["industrial_revolution", "mekanism:fluidic_plenisher", "block_item"],
    // dimensional_stabilizer (chunk-loader) + modification_station (MekaSuit/Meka-Tool
    // module install) route through c:circuits/ultimate (atomic), so they are
    // naturally >= atomic; add explicit item locks to close the loot/trade/reward leak.
    ["atomic", "mekanism:dimensional_stabilizer", "block_item"],
    ["atomic", "mekanism:modification_station", "block_item"],
    // antiprotonic_nucleosynthesizer consumes antimatter pellets (post-fusion = OW).
    ["otherworldly", "mekanism:antiprotonic_nucleosynthesizer", "block_item"],
    ["industrial_revolution", "modern_industrialization:bronze_machine_casing", "item"],
    ["industrial_revolution", "railways:fuel_tank", "item"],
    ["the_renaissance", "projectred_core:red_ingot", "item"],
    ["industrial_revolution", "forbidden_arcanus:aureal_tank", "item"],
    ["industrial_revolution", "forbidden_arcanus:smelter_prism", "item"],
    ["industrial_revolution", "immersiveengineering:capacitor_hv", "item"],
    ["industrial_revolution", "immersiveengineering:fluid_pump", "item"],
    ["industrial_revolution", "immersiveengineering:high_power_biodiesel_bucket", "item"],
    ["industrial_revolution", "immersiveengineering:wirecoil_steel", "item"],
    ["industrial_revolution", "enderio:basic_capacitor", "item"],
    ["atomic", "modularforcefields:coercionderiver", "item"],
    ["atomic", "modularforcefields:fortronfieldprojector", "item"],
    ["industrial_revolution", "psi:cad_assembler", "item"],
    ["otherworldly", "mahoutsukai:morgan", "endgame one-shot weapon, post-End gate"],
    ["industrial_revolution", "solarflux:photovoltaic_cell_2", "item"],
    ["industrial_revolution", "solarflux:photovoltaic_cell_3", "item"],
    ["industrial_revolution", "powergrid:electric_motor", "item"],
    ["industrial_revolution", "createaddition:alternator", "item"],
    ["industrial_revolution", "create_new_age:basic_energiser", "item"],
    ["industrial_revolution", "pneumaticcraft:pressure_chamber_wall", "block_item"],
    ["industrial_revolution", "theurgy:digestion_vat", "item"],
    ["industrial_revolution", "occultism:book_of_binding_djinni", "item"],
    ["industrial_revolution", "oritech:adamant_ingot", "item"],
    ["atomic", "modularforcefields:focusmatrix", "item"],
    ["industrial_revolution", "oritech:machine_frame_block", "block_item"],
    ["industrial_revolution", "oritech:machine_core_1", "block_item"],
    ["otherworldly", "stellaris:rocket", "item"],
    ["otherworldly", "occultism:book_of_binding_marid", "item"],
    ["otherworldly", "ae2:quantum_link", "item"],
    ["otherworldly", "ae2:quantum_ring", "item"],
    ["otherworldly", "ae2:quantum_entangled_singularity", "item"],
    ["otherworldly", "refinedstorage:network_transmitter", "item"],
    ["otherworldly", "refinedstorage:network_receiver", "item"],
    ["otherworldly", "mekanism:qio_dashboard", "item"],
    ["otherworldly", "mekanism:portable_qio_dashboard", "item"],
    ["otherworldly", "mekanism:qio_drive_array", "item"],
    ["otherworldly", "mekanism:qio_drive_base", "item"],
    ["otherworldly", "mekanism:qio_drive_hyper_dense", "item"],
    ["otherworldly", "mekanism:qio_drive_supermassive", "item"],
    ["otherworldly", "mekanism:qio_drive_time_dilating", "item"],
    ["otherworldly", "mekanism:qio_importer", "item"],
    ["otherworldly", "mekanism:qio_exporter", "item"],
    ["otherworldly", "mekanism:qio_redstone_adapter", "item"],
    ["otherworldly", "mekanism:teleporter", "item"],
    ["otherworldly", "mekanism:teleporter_frame", "item"],
    ["otherworldly", "mekanism:portable_teleporter", "item"],
    ["otherworldly", "advanced_ae:quantum_crafter", "item"],
    ["otherworldly", "advanced_ae:quantum_crafter_terminal", "item"],
    ["otherworldly", "advanced_ae:wireless_quantum_crafter_terminal", "item"],
    ["otherworldly", "advanced_ae:quantum_core", "item"],
    ["otherworldly", "advanced_ae:quantum_unit", "item"],
    ["otherworldly", "extendedae:wireless_hub", "item"],
    ["otherworldly", "extendedae:wireless_connect", "item"],
    ["otherworldly", "extendedae:wireless_ex_pat", "item"],
    ["otherworldly", "mekanismgenerators:fusion_reactor_controller", "item"],
    ["otherworldly", "mekanismgenerators:fusion_reactor_frame", "item"],
    ["otherworldly", "mekanismgenerators:fusion_reactor_port", "item"],
    ["otherworldly", "mekanismgenerators:fusion_reactor_logic_adapter", "item"],
    ["otherworldly", "mekanismgenerators:laser_focus_matrix", "item"],
    ["otherworldly", "mekanismgenerators:hohlraum", "item"],
    ["otherworldly", "mekanismgenerators:fusion_fuel_bucket", "item"],
    ["otherworldly", "generatorgalore:netherite_generator", "item"],
    ["otherworldly", "generatorgalore:netherstar_generator", "item"],
    ["otherworldly", "generatorgalore:netherite_generator_8x", "item"],
    ["otherworldly", "generatorgalore:netherstar_generator_8x", "item"],
    ["otherworldly", "generatorgalore:ender_generator_64x", "item"],
    ["otherworldly", "generatorgalore:netherite_generator_64x", "item"],
    ["otherworldly", "generatorgalore:netherstar_generator_64x", "item"],
    ["industrial_revolution", "mekanismtools:lapis_lazuli_paxel", "item"],
    ["industrial_revolution", "mekanismtools:osmium_paxel", "item"],
    ["atomic", "mekanismtools:refined_glowstone_paxel", "item"],
    ["atomic", "mekanismtools:refined_obsidian_paxel", "item"],
    ["industrial_revolution", "mekanismtools:steel_paxel", "item"],
    ["atomic", "mekanismtools:netherite_paxel", "item"],
    ["the_renaissance", "aether:cloud_staff", "item"],
    ["the_renaissance", "alltheores:lead_dust", "item"],
    ["the_renaissance", "alltheores:lead_ingot", "item"],
    ["the_renaissance", "alltheores:lead_nugget", "item"],
    ["the_renaissance", "alltheores:nickel_dust", "item"],
    ["the_renaissance", "alltheores:nickel_ingot", "item"],
    ["the_renaissance", "alltheores:nickel_nugget", "item"],
    ["the_renaissance", "alltheores:osmium_dust", "item"],
    ["the_renaissance", "alltheores:osmium_ingot", "item"],
    ["the_renaissance", "alltheores:osmium_nugget", "item"],
    ["the_renaissance", "alltheores:platinum_dust", "item"],
    ["the_renaissance", "alltheores:platinum_ingot", "item"],
    ["the_renaissance", "alltheores:platinum_nugget", "item"],
    ["the_renaissance", "alltheores:raw_lead", "item"],
    ["the_renaissance", "alltheores:raw_lead_block", "item"],
    ["the_renaissance", "alltheores:raw_nickel", "item"],
    ["the_renaissance", "alltheores:raw_nickel_block", "item"],
    ["the_renaissance", "alltheores:raw_osmium", "item"],
    ["the_renaissance", "alltheores:raw_osmium_block", "item"],
    ["the_renaissance", "alltheores:raw_platinum", "item"],
    ["the_renaissance", "alltheores:raw_platinum_block", "item"],
    ["the_renaissance", "alltheores:raw_silver", "item"],
    ["the_renaissance", "alltheores:raw_silver_block", "item"],
    ["the_renaissance", "alltheores:silver_dust", "item"],
    ["the_renaissance", "alltheores:silver_ingot", "item"],
    ["the_renaissance", "alltheores:silver_nugget", "item"],
    ["otherworldly", "cataclysm:cursium_ingot", "item"],
    ["the_renaissance", "cataclysm:cursed_eye", "item"],
    ["industrial_revolution", "deeperdarker:soul_elytra", "item"],
    // Vanilla elytra rides an end-ship item frame, not a loot table, so no loot
    // replacer can reach it. The soft policy is the gate: it stays pickup-able
    // and storable, but the default equipment lock means no flight until IR. This
    // is deliberate parity with soul_elytra above (owner ruling 2026-08-02).
    ["industrial_revolution", "minecraft:elytra", "item"],
    // Shulker shells are the chokepoint for every portable shulker-box route
    // (vanilla box, BetterNether's box recipe, and the whole sophisticatedstorage
    // shulker line all consume shells), so this one lock moves portable storage
    // to IR without touching Renaissance's static diamond chests and barrels.
    // The paired Ren-tier diamond_shulker_box line in aoa_astages_07 was moved to
    // IR in the same pass so the two layers agree (owner ruling 2026-08-02).
    ["industrial_revolution", "minecraft:shulker_shell", "item"],
    ["industrial_revolution", "mekanism:dust_lead", "item"],
    ["industrial_revolution", "mekanism:dust_osmium", "item"],
    ["industrial_revolution", "mekanism:ingot_lead", "item"],
    ["industrial_revolution", "mekanism:ingot_osmium", "item"],
    ["industrial_revolution", "mekanism:nugget_lead", "item"],
    ["industrial_revolution", "mekanism:nugget_osmium", "item"],
    ["industrial_revolution", "mekanism:raw_lead", "item"],
    ["industrial_revolution", "mekanism:raw_osmium", "item"],
    ["the_renaissance", "minecraft:beacon", "item"],
    ["the_renaissance", "minecraft:deepslate_diamond_ore", "item"],
    ["medieval_times", "minecraft:diamond", "item"],
    ["the_renaissance", "minecraft:diamond_axe", "item"],
    ["the_renaissance", "minecraft:diamond_block", "item"],
    ["the_renaissance", "minecraft:diamond_boots", "item"],
    ["the_renaissance", "minecraft:diamond_chestplate", "item"],
    ["the_renaissance", "minecraft:diamond_helmet", "item"],
    ["the_renaissance", "minecraft:diamond_hoe", "item"],
    ["the_renaissance", "minecraft:diamond_leggings", "item"],
    ["the_renaissance", "minecraft:diamond_ore", "item"],
    ["the_renaissance", "minecraft:diamond_pickaxe", "item"],
    ["the_renaissance", "minecraft:diamond_shovel", "item"],
    ["the_renaissance", "minecraft:diamond_sword", "item"],
    ["the_renaissance", "minecraft:enchanting_table", "item"],
    ["the_renaissance", "minecraft:end_crystal", "item"],
    ["gilded_age", "deep_aether:stratus_ingot", "item"],
    ["the_renaissance", "betternether:cincinnasite", "item"],
    ["the_renaissance", "eternalnether:soul_stone", "item"],
    ["the_renaissance", "eternal_starlight:orb_of_prophecy", "item"],
    ["the_renaissance", "eternal_starlight:thermal_springstone", "item"],
    ["industrial_revolution", "undergarden:catalyst", "item"],
    ["industrial_revolution", "undergarden:crumbling_catalyst", "item"],
    ["the_renaissance", "block_factorys_bosses:underworld_arena_key", "item"],
    ["the_renaissance", "block_factorys_bosses:ancient_trial_key", "item"],
    ["the_renaissance", "bosses_of_mass_destruction:soul_star", "item"],
    ["the_renaissance", "bosses_of_mass_destruction:void_lily", "item"],
    // 2026-08-08 owner ruling: blazing_eye (Nether Gauntlet proof, see
    // boss_progression_proof.js) gets the same Renaissance lock as its sibling proofs.
    ["the_renaissance", "bosses_of_mass_destruction:blazing_eye", "item"],
    ["industrial_revolution", "bosses_of_mass_destruction:obsidilith_rune", "item"],
    // 2026-05-30 canon: AE2 and Refined Storage start in Industrial Revolution.
    ["industrial_revolution", "ae2:fluix_crystal", "item"],
    ["industrial_revolution", "refinedstorage:processor_binding", "item"],
    ["the_renaissance", "spectrum:connection_node", "item"],
    ["the_renaissance", "spectrum:gather_node", "item"],
    ["the_renaissance", "spectrum:provider_node", "item"],
    ["the_renaissance", "spectrum:sender_node", "item"],
    ["the_renaissance", "spectrum:storage_node", "item"],

    // Spectrum teleport ladder. Intra-dimensional idols open with the rest of
    // Renaissance Spectrum content. The cross-dim teleport items, the Deeper
    // Down portal block, and the ritual mechanism (bedrock anvil + midnight
    // solution) belong with Spectrum's Atomic placement (mod author labels
    // Deeper Down access as midgame; AoA places that tier at Atomic).
    ["atomic", "spectrum:ender_splice", "item"],
    ["atomic", "spectrum:perturbed_eye", "item"],
    ["atomic", "spectrum:radiating_ender", "block_item"],
    ["atomic", "spectrum:bedrock_anvil", "block_item"],
    ["atomic", "spectrum:midnight_solution", "block_item"],
    ["atomic", "spectrum:midnight_solution_bucket", "item"],
    ["atomic", "spectrum:deeper_down_portal", "block_item"],
    ["the_renaissance", "malum:spirit_altar", "item"],
    ["gilded_age", "actuallyadditions:iron_casing", "item"],
    ["the_renaissance", "actuallyadditions:basic_coil", "item"],
    ["the_renaissance", "projectred_core:plate", "item"],
    ["industrial_revolution", "cabletiers:elite_importer", "item"],
    ["the_renaissance", "theurgy:calcination_oven", "item"],
    ["the_renaissance", "minecraft:diamond_block", "block_item"],
    ["the_renaissance", "minecraft:enchanting_table", "block_item"],
    ["the_renaissance", "minecraft:beacon", "block_item"],
    ["the_renaissance", "alltheores:lead_ore", "block_item"],
    ["the_renaissance", "alltheores:deepslate_lead_ore", "block_item"],
    ["the_renaissance", "alltheores:nether_lead_ore", "block_item"],
    ["the_renaissance", "alltheores:end_lead_ore", "block_item"],
    ["the_renaissance", "alltheores:other_lead_ore", "block_item"],
    ["the_renaissance", "alltheores:lead_block", "block_item"],
    ["the_renaissance", "alltheores:raw_lead_block", "block_item"],
    ["the_renaissance", "alltheores:nickel_ore", "block_item"],
    ["the_renaissance", "alltheores:deepslate_nickel_ore", "block_item"],
    ["the_renaissance", "alltheores:nether_nickel_ore", "block_item"],
    ["the_renaissance", "alltheores:end_nickel_ore", "block_item"],
    ["the_renaissance", "alltheores:nickel_block", "block_item"],
    ["the_renaissance", "alltheores:raw_nickel_block", "block_item"],
    ["the_renaissance", "alltheores:silver_ore", "block_item"],
    ["the_renaissance", "alltheores:deepslate_silver_ore", "block_item"],
    ["the_renaissance", "alltheores:nether_silver_ore", "block_item"],
    ["the_renaissance", "alltheores:end_silver_ore", "block_item"],
    ["the_renaissance", "alltheores:other_silver_ore", "block_item"],
    ["the_renaissance", "alltheores:silver_block", "block_item"],
    ["the_renaissance", "alltheores:raw_silver_block", "block_item"],
    ["the_renaissance", "alltheores:osmium_ore", "block_item"],
    ["the_renaissance", "alltheores:deepslate_osmium_ore", "block_item"],
    ["the_renaissance", "alltheores:nether_osmium_ore", "block_item"],
    ["the_renaissance", "alltheores:end_osmium_ore", "block_item"],
    ["the_renaissance", "alltheores:other_osmium_ore", "block_item"],
    ["the_renaissance", "alltheores:osmium_block", "block_item"],
    ["the_renaissance", "alltheores:raw_osmium_block", "block_item"],
    ["the_renaissance", "alltheores:platinum_ore", "block_item"],
    ["the_renaissance", "alltheores:deepslate_platinum_ore", "block_item"],
    ["the_renaissance", "alltheores:nether_platinum_ore", "block_item"],
    ["the_renaissance", "alltheores:end_platinum_ore", "block_item"],
    ["the_renaissance", "alltheores:other_platinum_ore", "block_item"],
    ["the_renaissance", "alltheores:platinum_block", "block_item"],
    ["the_renaissance", "alltheores:raw_platinum_block", "block_item"],
    ["atomic", "alltheores:uranium_ore", "block_item"],
    ["atomic", "alltheores:deepslate_uranium_ore", "block_item"],
    ["atomic", "alltheores:nether_uranium_ore", "block_item"],
    ["atomic", "alltheores:end_uranium_ore", "block_item"],
    ["atomic", "alltheores:other_uranium_ore", "block_item"],
    ["industrial_revolution", "mekanism:lead_ore", "block_item"],
    ["industrial_revolution", "mekanism:deepslate_lead_ore", "block_item"],
    ["industrial_revolution", "mekanism:block_lead", "block_item"],
    ["industrial_revolution", "mekanism:block_raw_lead", "block_item"],
    ["industrial_revolution", "mekanism:osmium_ore", "block_item"],
    ["industrial_revolution", "mekanism:deepslate_osmium_ore", "block_item"],
    ["industrial_revolution", "mekanism:block_osmium", "block_item"],
    ["industrial_revolution", "mekanism:block_raw_osmium", "block_item"],
    ["atomic", "mekanism:uranium_ore", "block_item"],
    ["atomic", "mekanism:deepslate_uranium_ore", "block_item"],
    ["atomic", "mekanism:advanced_energy_cube", "block_item"],
    ["atomic", "mekanism:elite_energy_cube", "block_item"],
    ["atomic", "mekanism:ultimate_energy_cube", "block_item"],
    ["atomic", "mekanism:advanced_bin", "block_item"],
    ["atomic", "mekanism:elite_bin", "block_item"],
    ["atomic", "mekanism:ultimate_bin", "block_item"],
    ["atomic", "mekanism:advanced_fluid_tank", "block_item"],
    ["atomic", "mekanism:elite_fluid_tank", "block_item"],
    ["atomic", "mekanism:ultimate_fluid_tank", "block_item"],
    ["atomic", "mekanism:advanced_chemical_tank", "block_item"],
    ["atomic", "mekanism:elite_chemical_tank", "block_item"],
    ["atomic", "mekanism:ultimate_chemical_tank", "block_item"],
    ["atomic", "mekanism:advanced_universal_cable", "block_item"],
    ["atomic", "mekanism:elite_universal_cable", "block_item"],
    ["atomic", "mekanism:ultimate_universal_cable", "block_item"],
    ["atomic", "mekanism:advanced_logistical_transporter", "block_item"],
    ["atomic", "mekanism:elite_logistical_transporter", "block_item"],
    ["atomic", "mekanism:ultimate_logistical_transporter", "block_item"],
    ["atomic", "mekanism:advanced_mechanical_pipe", "block_item"],
    ["atomic", "mekanism:elite_mechanical_pipe", "block_item"],
    ["atomic", "mekanism:ultimate_mechanical_pipe", "block_item"],
    ["atomic", "mekanism:advanced_pressurized_tube", "block_item"],
    ["atomic", "mekanism:elite_pressurized_tube", "block_item"],
    ["atomic", "mekanism:ultimate_pressurized_tube", "block_item"],
    ["atomic", "mekanism:advanced_thermodynamic_conductor", "block_item"],
    ["atomic", "mekanism:elite_thermodynamic_conductor", "block_item"],
    ["atomic", "mekanism:ultimate_thermodynamic_conductor", "block_item"],
    ["atomic", "mekanism:advanced_smelting_factory", "block_item"],
    ["atomic", "mekanism:elite_smelting_factory", "block_item"],
    ["atomic", "mekanism:ultimate_smelting_factory", "block_item"],
    ["atomic", "mekanism:advanced_enriching_factory", "block_item"],
    ["atomic", "mekanism:elite_enriching_factory", "block_item"],
    ["atomic", "mekanism:ultimate_enriching_factory", "block_item"],
    ["atomic", "mekanism:advanced_crushing_factory", "block_item"],
    ["atomic", "mekanism:elite_crushing_factory", "block_item"],
    ["atomic", "mekanism:ultimate_crushing_factory", "block_item"],
    ["atomic", "mekanism:advanced_compressing_factory", "block_item"],
    ["atomic", "mekanism:elite_compressing_factory", "block_item"],
    ["atomic", "mekanism:ultimate_compressing_factory", "block_item"],
    ["atomic", "mekanism:advanced_combining_factory", "block_item"],
    ["atomic", "mekanism:elite_combining_factory", "block_item"],
    ["atomic", "mekanism:ultimate_combining_factory", "block_item"],
    ["atomic", "mekanism:advanced_purifying_factory", "block_item"],
    ["atomic", "mekanism:elite_purifying_factory", "block_item"],
    ["atomic", "mekanism:ultimate_purifying_factory", "block_item"],
    ["atomic", "mekanism:advanced_injecting_factory", "block_item"],
    ["atomic", "mekanism:elite_injecting_factory", "block_item"],
    ["atomic", "mekanism:ultimate_injecting_factory", "block_item"],
    ["atomic", "mekanism:advanced_infusing_factory", "block_item"],
    ["atomic", "mekanism:elite_infusing_factory", "block_item"],
    ["atomic", "mekanism:ultimate_infusing_factory", "block_item"],
    ["atomic", "mekanism:advanced_sawing_factory", "block_item"],
    ["atomic", "mekanism:elite_sawing_factory", "block_item"],
    ["atomic", "mekanism:ultimate_sawing_factory", "block_item"],
    ["atomic", "mekanism:chemical_oxidizer", "block_item"],
    ["atomic", "mekanism:chemical_dissolution_chamber", "block_item"],
    ["atomic", "mekanism:chemical_washer", "block_item"],
    ["atomic", "mekanism:chemical_crystallizer", "block_item"],
    ["atomic", "mekanism:isotopic_centrifuge", "block_item"],
    ["atomic", "mekanism:solar_neutron_activator", "block_item"],
    ["atomic", "mekanism:induction_casing", "block_item"],
    ["atomic", "mekanism:induction_port", "block_item"],
    ["atomic", "mekanism:basic_induction_cell", "block_item"],
    ["atomic", "mekanism:advanced_induction_cell", "block_item"],
    ["atomic", "mekanism:elite_induction_cell", "block_item"],
    ["atomic", "mekanism:ultimate_induction_cell", "block_item"],
    ["atomic", "mekanism:basic_induction_provider", "block_item"],
    ["atomic", "mekanism:advanced_induction_provider", "block_item"],
    ["atomic", "mekanism:elite_induction_provider", "block_item"],
    ["atomic", "mekanism:ultimate_induction_provider", "block_item"],
    ["atomic", "mekanism:boiler_casing", "block_item"],
    ["atomic", "mekanism:boiler_valve", "block_item"],
    ["atomic", "mekanism:laser", "block_item"],
    ["atomic", "mekanism:laser_amplifier", "block_item"],
    ["atomic", "mekanism:laser_tractor_beam", "block_item"],
    ["atomic", "appmek:chemical_cell_housing", "item"],
    ["gilded_age", "blastcraft:blastcompressor", "block_item"],
    ["otherworldly", "evolvedmekanism:dense_control_circuit", "item"],
    ["otherworldly", "evolvedmekanism:dense_energy_cube", "block_item"],
    ["atomic", "extradisks:advanced_machine_casing", "block_item"],
    ["atomic", "extrastorage:advanced_exporter", "block_item"],
    ["atomic", "industrialization_overdrive:multi_processing_array", "block_item"],
    ["atomic", "mekanism_lasers:basic_laser", "block_item"],
    ["atomic", "mekanism_turrets:basic_laser_turret", "block_item"],
    ["atomic", "mekmm:large_gas_burning_generator", "block_item"],
    ["atomic", "mekmm:wireless_transmission_station", "block_item"],
    ["atomic", "oritechthings:addon_block_capacitor_tier_4", "block_item"],
    ["atomic", "refinedstorage_mekanism_integration:64b_chemical_storage_part", "item"],
    ["atomic", "refinedstorage_quartz_arsenal:wireless_crafting_grid", "item"],
    ["atomic", "integratedtunnels:part_player_simulator", "item"],
    ["gilded_age", "appliedpneumatics:me_pressure_interface_block", "block_item"],
    ["medieval_times", "create_integrated_farming:fishing_net", "block_item"],
    ["medieval_times", "create_integrated_farming:roost", "block_item"],
    // R5 Prompt 04: basic Create Diesel Generators starts in IR; huge diesel stays later.
    ["industrial_revolution", "createdieselgenerators:diesel_engine", "block_item"],
    ["industrial_revolution", "createdieselgenerators:pumpjack_crank", "block_item"],
    ["gilded_age", "createpropulsion:coral_generator", "block_item"],
    ["gilded_age", "expandedae:exp_encoding_terminal", "item"],
    ["gilded_age", "extended_industrialization:large_configurable_chest", "block_item"],
    ["gilded_age", "immeng:wirecoil_me", "item"],
    ["gilded_age", "megacells:mega_item_cell_housing", "item"],
    ["gilded_age", "more_immersive_wires:ae_connector", "block_item"],
    ["medieval_times", "botanypots:terracotta_hopper_botany_pot", "block_item"],
    ["industrial_revolution", "assemblyline:autocrafter", "block_item"],
    ["industrial_revolution", "bellsandwhistles:metro_casing", "block_item"],
    ["medieval_times", "botanypots:terracotta_botany_pot", "block_item"],
    ["industrial_revolution", "create_dragons_plus:blaze_upgrade_smithing_template", "item"],
    ["industrial_revolution", "create_sa:drone_controller", "item"],
    ["industrial_revolution", "electroenergetics:alternator_rotor", "block_item"],
    ["industrial_revolution", "extendedterminal:compat_processor", "item"],
    ["industrial_revolution", "ifeu:apple_core", "item"],
    ["industrial_revolution", "immersive_aircraft:engine", "item"],
    ["industrial_revolution", "immersive_machinery:iron_drill", "item"],
    ["industrial_revolution", "immersivepetroleum:distillation_tower", "block_item"],
    ["industrial_revolution", "immersivepetroleum:gas_generator", "block_item"],
    ["industrial_revolution", "integrateddynamics:cable", "block_item"],
    ["industrial_revolution", "integrateddynamics:drying_basin", "block_item"],
    ["industrial_revolution", "integrateddynamics:logic_programmer", "block_item"],
    ["industrial_revolution", "integrateddynamics:mechanical_drying_basin", "block_item"],
    ["industrial_revolution", "integratedterminals:part_terminal_storage", "item"],
    ["industrial_revolution", "mifa:netherite_gear", "item"],
    ["industrial_revolution", "mm_farming:block_controller_system", "block_item"],
    ["industrial_revolution", "mm_farming:block_farm_controller_plant", "block_item"],
    ["industrial_revolution", "projectred_expansion:auto_crafter", "block_item"],
    ["industrial_revolution", "projectred_integration:state_cell_gate", "item"],
    ["industrial_revolution", "projectred_transmission:neutral_bundled_wire", "block_item"],
    ["medieval_times", "sliceanddice:slicer", "block_item"],
    ["the_renaissance", "sophisticatedstorage:controller", "block_item"],
    ["industrial_revolution", "voltaic:upgradebasiccapacity", "item"],
    ["gilded_age", "astral_dimension:astral_dimension", "item"],
    ["otherworldly", "interdimensionalwirelesstransmitter:black_interdimensional_wireless_transmitter", "block_item"],
    ["the_renaissance", "alchemists_garden:alpha_shroom_staff", "item"],
    ["the_renaissance", "constructionwand:core_angel", "item"],
    ["the_renaissance", "create:mechanical_drill", "block_item"],
    ["medieval_times", "create:brass_casing", "block_item"],
    ["medieval_times", "create:crushing_wheel", "block_item"],
    ["medieval_times", "create:mechanical_press", "block_item"],
    // Market re-tiered medieval_times -> the_renaissance (owner ruling 2026-07-31).
    // Its preset offer list is codec-defaulted `orElse(true)` and
    // disabledDefaultPresets is empty, so it sells 17 BetterNether flora for
    // 1 emerald each. BetterNether is Renaissance content (see the betternether
    // locks in this file; every BN quest lives in ren_magic_foundations), so a
    // Medieval Market leaked Renaissance flora. Gating the Market itself to
    // Renaissance closes the leak without touching the mod's preset config.
    ["the_renaissance", "farmingforblockheads:market", "block_item"],
    ["the_renaissance", "monsterplus:ancient_crystal", "item"],
    ["gilded_age", "mowziesmobs:sol_visage", "item"],
    ["medieval_times", "mowziesmobs:wrought_axe", "item"],
    ["the_renaissance", "projectred_transmission:red_alloy_wire", "item"],
    ["the_renaissance", "reliquified_artifacts:mimi_dust", "item"],
    ["medieval_times", "waystones:waystone", "block_item"],
    // Keep one CFB gate aligned to the Medieval kitchen quest instead of locking every dye variant.
    ["medieval_times", "cookingforblockheads:white_oven", "block_item"],

    // R5 Prompt 04 base tier repair: Create advanced contraptions, oil, pressure,
    // IE multiblocks, and required Renaissance realm-spine entry items.
    ["medieval_times", "create:deployer", "block_item"],
    ["the_renaissance", "create:mechanical_crafter", "block_item"],
    ["the_renaissance", "create:steam_engine", "block_item"],
    ["the_renaissance", "create:track", "block_item"],
    ["the_renaissance", "create:track_station", "block_item"],
    ["the_renaissance", "create:track_signal", "block_item"],
    ["the_renaissance", "create:track_observer", "block_item"],
    ["the_renaissance", "create:controls", "block_item"],
    ["the_renaissance", "createrailwaysnavigator:train_station_clock", "block_item"],
    ["industrial_revolution", "createdieselgenerators:bulk_fermenter", "block_item"],
    ["industrial_revolution", "createdieselgenerators:distillation_tank", "block_item"],
    ["industrial_revolution", "createdieselgenerators:distillation_controller", "block_item"],
    ["industrial_revolution", "createdieselgenerators:large_diesel_engine", "block_item"],
    ["gilded_age", "createdieselgenerators:huge_diesel_engine", "block_item"],
    ["industrial_revolution", "immersivepetroleum:pumpjack", "block_item"],
    ["industrial_revolution", "immersivepetroleum:derrick", "block_item"],
    ["industrial_revolution", "immersivepetroleum:oiltank", "block_item"],
    // Oil-doc reconciliation (2026-06-15): hydrotreater/coker unlock with IR petrochem quests.
    ["industrial_revolution", "immersivepetroleum:hydrotreater", "block_item"],
    ["industrial_revolution", "immersivepetroleum:coker_unit", "block_item"],
    ["the_renaissance", "spectrum:pigment_palette", "item"],
    ["the_renaissance", "spectrum:pedestal_all_basic", "block_item"],
    ["the_renaissance", "spectrum:pedestal_basic_amethyst", "block_item"],
    ["the_renaissance", "spectrum:pedestal_basic_citrine", "block_item"],
    ["the_renaissance", "spectrum:pedestal_basic_topaz", "block_item"],
    ["atomic", "spectrum:pedestal_moonstone", "block_item"],
    ["the_renaissance", "spectrum:pedestal_onyx", "block_item"],
    ["the_renaissance", "netherex:hoglin_tusk", "item"],
    ["the_renaissance", "netherex:ribs", "item"],
    ["the_renaissance", "netherex:kiln", "block_item"],
    ["industrial_revolution", "pneumaticcraft:air_compressor", "block_item"],
    ["industrial_revolution", "pneumaticcraft:pressure_tube", "block_item"],
    ["industrial_revolution", "pneumaticcraft:pressure_gauge", "item"],
    ["industrial_revolution", "pneumaticcraft:pressure_chamber_glass", "block_item"],
    ["industrial_revolution", "pneumaticcraft:pressure_chamber_valve", "block_item"],
    ["industrial_revolution", "pneumaticcraft:pressure_chamber_interface", "block_item"],
    ["industrial_revolution", "pneumaticcraft:ingot_iron_compressed", "item"],
    ["industrial_revolution", "pneumaticcraft:empty_pcb", "item"],
    ["industrial_revolution", "pneumaticcraft:transistor", "item"],
    ["industrial_revolution", "pneumaticcraft:capacitor", "item"],
    ["industrial_revolution", "pneumaticcraft:refinery", "block_item"],
    ["industrial_revolution", "pneumaticcraft:refinery_output", "block_item"],
    ["industrial_revolution", "pneumaticcraft:thermopneumatic_processing_plant", "block_item"],
    ["industrial_revolution", "pneumaticcraft:plastic", "item"],
    ["industrial_revolution", "pneumaticcraft:biodiesel_bucket", "item"],
    ["industrial_revolution", "pneumaticcraft:lpg_bucket", "item"],
    ["industrial_revolution", "pneumaticcraft:plastic_bucket", "item"],
    ["medieval_times", "immersiveengineering:cokebrick", "block_item"],
    ["medieval_times", "immersiveengineering:coke_oven", "block_item"],
    ["the_renaissance", "immersiveengineering:blastbrick", "block_item"],
    // 2026-08-08 owner ruling: crude blast furnace unlocks in the_renaissance (steel is
    // period-correct there; the Medieval metallurgy chapter already quests IE coke).
    // The advanced_blast_furnace below stays industrial_revolution.
    ["the_renaissance", "immersiveengineering:blast_furnace", "block_item"],
    ["industrial_revolution", "immersiveengineering:crusher", "block_item"],
    ["industrial_revolution", "immersiveengineering:metal_press", "block_item"],
    ["industrial_revolution", "immersiveengineering:mixer", "block_item"],
    ["industrial_revolution", "immersiveengineering:sawmill", "block_item"],
    ["industrial_revolution", "immersiveengineering:auto_workbench", "block_item"],
    ["industrial_revolution", "immersiveengineering:silo", "block_item"],
    ["medieval_times", "immersiveengineering:tank", "block_item"],
    ["industrial_revolution", "immersiveengineering:shelf", "block_item"],
    ["industrial_revolution", "immersiveengineering:workbench", "block_item"],
    ["gilded_age", "immersiveengineering:arc_furnace", "block_item"],
    // Retiered gilded -> IR 2026-08-05: the IR early-factory quest has players
    // form this multiblock, and the blastfurnace_preheater already sits at IR
    // (01d_immersive.js). Pairs with the g5 duplicate quest deletion
    // (immersiveengineering_questline_verification_2026-08-05.md F5).
    ["industrial_revolution", "immersiveengineering:advanced_blast_furnace", "block_item"],
    // Oil-doc reconciliation (2026-05-28): IE bio-refining (refinery/fermenter/squeezer/
    // diesel_generator) is the IR fuel-cycle mainline, not Gilded. excavator stays Gilded.
    ["industrial_revolution", "immersiveengineering:refinery", "block_item"],
    ["gilded_age", "immersiveengineering:excavator", "block_item"],
    ["industrial_revolution", "immersiveengineering:fermenter", "block_item"],
    ["industrial_revolution", "immersiveengineering:squeezer", "block_item"],
    ["industrial_revolution", "immersiveengineering:diesel_generator", "block_item"],
    ["gilded_age", "immersiveengineering:assembler", "block_item"],
    ["gilded_age", "immersiveengineering:bucket_wheel", "block_item"],

    // R47-R88: cross-mod armor leak coverage, verified against live jar lang/model evidence.
    ["the_renaissance", "betterend:thallasium_helmet", "item"],
    ["the_renaissance", "betterend:thallasium_chestplate", "item"],
    ["the_renaissance", "betterend:thallasium_leggings", "item"],
    ["the_renaissance", "betterend:thallasium_boots", "item"],
    ["the_renaissance", "betterend:terminite_helmet", "item"],
    ["the_renaissance", "betterend:terminite_chestplate", "item"],
    ["the_renaissance", "betterend:terminite_leggings", "item"],
    ["the_renaissance", "betterend:terminite_boots", "item"],
    ["industrial_revolution", "betterend:crystalite_helmet", "item"],
    ["industrial_revolution", "betterend:crystalite_chestplate", "item"],
    ["industrial_revolution", "betterend:crystalite_leggings", "item"],
    ["industrial_revolution", "betterend:crystalite_boots", "item"],
    ["industrial_revolution", "betterend:aeternium_helmet", "item"],
    ["industrial_revolution", "betterend:aeternium_chestplate", "item"],
    ["industrial_revolution", "betterend:aeternium_leggings", "item"],
    ["industrial_revolution", "betterend:aeternium_boots", "item"],
    // Aeternium tools sit at the same tier as the armor above. They are already
    // gated in practice because aeternium smithing consumes a netherite ingot
    // (locked industrial_revolution in aoa_astages_06), so these lines make the
    // existing gate explicit rather than leaving it implied by one ingredient.
    ["industrial_revolution", "betterend:aeternium_sword", "item"],
    ["industrial_revolution", "betterend:aeternium_pickaxe", "item"],
    ["industrial_revolution", "betterend:aeternium_axe", "item"],
    ["industrial_revolution", "betterend:aeternium_shovel", "item"],
    ["industrial_revolution", "betterend:aeternium_hoe", "item"],
    ["industrial_revolution", "betterend:aeternium_hammer", "item"],
    ["the_renaissance", "aether:zanite_helmet", "item"],
    ["the_renaissance", "aether:zanite_chestplate", "item"],
    ["the_renaissance", "aether:zanite_leggings", "item"],
    ["the_renaissance", "aether:zanite_boots", "item"],
    ["the_renaissance", "aether:zanite_gloves", "item"],
    ["the_renaissance", "aether:skyroot_pickaxe", "item"],
    ["the_renaissance", "aether:holystone_pickaxe", "item"],
    ["the_renaissance", "aether:zanite_gemstone", "item"],
    ["the_renaissance", "aether:golden_amber", "item"],
    ["the_renaissance", "aether:bronze_dungeon_key", "item"],
    ["gilded_age", "aether:gravitite_helmet", "item"],
    ["gilded_age", "aether:gravitite_chestplate", "item"],
    ["gilded_age", "aether:gravitite_leggings", "item"],
    ["gilded_age", "aether:gravitite_boots", "item"],
    ["gilded_age", "aether:gravitite_gloves", "item"],
    ["gilded_age", "aether:gravitite_sword", "item"],
    ["gilded_age", "aether:gravitite_axe", "item"],
    ["gilded_age", "aether:gravitite_pickaxe", "item"],
    ["gilded_age", "aether:gravitite_shovel", "item"],
    ["gilded_age", "aether:gravitite_hoe", "item"],
    ["gilded_age", "aether:enchanted_gravitite", "item"],
    ["the_renaissance", "aether:neptune_helmet", "item"],
    ["the_renaissance", "aether:neptune_chestplate", "item"],
    ["the_renaissance", "aether:neptune_leggings", "item"],
    ["the_renaissance", "aether:neptune_boots", "item"],
    ["the_renaissance", "aether:neptune_gloves", "item"],
    ["industrial_revolution", "aether:obsidian_helmet", "item"],
    ["industrial_revolution", "aether:obsidian_chestplate", "item"],
    ["industrial_revolution", "aether:obsidian_leggings", "item"],
    ["industrial_revolution", "aether:obsidian_boots", "item"],
    ["industrial_revolution", "aether:obsidian_gloves", "item"],
    ["the_renaissance", "aether:sentry_boots", "item"],
    ["gilded_age", "aether:gold_dungeon_key", "item"],
    ["gilded_age", "aether:sun_altar", "item"],
    ["gilded_age", "aether:phoenix_bow", "item"],
    ["gilded_age", "aether:phoenix_helmet", "item"],
    ["gilded_age", "aether:phoenix_chestplate", "item"],
    ["gilded_age", "aether:phoenix_leggings", "item"],
    ["gilded_age", "aether:phoenix_boots", "item"],
    ["gilded_age", "aether:phoenix_gloves", "item"],
    ["gilded_age", "aether:vampire_blade", "item"],
    ["gilded_age", "aether:pig_slayer", "item"],
    ["gilded_age", "aether:iron_bubble", "item"],
    ["gilded_age", "aether:life_shard", "item"],
    ["gilded_age", "aether:ice_pendant", "item"],
    ["gilded_age", "aether:ice_ring", "item"],
    ["gilded_age", "aether:aerogel", "item"],
    ["the_renaissance", "aether:silver_dungeon_key", "item"],
    // victory_medal is the Renaissance Valkyrie Queen fight-trigger (given to her by
    // right-click USE); it is a prerequisite for the required ren_aether_literacy boss,
    // not later gear, so it must unlock at the_renaissance (was mis-tiered to IR alongside
    // the Valkyrie armor, softlocking the Queen fight until IR). 2026-07-20 medal audit.
    ["the_renaissance", "aether:victory_medal", "item"],
    ["gilded_age", "deep_aether:aercloud_necklace", "item"],
    ["gilded_age", "deep_aether:brass_dungeon_key", "item"],
    ["gilded_age", "deep_aether:sun_core", "item"],
    ["gilded_age", "deep_aether:afterburner", "item"],
    ["gilded_age", "deep_aether:skyjade", "item"],
    ["gilded_age", "deep_aether:bio_crystal", "item"],
    ["gilded_age", "deep_aether:golden_swet_ball", "item"],
    ["gilded_age", "deep_aether:gravitite_ring", "item"],
    ["industrial_revolution", "aether:valkyrie_helmet", "item"],
    ["industrial_revolution", "aether:valkyrie_chestplate", "item"],
    ["industrial_revolution", "aether:valkyrie_leggings", "item"],
    ["industrial_revolution", "aether:valkyrie_boots", "item"],
    ["industrial_revolution", "aether:valkyrie_gloves", "item"],
    ["gilded_age", "deep_aether:skyjade_helmet", "item"],
    ["gilded_age", "deep_aether:skyjade_chestplate", "item"],
    ["gilded_age", "deep_aether:skyjade_leggings", "item"],
    ["gilded_age", "deep_aether:skyjade_boots", "item"],
    ["gilded_age", "deep_aether:stratus_helmet", "item"],
    ["gilded_age", "deep_aether:stratus_chestplate", "item"],
    ["gilded_age", "deep_aether:stratus_leggings", "item"],
    ["gilded_age", "deep_aether:stratus_boots", "item"],
    ["gilded_age", "deep_aether:stormforged_helmet", "item"],
    ["gilded_age", "deep_aether:stormforged_chestplate", "item"],
    ["gilded_age", "deep_aether:stormforged_leggings", "item"],
    ["gilded_age", "deep_aether:stormforged_boots", "item"],
    ["industrial_revolution", "undergarden:cloggrum_helmet", "item"],
    ["industrial_revolution", "undergarden:cloggrum_chestplate", "item"],
    ["industrial_revolution", "undergarden:cloggrum_leggings", "item"],
    ["industrial_revolution", "undergarden:cloggrum_boots", "item"],
    ["industrial_revolution", "undergarden:froststeel_helmet", "item"],
    ["industrial_revolution", "undergarden:froststeel_chestplate", "item"],
    ["industrial_revolution", "undergarden:froststeel_leggings", "item"],
    ["industrial_revolution", "undergarden:froststeel_boots", "item"],
    ["industrial_revolution", "undergarden:utherium_helmet", "item"],
    ["industrial_revolution", "undergarden:utherium_chestplate", "item"],
    ["industrial_revolution", "undergarden:utherium_leggings", "item"],
    ["industrial_revolution", "undergarden:utherium_boots", "item"],
    ["industrial_revolution", "undergarden:ancient_helmet", "item"],
    ["industrial_revolution", "undergarden:ancient_chestplate", "item"],
    ["industrial_revolution", "undergarden:ancient_leggings", "item"],
    ["industrial_revolution", "deeperdarker:resonarium_helmet", "item"],
    ["industrial_revolution", "deeperdarker:resonarium_chestplate", "item"],
    ["industrial_revolution", "deeperdarker:resonarium_leggings", "item"],
    ["industrial_revolution", "deeperdarker:resonarium_boots", "item"],
    ["gilded_age", "deeperdarker:warden_helmet", "item"],
    ["gilded_age", "deeperdarker:warden_chestplate", "item"],
    ["gilded_age", "deeperdarker:warden_leggings", "item"],
    ["gilded_age", "deeperdarker:warden_boots", "item"],
    ["the_renaissance", "unusualend:chorus_helmet", "item"],
    ["the_renaissance", "unusualend:warped_boots", "item"],
    ["the_renaissance", "unusualend:warped_chestplate", "item"],
    ["industrial_revolution", "unusualend:spectral_leggings", "item"],
    ["gilded_age", "unusualend:spirit_grim_helmet", "item"],
    ["gilded_age", "unusualend:spirit_malice_helmet", "item"],
    ["gilded_age", "unusualend:spirit_mania_helmet", "item"],
    ["gilded_age", "unusualend:spirit_smile_helmet", "item"],
    ["gilded_age", "unusualend:spirit_twist_helmet", "item"],
    ["gilded_age", "unusualend:spirit_vice_helmet", "item"],
    ["industrial_revolution", "forbidden_arcanus:draco_arcanus_helmet", "item"],
    ["industrial_revolution", "forbidden_arcanus:draco_arcanus_chestplate", "item"],
    ["industrial_revolution", "forbidden_arcanus:draco_arcanus_leggings", "item"],
    ["industrial_revolution", "forbidden_arcanus:draco_arcanus_boots", "item"],
    ["the_renaissance", "forbidden_arcanus:mortem_helmet", "item"],
    ["the_renaissance", "forbidden_arcanus:mortem_chestplate", "item"],
    ["the_renaissance", "forbidden_arcanus:mortem_leggings", "item"],
    ["the_renaissance", "forbidden_arcanus:mortem_boots", "item"],
    ["industrial_revolution", "forbidden_arcanus:tyr_helmet", "item"],
    ["industrial_revolution", "forbidden_arcanus:tyr_chestplate", "item"],
    ["industrial_revolution", "forbidden_arcanus:tyr_leggings", "item"],
    ["industrial_revolution", "forbidden_arcanus:tyr_boots", "item"],
    ["the_renaissance", "eternal_starlight:deepsilver_helmet", "item"],
    ["the_renaissance", "eternal_starlight:deepsilver_chestplate", "item"],
    ["the_renaissance", "eternal_starlight:deepsilver_leggings", "item"],
    ["the_renaissance", "eternal_starlight:deepsilver_boots", "item"],
    ["the_renaissance", "eternal_starlight:thermal_springstone_helmet", "item"],
    ["the_renaissance", "eternal_starlight:thermal_springstone_chestplate", "item"],
    ["the_renaissance", "eternal_starlight:thermal_springstone_leggings", "item"],
    ["the_renaissance", "eternal_starlight:thermal_springstone_boots", "item"],
    ["the_renaissance", "eternal_starlight:glacite_helmet", "item"],
    ["the_renaissance", "eternal_starlight:glacite_chestplate", "item"],
    ["the_renaissance", "eternal_starlight:glacite_leggings", "item"],
    ["the_renaissance", "eternal_starlight:glacite_boots", "item"],
    ["industrial_revolution", "eternal_starlight:starlit_diamond_helmet", "item"],
    ["industrial_revolution", "eternal_starlight:starlit_diamond_chestplate", "item"],
    ["industrial_revolution", "eternal_starlight:starlit_diamond_leggings", "item"],
    ["industrial_revolution", "eternal_starlight:starlit_diamond_boots", "item"],
    ["industrial_revolution", "eternal_starlight:unrealium_helmet", "item"],
    ["industrial_revolution", "eternal_starlight:unrealium_chestplate", "item"],
    ["industrial_revolution", "eternal_starlight:unrealium_leggings", "item"],
    ["industrial_revolution", "eternal_starlight:unrealium_boots", "item"],
    ["industrial_revolution", "eternal_starlight:aethersent_hood", "item"],
    ["industrial_revolution", "eternal_starlight:aethersent_cape", "item"],
    ["industrial_revolution", "eternal_starlight:aethersent_bottoms", "item"],
    ["industrial_revolution", "eternal_starlight:aethersent_boots", "item"],
    ["the_renaissance", "eternal_starlight:air_sac_boots", "item"],
    ["the_renaissance", "eternal_starlight:air_sac_mask", "item"],
    ["the_renaissance", "eternal_starlight:amaramber_chestplate", "item"],
    ["the_renaissance", "eternal_starlight:amaramber_mask", "item"],
    ["the_renaissance", "eternal_starlight:alchemist_robe", "item"],
    ["the_renaissance", "eternal_starlight:alchemist_mask", "item"],
    ["industrial_revolution", "mekanismtools:bronze_helmet", "item"],
    ["industrial_revolution", "mekanismtools:bronze_chestplate", "item"],
    ["industrial_revolution", "mekanismtools:bronze_leggings", "item"],
    ["industrial_revolution", "mekanismtools:bronze_boots", "item"],
    ["industrial_revolution", "mekanismtools:lapis_lazuli_helmet", "item"],
    ["industrial_revolution", "mekanismtools:lapis_lazuli_chestplate", "item"],
    ["industrial_revolution", "mekanismtools:lapis_lazuli_leggings", "item"],
    ["industrial_revolution", "mekanismtools:lapis_lazuli_boots", "item"],
    ["industrial_revolution", "mekanismtools:steel_helmet", "item"],
    ["industrial_revolution", "mekanismtools:steel_chestplate", "item"],
    ["industrial_revolution", "mekanismtools:steel_leggings", "item"],
    ["industrial_revolution", "mekanismtools:steel_boots", "item"],
    ["gilded_age", "mekanismtools:osmium_helmet", "item"],
    ["gilded_age", "mekanismtools:osmium_chestplate", "item"],
    ["gilded_age", "mekanismtools:osmium_leggings", "item"],
    ["gilded_age", "mekanismtools:osmium_boots", "item"],
    ["atomic", "mekanismtools:refined_glowstone_helmet", "item"],
    ["atomic", "mekanismtools:refined_glowstone_chestplate", "item"],
    ["atomic", "mekanismtools:refined_glowstone_leggings", "item"],
    ["atomic", "mekanismtools:refined_glowstone_boots", "item"],
    ["atomic", "mekanismtools:refined_obsidian_helmet", "item"],
    ["atomic", "mekanismtools:refined_obsidian_chestplate", "item"],
    ["atomic", "mekanismtools:refined_obsidian_leggings", "item"],
    ["atomic", "mekanismtools:refined_obsidian_boots", "item"],

    // Mekanism Tools weapons/tools/shields. Armor for these tiers was already
    // gated above, but the swords/picks/axes/shovels/hoes/shields were not -
    // and Mekanism Tools' mob-gear-spawn feature puts a weapon IN HAND, so an
    // ungated refined_obsidian_sword could leak even while the armor was locked.
    // Each weapon is gated to the SAME age as its material's armor.
    ["industrial_revolution", "mekanismtools:bronze_sword", "item"],
    ["industrial_revolution", "mekanismtools:bronze_pickaxe", "item"],
    ["industrial_revolution", "mekanismtools:bronze_axe", "item"],
    ["industrial_revolution", "mekanismtools:bronze_shovel", "item"],
    ["industrial_revolution", "mekanismtools:bronze_hoe", "item"],
    ["industrial_revolution", "mekanismtools:bronze_shield", "item"],
    ["industrial_revolution", "mekanismtools:lapis_lazuli_sword", "item"],
    ["industrial_revolution", "mekanismtools:lapis_lazuli_pickaxe", "item"],
    ["industrial_revolution", "mekanismtools:lapis_lazuli_axe", "item"],
    ["industrial_revolution", "mekanismtools:lapis_lazuli_shovel", "item"],
    ["industrial_revolution", "mekanismtools:lapis_lazuli_hoe", "item"],
    ["industrial_revolution", "mekanismtools:lapis_lazuli_shield", "item"],
    ["industrial_revolution", "mekanismtools:steel_sword", "item"],
    ["industrial_revolution", "mekanismtools:steel_pickaxe", "item"],
    ["industrial_revolution", "mekanismtools:steel_axe", "item"],
    ["industrial_revolution", "mekanismtools:steel_shovel", "item"],
    ["industrial_revolution", "mekanismtools:steel_hoe", "item"],
    ["industrial_revolution", "mekanismtools:steel_shield", "item"],
    ["gilded_age", "mekanismtools:osmium_sword", "item"],
    ["gilded_age", "mekanismtools:osmium_pickaxe", "item"],
    ["gilded_age", "mekanismtools:osmium_axe", "item"],
    ["gilded_age", "mekanismtools:osmium_shovel", "item"],
    ["gilded_age", "mekanismtools:osmium_hoe", "item"],
    ["gilded_age", "mekanismtools:osmium_shield", "item"],
    ["atomic", "mekanismtools:refined_glowstone_sword", "item"],
    ["atomic", "mekanismtools:refined_glowstone_pickaxe", "item"],
    ["atomic", "mekanismtools:refined_glowstone_axe", "item"],
    ["atomic", "mekanismtools:refined_glowstone_shovel", "item"],
    ["atomic", "mekanismtools:refined_glowstone_hoe", "item"],
    ["atomic", "mekanismtools:refined_glowstone_shield", "item"],
    ["atomic", "mekanismtools:refined_obsidian_sword", "item"],
    ["atomic", "mekanismtools:refined_obsidian_pickaxe", "item"],
    ["atomic", "mekanismtools:refined_obsidian_axe", "item"],
    ["atomic", "mekanismtools:refined_obsidian_shovel", "item"],
    ["atomic", "mekanismtools:refined_obsidian_hoe", "item"],
    ["atomic", "mekanismtools:refined_obsidian_shield", "item"],

    // Evolved Mekanism "Better Gold" and "Plaslitherite" gear. These were the
    // exact items the Discord report flagged dropping from early-age mobs, and
    // they had NO gate at all. Both are Atomic-tier crafts: Better Gold needs
    // mekanism:spent_nuclear_waste (fission byproduct); Plaslitherite is forged
    // in the Evolved Mekanism chemixing machine (already Atomic content).
    // Plaslitherite armor (chestplate 14 / toughness 5) out-classes Netherite.
    ["atomic", "evolvedmekanism:better_gold_sword", "item"],
    ["atomic", "evolvedmekanism:better_gold_pickaxe", "item"],
    ["atomic", "evolvedmekanism:better_gold_axe", "item"],
    ["atomic", "evolvedmekanism:better_gold_shovel", "item"],
    ["atomic", "evolvedmekanism:better_gold_hoe", "item"],
    ["atomic", "evolvedmekanism:better_gold_paxel", "item"],
    ["atomic", "evolvedmekanism:better_gold_shield", "item"],
    ["atomic", "evolvedmekanism:better_gold_helmet", "item"],
    ["atomic", "evolvedmekanism:better_gold_chestplate", "item"],
    ["atomic", "evolvedmekanism:better_gold_leggings", "item"],
    ["atomic", "evolvedmekanism:better_gold_boots", "item"],
    ["atomic", "evolvedmekanism:plaslitherite_sword", "item"],
    ["atomic", "evolvedmekanism:plaslitherite_pickaxe", "item"],
    ["atomic", "evolvedmekanism:plaslitherite_axe", "item"],
    ["atomic", "evolvedmekanism:plaslitherite_shovel", "item"],
    ["atomic", "evolvedmekanism:plaslitherite_hoe", "item"],
    ["atomic", "evolvedmekanism:plaslitherite_paxel", "item"],
    ["atomic", "evolvedmekanism:plaslitherite_shield", "item"],
    ["atomic", "evolvedmekanism:plaslitherite_helmet", "item"],
    ["atomic", "evolvedmekanism:plaslitherite_chestplate", "item"],
    ["atomic", "evolvedmekanism:plaslitherite_leggings", "item"],
    ["atomic", "evolvedmekanism:plaslitherite_boots", "item"],

    // R106-R163: automation, logistics, Mekanism apex, and Iron Furnaces leak coverage.
    ["industrial_revolution", "projectred_expansion:block_breaker", "block_item"],
    ["industrial_revolution", "projectred_expansion:deployer", "block_item"],
    ["industrial_revolution", "projectred_expansion:transposer", "block_item"],
    ["industrial_revolution", "projectred_expansion:frame_motor", "block_item"],
    ["the_renaissance", "projectred_expansion:frame_actuator", "block_item"],
    ["gilded_age", "industrialforegoing:block_breaker", "block_item"],
    ["gilded_age", "industrialforegoing:block_placer", "block_item"],
    ["gilded_age", "industrialforegoing:plant_gatherer", "block_item"],
    ["gilded_age", "industrialforegoing:plant_sower", "block_item"],
    ["gilded_age", "industrialforegoing:plant_fertilizer", "block_item"],
    ["gilded_age", "industrialforegoing:wither_builder", "block_item"],
    ["gilded_age", "industrialforegoing:material_stonework_factory", "block_item"],
    ["gilded_age", "industrialforegoing:fluid_extractor", "block_item"],
    ["gilded_age", "industrialforegoing:dye_mixer", "block_item"],
    ["gilded_age", "industrialforegoing:fluid_collector", "block_item"],
    ["gilded_age", "industrialforegoing:fluid_placer", "block_item"],
    ["gilded_age", "industrialforegoing:marine_fisher", "block_item"],
    ["gilded_age", "industrialforegoing:fluid_sieving_machine", "block_item"],
    ["gilded_age", "industrialforegoing:resourceful_furnace", "block_item"],
    ["gilded_age", "industrialforegoing:enchantment_applicator", "block_item"],
    ["gilded_age", "industrialforegoing:enchantment_extractor", "block_item"],
    ["gilded_age", "industrialforegoing:enchantment_factory", "block_item"],
    ["atomic", "industrialforegoing:infinity_saw", "item"],
    ["atomic", "industrialforegoing:infinity_hammer", "item"],
    ["atomic", "industrialforegoing:infinity_trident", "item"],
    ["industrial_revolution", "ae2:annihilation_plane", "item"],
    ["industrial_revolution", "ae2:formation_plane", "item"],
    ["industrial_revolution", "ae2:import_bus", "item"],
    ["industrial_revolution", "ae2:export_bus", "item"],
    ["industrial_revolution", "ae2:storage_bus", "item"],
    ["industrial_revolution", "ae2:interface", "item"],
    ["industrial_revolution", "ae2:cable_interface", "item"],
    ["industrial_revolution", "ae2:toggle_bus", "item"],
    ["industrial_revolution", "ae2:level_emitter", "item"],
    ["industrial_revolution", "ae2:storage_monitor", "item"],
    ["industrial_revolution", "ae2:conversion_monitor", "item"],
    ["industrial_revolution", "refinedstorage:exporter", "block_item"],
    ["industrial_revolution", "refinedstorage:importer", "block_item"],
    ["industrial_revolution", "refinedstorage:external_storage", "block_item"],
    ["industrial_revolution", "refinedstorage:interface", "block_item"],
    ["industrial_revolution", "refinedstorage:constructor", "block_item"],
    ["industrial_revolution", "refinedstorage:destructor", "block_item"],
    ["gilded_age", "refinedstorage:autocrafter", "block_item"],
    ["gilded_age", "refinedstorage:autocrafter_manager", "block_item"],
    ["industrial_revolution", "refinedstorage:relay", "block_item"],
    ["industrial_revolution", "refinedstorage:disk_interface", "block_item"],
    ["the_renaissance", "create:mechanical_saw", "block_item"],
    ["medieval_times", "create:mechanical_harvester", "block_item"],
    ["medieval_times", "create:mechanical_plough", "block_item"],
    ["the_renaissance", "create:mechanical_arm", "block_item"],
    ["the_renaissance", "create:portable_storage_interface", "block_item"],
    ["industrial_revolution", "create:smart_chute", "block_item"],
    ["industrial_revolution", "create:redstone_link", "block_item"],
    ["atomic", "mekanism:atomic_disassembler", "item"],
    ["atomic", "mekanism:meka_tool", "item"],
    ["atomic", "mekanism:mekasuit_helmet", "item"],
    ["atomic", "mekanism:mekasuit_bodyarmor", "item"],
    ["atomic", "mekanism:mekasuit_pants", "item"],
    ["atomic", "mekanism:mekasuit_boots", "item"],
    ["industrial_revolution", "mekanism:seismic_vibrator", "item"],
    ["atomic", "mekanism:quantum_entangloporter", "block_item"],
    ["industrial_revolution", "mekanism:jetpack", "item"],
    ["industrial_revolution", "mekanism:jetpack_armored", "item"],
    ["industrial_revolution", "ironfurnaces:silver_furnace", "block_item"],
    ["industrial_revolution", "ironfurnaces:gold_furnace", "block_item"],
    ["industrial_revolution", "ironfurnaces:diamond_furnace", "block_item"],
    ["industrial_revolution", "ironfurnaces:emerald_furnace", "block_item"],
    ["gilded_age", "ironfurnaces:obsidian_furnace", "block_item"],
    ["gilded_age", "ironfurnaces:crystal_furnace", "block_item"],
    ["atomic", "ironfurnaces:netherite_furnace", "block_item"],
    ["atomic", "ironfurnaces:million_furnace", "block_item"],
    ["ascension", "ironfurnaces:allthemodium_furnace", "block_item"],
    ["industrial_revolution", "ironfurnaces:augment_factory", "item"],
    ["gilded_age", "ironfurnaces:augment_blasting", "item"],
    ["gilded_age", "ironfurnaces:augment_smoking", "item"],
    ["medieval_times", "supplementaries:cannon", "block_item"],
    ["medieval_times", "supplementaries:cannonball", "item"],
    ["the_renaissance", "supplementaries:bomb", "item"],
    ["the_renaissance", "supplementaries:bomb_blue", "item"],

    // R174: Draconic Additions is Ascension-tier; IDs come from live lang/model evidence.
    ["ascension", "draconicadditions:chaos_crystalizer", "block_item"],
    ["ascension", "draconicadditions:chaos_extractor", "block_item"],
    ["ascension", "draconicadditions:chaos_infuser", "block_item"],
    ["ascension", "draconicadditions:chaos_liquifier", "block_item"],
    ["ascension", "draconicadditions:chaos_container", "item"],
    ["ascension", "draconicadditions:chaos_heart", "item"],
    ["ascension", "draconicadditions:chaotic_necklace", "item"],
    ["ascension", "draconicadditions:draconic_necklace", "item"],
    ["ascension", "draconicadditions:hermal", "item"],
    ["ascension", "draconicadditions:inert_potato_boots", "item"],
    ["ascension", "draconicadditions:inert_potato_chest", "item"],
    ["ascension", "draconicadditions:inert_potato_helm", "item"],
    ["ascension", "draconicadditions:inert_potato_legs", "item"],
    ["ascension", "draconicadditions:infused_potato_boots", "item"],
    ["ascension", "draconicadditions:infused_potato_chest", "item"],
    ["ascension", "draconicadditions:infused_potato_helm", "item"],
    ["ascension", "draconicadditions:infused_potato_legs", "item"],
    ["ascension", "draconicadditions:item_chaos_injector", "item"],
    ["ascension", "draconicadditions:item_chaotic_auto_feed", "item"],
    ["ascension", "draconicadditions:item_semi_stable_chaos", "item"],
    ["ascension", "draconicadditions:item_stable_chaos", "item"],
    ["ascension", "draconicadditions:item_unstable_chaos", "item"],
    ["ascension", "draconicadditions:wyvern_necklace", "item"],

    // astral_dimension - Gilded mod identity after the 2026-05-27 Astral swap. The portal item is
    // already locked above; these are the recipe-ingredient and gear
    // surfaces that should never become an early-tier material substitute.
    // Decorative blocks (jelly glass, marble/stone variants, plants,
    // signs, doors) and mob/food items (spawn eggs, dragon_fruit, etc.)
    // are intentionally NOT locked - their inputs are dimension-gated, and
    // locking them creates JEI noise without progression benefit.

    // Source / identity materials
    ["gilded_age", "astral_dimension:astral_stone", "block_item"],
    ["gilded_age", "astral_dimension:astranite_ingot", "item"],
    ["gilded_age", "astral_dimension:astranite_block", "block_item"],
    ["gilded_age", "astral_dimension:raw_astranite", "item"],
    ["gilded_age", "astral_dimension:raw_astranite_block", "block_item"],
    ["gilded_age", "astral_dimension:lucid_ingot", "item"],
    ["gilded_age", "astral_dimension:lucid_rock", "item"],
    ["gilded_age", "astral_dimension:block_of_lucid", "block_item"],
    ["gilded_age", "astral_dimension:void_shards", "item"],
    ["gilded_age", "astral_dimension:void_gem", "item"],
    ["gilded_age", "astral_dimension:pure_void", "item"],
    ["gilded_age", "astral_dimension:void_charge", "item"],
    ["gilded_age", "astral_dimension:super_void_charge", "item"],
    ["gilded_age", "astral_dimension:void_charge_titan", "item"],
    ["gilded_age", "astral_dimension:burning_shards", "item"],
    ["gilded_age", "astral_dimension:decay_charge", "item"],
    ["gilded_age", "astral_dimension:frost_charge", "item"],

    // Tools / weapons
    ["gilded_age", "astral_dimension:astral_sword", "item"],
    ["gilded_age", "astral_dimension:astranite_sword", "item"],
    ["gilded_age", "astral_dimension:astranite_pickaxe", "item"],
    ["gilded_age", "astral_dimension:astranite_axe", "item"],
    ["gilded_age", "astral_dimension:astranite_shovel", "item"],
    ["gilded_age", "astral_dimension:astranite_hoe", "item"],
    ["gilded_age", "astral_dimension:lucid_sword", "item"],
    ["gilded_age", "astral_dimension:lucid_pickaxe", "item"],
    ["gilded_age", "astral_dimension:lucid_axe", "item"],
    ["gilded_age", "astral_dimension:lucid_shovel", "item"],
    ["gilded_age", "astral_dimension:lucid_hoe", "item"],

    // Armor sets
    ["gilded_age", "astral_dimension:astranite_armor_helmet", "item"],
    ["gilded_age", "astral_dimension:astranite_armor_chestplate", "item"],
    ["gilded_age", "astral_dimension:astranite_armor_leggings", "item"],
    ["gilded_age", "astral_dimension:astranite_armor_boots", "item"],
    ["gilded_age", "astral_dimension:lucid_armor_helmet", "item"],
    ["gilded_age", "astral_dimension:lucid_armor_chestplate", "item"],
    ["gilded_age", "astral_dimension:lucid_armor_leggings", "item"],
    ["gilded_age", "astral_dimension:lucid_armor_boots", "item"],
    ["gilded_age", "astral_dimension:harsh_leather_armor_helmet", "item"],
    ["gilded_age", "astral_dimension:harsh_leather_armor_chestplate", "item"],
    ["gilded_age", "astral_dimension:harsh_leather_armor_leggings", "item"],
    ["gilded_age", "astral_dimension:harsh_leather_armor_boots", "item"],
    ["gilded_age", "astral_dimension:tormented_helmet", "item"],
    ["gilded_age", "astral_dimension:tormented_chestplate", "item"],
    ["gilded_age", "astral_dimension:tormented_leggings", "item"],
    ["gilded_age", "astral_dimension:tormented_boots", "item"],
    ["gilded_age", "astral_dimension:pajama_helmet", "item"],
    ["gilded_age", "astral_dimension:pajama_chestplate", "item"],
    ["gilded_age", "astral_dimension:pajama_leggings", "item"],
    ["gilded_age", "astral_dimension:pajama_boots", "item"],
    ["gilded_age", "astral_dimension:supreme_helmet", "item"],

    // Mobility / accessory gear
    ["gilded_age", "astral_dimension:magma_wings_chestplate", "item"],
    ["gilded_age", "astral_dimension:bouncy_boots", "item"],
    ["gilded_age", "astral_dimension:void_necklace_chestplate", "item"],
    ["gilded_age", "astral_dimension:amethyst_necklace_chestplate", "item"],
    ["gilded_age", "astral_dimension:void_boots_helmet", "item"],

    // Boss proofs / smithing templates / reward + altar blocks
    ["gilded_age", "astral_dimension:void_eater", "item"],
    ["gilded_age", "astral_dimension:upgraded_void_eater", "item"],
    ["gilded_age", "astral_dimension:void_fang", "item"],
    ["gilded_age", "astral_dimension:lucid_upgrade_smithing_template", "item"],
    ["gilded_age", "astral_dimension:void_eater_upgrade_smithing_template", "item"],
    ["gilded_age", "astral_dimension:sword_upgrade_smithing_template", "item"],
    ["gilded_age", "astral_dimension:titan_helmet_upgrade_template", "item"],
    ["gilded_age", "astral_dimension:astral_reward", "block_item"],
    ["gilded_age", "astral_dimension:astral_altar", "block_item"],

    // R5 hardening: class-stack village, End/Nether loot, fishing,
    // and early circuit surfaces that can otherwise leak before their
    // authored chapters.
    ["medieval_times", "archers:flint_spear", "item"],
    ["medieval_times", "archers:composite_longbow", "item"],
    ["medieval_times", "rogues:flint_dagger", "item"],
    ["medieval_times", "paladins:acolyte_wand", "item"],
    ["medieval_times", "wizards:wand_novice", "item"],
    ["medieval_times", "archers:archer_armor_head", "item"],
    ["medieval_times", "archers:archer_armor_chest", "item"],
    ["medieval_times", "archers:archer_armor_legs", "item"],
    ["medieval_times", "archers:archer_armor_feet", "item"],
    ["medieval_times", "paladins:paladin_armor_head", "item"],
    ["medieval_times", "paladins:paladin_armor_chest", "item"],
    ["medieval_times", "paladins:paladin_armor_legs", "item"],
    ["medieval_times", "paladins:paladin_armor_feet", "item"],
    ["medieval_times", "paladins:priest_robe_head", "item"],
    ["medieval_times", "paladins:priest_robe_chest", "item"],
    ["medieval_times", "paladins:priest_robe_legs", "item"],
    ["medieval_times", "paladins:priest_robe_feet", "item"],
    ["medieval_times", "rogues:iron_dagger", "item"],
    ["medieval_times", "rogues:iron_double_axe", "item"],
    ["medieval_times", "rogues:iron_glaive", "item"],
    ["medieval_times", "rogues:iron_sickle", "item"],
    ["medieval_times", "rogues:rogue_armor_head", "item"],
    ["medieval_times", "rogues:rogue_armor_chest", "item"],
    ["medieval_times", "rogues:rogue_armor_legs", "item"],
    ["medieval_times", "rogues:rogue_armor_feet", "item"],
    ["medieval_times", "rogues:warrior_armor_head", "item"],
    ["medieval_times", "rogues:warrior_armor_chest", "item"],
    ["medieval_times", "rogues:warrior_armor_legs", "item"],
    ["medieval_times", "rogues:warrior_armor_feet", "item"],
    ["medieval_times", "wizards:staff_wizard", "item"],
    ["medieval_times", "wizards:wizard_robe_head", "item"],
    ["medieval_times", "wizards:wizard_robe_chest", "item"],
    ["medieval_times", "wizards:wizard_robe_legs", "item"],
    ["medieval_times", "wizards:wizard_robe_feet", "item"],
    ["medieval_times", "jewelry:copper_ring", "item"],
    ["medieval_times", "jewelry:iron_ring", "item"],
    ["medieval_times", "jewelry:gold_ring", "item"],
    ["medieval_times", "jewelry:emerald_necklace", "item"],
    ["medieval_times", "runes:arcane_stone", "item"],
    ["medieval_times", "runes:fire_stone", "item"],
    ["medieval_times", "runes:frost_stone", "item"],
    ["medieval_times", "runes:healing_stone", "item"],
    ["medieval_times", "runes:lightning_stone", "item"],
    ["medieval_times", "runes:soul_stone", "item"],
    ["medieval_times", "runes:small_rune_pouch", "item"],
    ["medieval_times", "runes:medium_rune_pouch", "item"],
    ["medieval_times", "runes:large_rune_pouch", "item"],
    ["medieval_times", "runes:crafting_altar", "block_item"],
    ["medieval_times", "spell_engine:spell_binding", "block_item"],
    ["medieval_times", "spell_engine:spell_book", "item"],
    ["medieval_times", "spell_engine:spell_scroll", "item"],
    ["medieval_times", "spell_engine:scroll_default", "item"],
    ["medieval_times", "skill_tree_rpgs:orb_of_oblivion", "item"],
    ["the_renaissance", "armory_rpgs:epic_armor_upgrade", "item"],
    ["the_renaissance", "armory_rpgs:champion_upgrade_crystal", "item"],
    ["the_renaissance", "armory_rpgs:conqueror_upgrade_crystal", "item"],
    ["the_renaissance", "armory_rpgs:redeemer_upgrade_crystal", "item"],
    ["the_renaissance", "armory_rpgs:vanquisher_upgrade_crystal", "item"],
    ["the_renaissance", "armory_rpgs:astral_robe_head", "item"],
    ["the_renaissance", "armory_rpgs:astral_robe_chest", "item"],
    ["the_renaissance", "armory_rpgs:astral_robe_legs", "item"],
    ["the_renaissance", "armory_rpgs:astral_robe_feet", "item"],
    ["the_renaissance", "armory_rpgs:avatar_robe_head", "item"],
    ["the_renaissance", "armory_rpgs:avatar_robe_chest", "item"],
    ["the_renaissance", "armory_rpgs:avatar_robe_legs", "item"],
    ["the_renaissance", "armory_rpgs:avatar_robe_feet", "item"],
    ["the_renaissance", "armory_rpgs:deathmantle_armor_head", "item"],
    ["the_renaissance", "armory_rpgs:deathmantle_armor_chest", "item"],
    ["the_renaissance", "armory_rpgs:deathmantle_armor_legs", "item"],
    ["the_renaissance", "armory_rpgs:deathmantle_armor_feet", "item"],
    ["the_renaissance", "armory_rpgs:destroyer_armor_head", "item"],
    ["the_renaissance", "armory_rpgs:destroyer_armor_chest", "item"],
    ["the_renaissance", "armory_rpgs:destroyer_armor_legs", "item"],
    ["the_renaissance", "armory_rpgs:destroyer_armor_feet", "item"],
    ["the_renaissance", "armory_rpgs:glacier_robe_head", "item"],
    ["the_renaissance", "armory_rpgs:glacier_robe_chest", "item"],
    ["the_renaissance", "armory_rpgs:glacier_robe_legs", "item"],
    ["the_renaissance", "armory_rpgs:glacier_robe_feet", "item"],
    ["the_renaissance", "armory_rpgs:justicar_armor_head", "item"],
    ["the_renaissance", "armory_rpgs:justicar_armor_chest", "item"],
    ["the_renaissance", "armory_rpgs:justicar_armor_legs", "item"],
    ["the_renaissance", "armory_rpgs:justicar_armor_feet", "item"],
    ["the_renaissance", "armory_rpgs:scarlet_robe_head", "item"],
    ["the_renaissance", "armory_rpgs:scarlet_robe_chest", "item"],
    ["the_renaissance", "armory_rpgs:scarlet_robe_legs", "item"],
    ["the_renaissance", "armory_rpgs:scarlet_robe_feet", "item"],
    ["the_renaissance", "armory_rpgs:strider_armor_head", "item"],
    ["the_renaissance", "armory_rpgs:strider_armor_chest", "item"],
    ["the_renaissance", "armory_rpgs:strider_armor_legs", "item"],
    ["the_renaissance", "armory_rpgs:strider_armor_feet", "item"],

    ["gilded_age", "unusualend:void_totem", "item"],
    ["industrial_revolution", "unusualend:pearlescent_ingot", "item"],
    ["industrial_revolution", "unusualend:pearlescent_block", "block_item"],
    // All five pearlescent tools are smithing-transform-only (jar pearl_*.json:
    // template + diamond tool + ingot) and the template is otherworldly (below),
    // so the tools retier with it (2026-08-06; tool quests moved to ow6 same day).
    ["otherworldly", "unusualend:pearlescent_axe", "item"],
    ["otherworldly", "unusualend:pearlescent_hoe", "item"],
    ["otherworldly", "unusualend:pearlescent_pickaxe", "item"],
    ["otherworldly", "unusualend:pearlescent_shovel", "item"],
    ["otherworldly", "unusualend:pearlescent_sword", "item"],
    ["industrial_revolution", "unusualend:pearlescent_ring", "item"],
    ["industrial_revolution", "unusualend:pearlescent_infuser", "block_item"],
    ["industrial_revolution", "unusualend:prismatic_mirror", "item"],
    ["otherworldly", "unusualend:pearlescent_upgrade_smithing_template", "item"],
    ["otherworldly", "unusualend:ancient_armor_trim_smithing_template", "item"],
    ["industrial_revolution", "netherex:netherite_horse_armor", "item"],

    // AoA Celestial Survey proof-mod bypass hardening (2026-06-01):
    // observation opens at Renaissance; ship and orbital mission surfaces wait for Otherworldly.
    ["the_renaissance", "aoa_celestial_survey:light_reader", "item"],
    ["the_renaissance", "aoa_celestial_survey:starlight_prism", "item"],
    ["the_renaissance", "aoa_celestial_survey:observatory", "block_item"],
    ["the_renaissance", "aoa_celestial_survey:starlight_sample", "item"],
    ["the_renaissance", "aoa_celestial_survey:starlight_analysis", "item"],
    ["the_renaissance", "aoa_celestial_survey:verified_starlight_reading", "item"],
    ["the_renaissance", "aoa_celestial_survey:lunar_survey_notes", "item"],
    ["the_renaissance", "aoa_celestial_survey:twin_sighting_marker", "block_item"],
    ["the_renaissance", "aoa_celestial_survey:twin_sighting_log", "item"],
    ["otherworldly", "aoa_celestial_survey:mission_console", "block_item"],
    ["otherworldly", "aoa_celestial_survey:astrocartography_console", "block_item"],
    ["otherworldly", "aoa_celestial_survey:verified_lunar_survey", "item"],
    ["otherworldly", "aoa_celestial_survey:first_orbital_manifest", "item"],
    ["otherworldly", "aoa_celestial_survey:moon_dust_sample", "item"],
    ["otherworldly", "aoa_celestial_survey:space_hull", "block_item"],
    ["otherworldly", "aoa_celestial_survey:plated_hull", "block_item"],
    ["otherworldly", "aoa_celestial_survey:reinforced_hull", "block_item"],
    ["otherworldly", "aoa_celestial_survey:hull_window", "block_item"],
    ["otherworldly", "aoa_celestial_survey:sealed_ceiling", "block_item"],
    ["otherworldly", "aoa_celestial_survey:sealed_floor", "block_item"],
    ["otherworldly", "aoa_celestial_survey:cargo_container", "block_item"],
    ["otherworldly", "aoa_celestial_survey:capacitor_bank", "block_item"],
    ["otherworldly", "aoa_celestial_survey:reactor_core", "block_item"],
    ["otherworldly", "aoa_celestial_survey:energy_conduit", "block_item"],
    ["otherworldly", "aoa_celestial_survey:ship_light_strip_amber", "block_item"],
    ["otherworldly", "aoa_celestial_survey:ship_light_strip_blue", "block_item"],
    ["otherworldly", "aoa_celestial_survey:ship_light_strip_cyan", "block_item"],
    ["otherworldly", "aoa_celestial_survey:ship_light_strip_green", "block_item"],
    ["otherworldly", "aoa_celestial_survey:ship_light_strip_light_blue", "block_item"],
    ["otherworldly", "aoa_celestial_survey:ship_light_strip_lime", "block_item"],
    ["otherworldly", "aoa_celestial_survey:ship_light_strip_red", "block_item"],
    ["otherworldly", "aoa_celestial_survey:ship_light_strip_white", "block_item"],
    ["otherworldly", "aoa_celestial_survey:ship_light_strip_yellow", "block_item"],
    ["ascension", "aoa_celestial_survey:test_proof", "item"],

    ["industrial_revolution", "aquaculture:neptunes_bounty", "block_item"],
    ["industrial_revolution", "aquaculture:neptunium_ingot", "item"],
    ["industrial_revolution", "aquaculture:neptunium_nugget", "item"],
    ["industrial_revolution", "aquaculture:neptunium_block", "block_item"],
    ["industrial_revolution", "aquaculture:neptunium_pickaxe", "item"],
    ["industrial_revolution", "aquaculture:neptunium_sword", "item"],
    ["industrial_revolution", "aquaculture:neptunium_shovel", "item"],
    ["industrial_revolution", "aquaculture:neptunium_axe", "item"],
    ["industrial_revolution", "aquaculture:neptunium_hoe", "item"],
    ["industrial_revolution", "aquaculture:neptunium_helmet", "item"],
    ["industrial_revolution", "aquaculture:neptunium_chestplate", "item"],
    ["industrial_revolution", "aquaculture:neptunium_leggings", "item"],
    ["industrial_revolution", "aquaculture:neptunium_boots", "item"],
    ["industrial_revolution", "aquaculture:neptunium_fishing_rod", "item"],
    ["industrial_revolution", "aquaculture:neptunium_bow", "item"],
    ["industrial_revolution", "aquaculture:neptunium_fillet_knife", "item"],

    ["industrial_revolution", "projectred_core:silicon", "item"],
    ["industrial_revolution", "projectred_core:silicon_chip", "item"],
    ["industrial_revolution", "projectred_core:infused_silicon", "item"],
    ["industrial_revolution", "projectred_core:energized_silicon", "item"],
    ["industrial_revolution", "projectred_core:energized_silicon_chip", "item"],
    ["industrial_revolution", "projectred_core:electrotine_dust", "item"],
    ["industrial_revolution", "projectred_core:electrotine_ingot", "item"],
  ]

  const tagLocks = [
    ["ascension", "c:ingots/draconium_awakened", "item_tag"],
    ["atomic", "c:circuits/elite", "item_tag"],
    ["atomic", "c:circuits/ultimate", "item_tag"],
    ["atomic", "c:dusts/fissile", "item_tag"],
    ["atomic", "c:dusts/plutonium", "item_tag"],
    ["atomic", "c:dusts/thorium", "item_tag"],
    ["atomic", "c:dusts/uranium", "item_tag"],
    ["atomic", "c:fuel_rods/heuo2", "item_tag"],
    ["atomic", "c:fuel_rods/leuo2", "item_tag"],
    ["atomic", "c:fuel_rods/plutonium", "item_tag"],
    ["atomic", "c:fuel_rods/spent", "item_tag"],
    ["atomic", "c:ingots/uranium", "item_tag"],
    ["atomic", "c:nuggets/uranium", "item_tag"],
    ["atomic", "c:ores/thorium", "item_tag"],
    ["atomic", "c:ores/uranium", "item_tag"],
    ["atomic", "c:oxide/plutonium", "item_tag"],
    ["atomic", "c:oxides/plutonium", "item_tag"],
    ["atomic", "c:pellets/plutonium", "item_tag"],
    ["atomic", "c:pellets/uranium235", "item_tag"],
    ["atomic", "c:pellets/uranium238", "item_tag"],
    ["atomic", "c:plates/uranium", "item_tag"],
    ["atomic", "c:raw_materials/thorium", "item_tag"],
    ["atomic", "c:raw_materials/uranium", "item_tag"],
    ["atomic", "c:salts/fissile", "item_tag"],
    ["atomic", "c:storage_blocks/raw_thorium", "item_tag"],
    ["atomic", "c:storage_blocks/raw_uranium", "item_tag"],
    ["atomic", "c:storage_blocks/thorium", "item_tag"],
    ["atomic", "c:storage_blocks/uranium", "item_tag"],
    ["atomic", "c:yellow_cake_uranium", "item_tag"],
    ["gilded_age", "refinedstorage:autocrafters", "item_tag"],
    ["gilded_age", "refinedstorage:autocrafter_managers", "item_tag"],
    ["atomic", "refinedstorage:autocrafting_monitors", "item_tag"],
    ["gilded_age", "refinedstorage:pattern_grids", "item_tag"],
    ["atomic", "refinedstorage:wireless_transmitters", "item_tag"],
    ["atomic", "c:ores/thorium", "block_tag"],
    ["atomic", "c:ores/uranium", "block_tag"],
    ["atomic", "c:storage_blocks/raw_thorium", "block_tag"],
    ["atomic", "c:storage_blocks/raw_uranium", "block_tag"],
    ["atomic", "c:storage_blocks/thorium", "block_tag"],
    ["atomic", "c:storage_blocks/uranium", "block_tag"],
    ["otherworldly", "refinedstorage:network_transmitters", "item_tag"],
    ["otherworldly", "refinedstorage:network_receivers", "item_tag"],
    ["otherworldly", "interdimensionalwirelesstransmitter:interdimensional_wireless_transmitters", "item_tag"],
  ]

  itemLocks.forEach(function (entry) { softItemLock(entry[0], entry[1], entry[2]) })
  tagLocks.forEach(function (entry) { softTagLock(entry[0], entry[1], entry[2]) })
})()
