// AoA KubeJS: aoa_loot_table_overrides.js
// High-priority data overrides for stale or phantom loot tables found in live logs.
// This silences broken loot tables without registering fake placeholder items.

const AOA_EMPTY_BLOCK_LOOT_TABLE_IDS = [
  'create_integrated_farming:blocks/duck_roost_campbell',
  'create_integrated_farming:blocks/duck_roost_female',
  'create_integrated_farming:blocks/duck_roost_normal',
  'create_integrated_farming:blocks/duck_roost_pekin',
  'create_integrated_farming:blocks/goose_roost_canadian',
  'create_integrated_farming:blocks/goose_roost_greylag',
  'create_integrated_farming:blocks/goose_roost_normal',
  'create_integrated_farming:blocks/goose_roost_ping',
  'create_integrated_farming:blocks/goose_roost_sus',
  'create_integrated_farming:blocks/goose_roost_untitled',
  'extendedae:blocks/ex_emc_interface',
  'generatorgalore:blocks/copper_generator_64x',
  'generatorgalore:blocks/diamond_generator_64x',
  'generatorgalore:blocks/emerald_generator_64x',
  'generatorgalore:blocks/gold_generator_64x',
  'generatorgalore:blocks/iron_generator_64x',
  'generatorgalore:blocks/obsidian_generator_64x',
  'railways:blocks/track_biomesoplenty_dead',
  'railways:blocks/track_biomesoplenty_dead_narrow',
  'railways:blocks/track_biomesoplenty_dead_wide',
  'railways:blocks/track_biomesoplenty_fir',
  'railways:blocks/track_biomesoplenty_fir_narrow',
  'railways:blocks/track_biomesoplenty_fir_wide',
  'railways:blocks/track_biomesoplenty_hellbark',
  'railways:blocks/track_biomesoplenty_hellbark_narrow',
  'railways:blocks/track_biomesoplenty_hellbark_wide',
  'railways:blocks/track_biomesoplenty_jacaranda',
  'railways:blocks/track_biomesoplenty_jacaranda_narrow',
  'railways:blocks/track_biomesoplenty_jacaranda_wide',
  'railways:blocks/track_biomesoplenty_magic',
  'railways:blocks/track_biomesoplenty_magic_narrow',
  'railways:blocks/track_biomesoplenty_magic_wide',
  'railways:blocks/track_biomesoplenty_mahogany',
  'railways:blocks/track_biomesoplenty_mahogany_narrow',
  'railways:blocks/track_biomesoplenty_mahogany_wide',
  'railways:blocks/track_biomesoplenty_palm',
  'railways:blocks/track_biomesoplenty_palm_narrow',
  'railways:blocks/track_biomesoplenty_palm_wide',
  'railways:blocks/track_biomesoplenty_redwood',
  'railways:blocks/track_biomesoplenty_redwood_narrow',
  'railways:blocks/track_biomesoplenty_redwood_wide',
  'railways:blocks/track_biomesoplenty_umbran',
  'railways:blocks/track_biomesoplenty_umbran_narrow',
  'railways:blocks/track_biomesoplenty_umbran_wide',
  'railways:blocks/track_biomesoplenty_willow',
  'railways:blocks/track_biomesoplenty_willow_narrow',
  'railways:blocks/track_biomesoplenty_willow_wide',
  'railways:blocks/track_blue_skies_bluebright',
  'railways:blocks/track_blue_skies_bluebright_narrow',
  'railways:blocks/track_blue_skies_bluebright_wide',
  'railways:blocks/track_blue_skies_dusk',
  'railways:blocks/track_blue_skies_dusk_narrow',
  'railways:blocks/track_blue_skies_dusk_wide',
  'railways:blocks/track_blue_skies_frostbright',
  'railways:blocks/track_blue_skies_frostbright_narrow',
  'railways:blocks/track_blue_skies_frostbright_wide',
  'railways:blocks/track_blue_skies_lunar',
  'railways:blocks/track_blue_skies_lunar_narrow',
  'railways:blocks/track_blue_skies_lunar_wide',
  'railways:blocks/track_blue_skies_maple',
  'railways:blocks/track_blue_skies_maple_narrow',
  'railways:blocks/track_blue_skies_maple_wide',
  'railways:blocks/track_blue_skies_starlit',
  'railways:blocks/track_blue_skies_starlit_narrow',
  'railways:blocks/track_blue_skies_starlit_wide',
  'railways:blocks/track_byg_aspen',
  'railways:blocks/track_byg_aspen_narrow',
  'railways:blocks/track_byg_aspen_wide',
  'railways:blocks/track_byg_baobab',
  'railways:blocks/track_byg_baobab_narrow',
  'railways:blocks/track_byg_baobab_wide',
  'railways:blocks/track_byg_blue_enchanted',
  'railways:blocks/track_byg_blue_enchanted_narrow',
  'railways:blocks/track_byg_blue_enchanted_wide',
  'railways:blocks/track_byg_bulbis',
  'railways:blocks/track_byg_bulbis_narrow',
  'railways:blocks/track_byg_bulbis_wide',
  'railways:blocks/track_byg_cika',
  'railways:blocks/track_byg_cika_narrow',
  'railways:blocks/track_byg_cika_wide',
  'railways:blocks/track_byg_cypress',
  'railways:blocks/track_byg_cypress_narrow',
  'railways:blocks/track_byg_cypress_wide',
  'railways:blocks/track_byg_ebony',
  'railways:blocks/track_byg_ebony_narrow',
  'railways:blocks/track_byg_ebony_wide',
  'railways:blocks/track_byg_embur',
  'railways:blocks/track_byg_embur_narrow',
  'railways:blocks/track_byg_embur_wide',
  'railways:blocks/track_byg_ether',
  'railways:blocks/track_byg_ether_narrow',
  'railways:blocks/track_byg_ether_wide',
  'railways:blocks/track_byg_fir',
  'railways:blocks/track_byg_fir_narrow',
  'railways:blocks/track_byg_fir_wide',
  'railways:blocks/track_byg_green_enchanted',
  'railways:blocks/track_byg_green_enchanted_narrow',
  'railways:blocks/track_byg_green_enchanted_wide',
  'railways:blocks/track_byg_holly',
  'railways:blocks/track_byg_holly_narrow',
  'railways:blocks/track_byg_holly_wide',
  'railways:blocks/track_byg_imparius',
  'railways:blocks/track_byg_imparius_narrow',
  'railways:blocks/track_byg_imparius_wide',
  'railways:blocks/track_byg_jacaranda',
  'railways:blocks/track_byg_jacaranda_narrow',
  'railways:blocks/track_byg_jacaranda_wide',
  'railways:blocks/track_byg_lament',
  'railways:blocks/track_byg_lament_narrow',
  'railways:blocks/track_byg_lament_wide',
  'railways:blocks/track_byg_mahogany',
  'railways:blocks/track_byg_mahogany_narrow',
  'railways:blocks/track_byg_mahogany_wide',
  'railways:blocks/track_byg_maple',
  'railways:blocks/track_byg_maple_narrow',
  'railways:blocks/track_byg_maple_wide',
  'railways:blocks/track_byg_nightshade',
  'railways:blocks/track_byg_nightshade_narrow',
  'railways:blocks/track_byg_nightshade_wide',
  'railways:blocks/track_byg_palm',
  'railways:blocks/track_byg_palm_narrow',
  'railways:blocks/track_byg_palm_wide',
  'railways:blocks/track_byg_pine',
  'railways:blocks/track_byg_pine_narrow',
  'railways:blocks/track_byg_pine_wide',
  'railways:blocks/track_byg_rainbow_eucalyptus',
  'railways:blocks/track_byg_rainbow_eucalyptus_narrow',
  'railways:blocks/track_byg_rainbow_eucalyptus_wide',
  'railways:blocks/track_byg_redwood',
  'railways:blocks/track_byg_redwood_narrow',
  'railways:blocks/track_byg_redwood_wide',
  'railways:blocks/track_byg_skyris',
  'railways:blocks/track_byg_skyris_narrow',
  'railways:blocks/track_byg_skyris_wide',
  'railways:blocks/track_byg_sythian',
  'railways:blocks/track_byg_sythian_narrow',
  'railways:blocks/track_byg_sythian_wide',
  'railways:blocks/track_byg_white_mangrove',
  'railways:blocks/track_byg_white_mangrove_narrow',
  'railways:blocks/track_byg_white_mangrove_wide',
  'railways:blocks/track_byg_willow',
  'railways:blocks/track_byg_willow_narrow',
  'railways:blocks/track_byg_willow_wide',
  'railways:blocks/track_byg_witch_hazel',
  'railways:blocks/track_byg_witch_hazel_narrow',
  'railways:blocks/track_byg_witch_hazel_wide',
  'railways:blocks/track_byg_zelkova',
  'railways:blocks/track_byg_zelkova_narrow',
  'railways:blocks/track_byg_zelkova_wide',
  'railways:blocks/track_create_dd_rose',
  'railways:blocks/track_create_dd_rose_narrow',
  'railways:blocks/track_create_dd_rose_wide',
  'railways:blocks/track_create_dd_rubber',
  'railways:blocks/track_create_dd_rubber_narrow',
  'railways:blocks/track_create_dd_rubber_wide',
  'railways:blocks/track_create_dd_smoked',
  'railways:blocks/track_create_dd_smoked_narrow',
  'railways:blocks/track_create_dd_smoked_wide',
  'railways:blocks/track_create_dd_spirit',
  'railways:blocks/track_create_dd_spirit_narrow',
  'railways:blocks/track_create_dd_spirit_wide',
  'railways:blocks/track_hexcasting_edified',
  'railways:blocks/track_hexcasting_edified_narrow',
  'railways:blocks/track_hexcasting_edified_wide',
  'railways:blocks/track_natures_spirit_aspen',
  'railways:blocks/track_natures_spirit_aspen_narrow',
  'railways:blocks/track_natures_spirit_aspen_wide',
  'railways:blocks/track_natures_spirit_cypress',
  'railways:blocks/track_natures_spirit_cypress_narrow',
  'railways:blocks/track_natures_spirit_cypress_wide',
  'railways:blocks/track_natures_spirit_fir',
  'railways:blocks/track_natures_spirit_fir_narrow',
  'railways:blocks/track_natures_spirit_fir_wide',
  'railways:blocks/track_natures_spirit_ghaf',
  'railways:blocks/track_natures_spirit_ghaf_narrow',
  'railways:blocks/track_natures_spirit_ghaf_wide',
  'railways:blocks/track_natures_spirit_joshua',
  'railways:blocks/track_natures_spirit_joshua_narrow',
  'railways:blocks/track_natures_spirit_joshua_wide',
  'railways:blocks/track_natures_spirit_maple',
  'railways:blocks/track_natures_spirit_maple_narrow',
  'railways:blocks/track_natures_spirit_maple_wide',
  'railways:blocks/track_natures_spirit_olive',
  'railways:blocks/track_natures_spirit_olive_narrow',
  'railways:blocks/track_natures_spirit_olive_wide',
  'railways:blocks/track_natures_spirit_palo_verde',
  'railways:blocks/track_natures_spirit_palo_verde_narrow',
  'railways:blocks/track_natures_spirit_palo_verde_wide',
  'railways:blocks/track_natures_spirit_redwood',
  'railways:blocks/track_natures_spirit_redwood_narrow',
  'railways:blocks/track_natures_spirit_redwood_wide',
  'railways:blocks/track_natures_spirit_sugi',
  'railways:blocks/track_natures_spirit_sugi_narrow',
  'railways:blocks/track_natures_spirit_sugi_wide',
  'railways:blocks/track_natures_spirit_willow',
  'railways:blocks/track_natures_spirit_willow_narrow',
  'railways:blocks/track_natures_spirit_willow_wide',
  'railways:blocks/track_natures_spirit_wisteria',
  'railways:blocks/track_natures_spirit_wisteria_narrow',
  'railways:blocks/track_natures_spirit_wisteria_wide',
  'railways:blocks/track_tfc_acacia',
  'railways:blocks/track_tfc_acacia_narrow',
  'railways:blocks/track_tfc_acacia_wide',
  'railways:blocks/track_tfc_ash',
  'railways:blocks/track_tfc_ash_narrow',
  'railways:blocks/track_tfc_ash_wide',
  'railways:blocks/track_tfc_aspen',
  'railways:blocks/track_tfc_aspen_narrow',
  'railways:blocks/track_tfc_aspen_wide',
  'railways:blocks/track_tfc_birch',
  'railways:blocks/track_tfc_birch_narrow',
  'railways:blocks/track_tfc_birch_wide',
  'railways:blocks/track_tfc_blackwood',
  'railways:blocks/track_tfc_blackwood_narrow',
  'railways:blocks/track_tfc_blackwood_wide',
  'railways:blocks/track_tfc_chestnut',
  'railways:blocks/track_tfc_chestnut_narrow',
  'railways:blocks/track_tfc_chestnut_wide',
  'railways:blocks/track_tfc_douglas_fir',
  'railways:blocks/track_tfc_douglas_fir_narrow',
  'railways:blocks/track_tfc_douglas_fir_wide',
  'railways:blocks/track_tfc_hickory',
  'railways:blocks/track_tfc_hickory_narrow',
  'railways:blocks/track_tfc_hickory_wide',
  'railways:blocks/track_tfc_kapok',
  'railways:blocks/track_tfc_kapok_narrow',
  'railways:blocks/track_tfc_kapok_wide',
  'railways:blocks/track_tfc_mangrove',
  'railways:blocks/track_tfc_mangrove_narrow',
  'railways:blocks/track_tfc_mangrove_wide',
  'railways:blocks/track_tfc_maple',
  'railways:blocks/track_tfc_maple_narrow',
  'railways:blocks/track_tfc_maple_wide',
  'railways:blocks/track_tfc_oak',
  'railways:blocks/track_tfc_oak_narrow',
  'railways:blocks/track_tfc_oak_wide',
  'railways:blocks/track_tfc_palm',
  'railways:blocks/track_tfc_palm_narrow',
  'railways:blocks/track_tfc_palm_wide',
  'railways:blocks/track_tfc_pine',
  'railways:blocks/track_tfc_pine_narrow',
  'railways:blocks/track_tfc_pine_wide',
  'railways:blocks/track_tfc_rosewood',
  'railways:blocks/track_tfc_rosewood_narrow',
  'railways:blocks/track_tfc_rosewood_wide',
  'railways:blocks/track_tfc_sequoia',
  'railways:blocks/track_tfc_sequoia_narrow',
  'railways:blocks/track_tfc_sequoia_wide',
  'railways:blocks/track_tfc_spruce',
  'railways:blocks/track_tfc_spruce_narrow',
  'railways:blocks/track_tfc_spruce_wide',
  'railways:blocks/track_tfc_sycamore',
  'railways:blocks/track_tfc_sycamore_narrow',
  'railways:blocks/track_tfc_sycamore_wide',
  'railways:blocks/track_tfc_white_cedar',
  'railways:blocks/track_tfc_white_cedar_narrow',
  'railways:blocks/track_tfc_white_cedar_wide',
  'railways:blocks/track_tfc_willow',
  'railways:blocks/track_tfc_willow_narrow',
  'railways:blocks/track_tfc_willow_wide',
]

function aoaEmptyBlockLootTable() {
  return {
    type: 'minecraft:block',
    pools: []
  }
}

function aoaNautecCrateLootTable() {
  return {
    type: 'minecraft:block',
    pools: [{
      bonus_rolls: 0.0,
      entries: [{
        type: 'minecraft:item',
        functions: [{
          function: 'minecraft:copy_components',
          include: [
            'minecraft:custom_name',
            'minecraft:container',
            'minecraft:lock',
            'minecraft:container_loot'
          ],
          source: 'block_entity'
        }],
        name: 'nautec:crate'
      }],
      rolls: 1.0
    }],
    random_sequence: 'nautec:blocks/crate'
  }
}

function aoaNautecRustyCrateLootTable() {
  return {
    type: 'minecraft:chest',
    pools: [{
      rolls: { min: 2, max: 5 },
      entries: [
        {
          type: 'minecraft:item',
          name: 'minecraft:gold_nugget',
          weight: 5,
          functions: [{ function: 'minecraft:set_count', count: { min: 2, max: 5 } }]
        },
        {
          type: 'minecraft:item',
          name: 'minecraft:prismarine_shard',
          weight: 5,
          functions: [{ function: 'minecraft:set_count', count: { min: 1, max: 3 } }]
        },
        {
          type: 'minecraft:item',
          name: 'minecraft:prismarine_crystals',
          weight: 5,
          functions: [{ function: 'minecraft:set_count', count: { min: 1, max: 3 } }]
        },
        {
          type: 'minecraft:item',
          name: 'minecraft:prismarine_shard',
          weight: 2,
          functions: [{ function: 'minecraft:set_count', count: { min: 1, max: 3 } }]
        },
        {
          type: 'minecraft:item',
          name: 'minecraft:iron_nugget',
          weight: 2,
          functions: [{ function: 'minecraft:set_count', count: { min: 1, max: 3 } }]
        },
        {
          type: 'minecraft:item',
          name: 'minecraft:gold_nugget',
          weight: 1,
          functions: [{ function: 'minecraft:set_count', count: { min: 1, max: 2 } }]
        }
      ]
    }]
  }
}

ServerEvents.generateData('after_mods', event => {
  AOA_EMPTY_BLOCK_LOOT_TABLE_IDS.forEach(id => {
    const parts = id.split(':')
    event.json(parts[0] + ':loot_table/' + parts[1], aoaEmptyBlockLootTable())
  })

  event.json('nautec:loot_table/blocks/crate', aoaNautecCrateLootTable())
  event.json('nautec:loot_table/chests/ruins_rusty_crate', aoaNautecRustyCrateLootTable())
})
