// AoA KubeJS: aoa_astages_01p_gap_closure.js
// Focused closure pass for live bypasses surfaced by the 2026-05-30/31
// staging and gear audits. This file intentionally holds small, evidenced
// mod-family lock sets that were not yet covered by the main machine waves.

;(function () {
  if (typeof AStages === 'undefined') return

  function applySoftItemPolicy(r) {
    // AStages 2.5 defaults keep locked entries hidden in EMI and conceal their names.
    return r.allowInventoryStorage().allowContainerStorage().allowPickup().disableBlockInteraction()
  }

  function softItemLock(stage, item, kind) {
    if (typeof Item !== 'undefined' && typeof Item.exists === 'function' && !Item.exists(item)) {
      console.warn('[AoA AStages gap closure] Skipped missing item ' + item + ' (stage=' + stage + ')')
      return
    }
    var id = 'aoa/item/' + kind + '/' + stage + '/' + item.replace(/[^a-zA-Z0-9_]/g, '_')
    try {
      applySoftItemPolicy(AStages.addRestrictionForItem(id, stage, item))
    } catch (e) {
      console.warn('[AoA AStages gap closure] Skipped ' + item + ': ' + e)
    }
  }

  function softRecipeModLock(stage, modId) {
    if (!AStages.addRestrictionForModRecipe) {
      console.warn('[AoA AStages gap closure] Recipe mod lock API missing for ' + modId)
      return
    }
    var id = 'aoa/recipe_mod/' + modId.replace(/[^a-zA-Z0-9_]/g, '_') + '/' + stage
    try {
      AStages.addRestrictionForModRecipe(id, stage, modId)
    } catch (e) {
      console.warn('[AoA AStages gap closure] Skipped recipe mod lock ' + modId + ': ' + e)
    }
  }

  var itemLocks = [
    // the_afterdark is an Otherworldly veil surface. Its portal items were
    // previously structure-loot reachable with no AStages item or dimension lock.
    ["otherworldly", "the_afterdark:teleport_catalyst", "afterdark"],
    ["otherworldly", "the_afterdark:teleport_block", "afterdark"],

    // IFEU: apple_core is already IR in the main item file; deep generators,
    // dragon-star processing, upgrade add-ons, and pseudo-creative endpoints
    // are held until Atomic/Otherworldly/Ascension to prevent IF endgame skips.
    ["atomic", "ifeu:laser_lens_sculk", "ifeu"],
    ["atomic", "ifeu:netherite_gear", "ifeu"],
    ["atomic", "ifeu:sculk_gear", "ifeu"],
    ["atomic", "ifeu:thread_addon_1", "ifeu"],
    ["atomic", "ifeu:thread_addon_2", "ifeu"],
    ["atomic", "ifeu:thread_addon_3", "ifeu"],
    ["atomic", "ifeu:apple_addon_1", "ifeu"],
    ["atomic", "ifeu:apple_addon_2", "ifeu"],
    ["atomic", "ifeu:apple_addon_3", "ifeu"],
    ["atomic", "ifeu:heal_addon_1", "ifeu"],
    ["atomic", "ifeu:heal_addon_2", "ifeu"],
    ["atomic", "ifeu:heal_addon_3", "ifeu"],
    ["atomic", "ifeu:chance_addon_1", "ifeu"],
    ["atomic", "ifeu:chance_addon_2", "ifeu"],
    ["atomic", "ifeu:chance_addon_3", "ifeu"],
    ["atomic", "ifeu:energy_addon_1", "ifeu"],
    ["atomic", "ifeu:energy_addon_2", "ifeu"],
    ["atomic", "ifeu:energy_addon_3", "ifeu"],
    ["atomic", "ifeu:hydroponic_simulation_processor", "ifeu"],
    ["atomic", "ifeu:blueprint", "ifeu"],
    ["atomic", "ifeu:silk_addon", "ifeu"],
    ["atomic", "ifeu:infuser", "ifeu"],
    ["atomic", "ifeu:ultimate_machine_frame", "ifeu"],
    ["atomic", "ifeu:fluid_crafting_table", "ifeu"],
    ["atomic", "ifeu:fluid_transfer", "ifeu"],
    ["atomic", "ifeu:big_dissolution_chamber", "ifeu"],
    ["atomic", "ifeu:liquid_sculk_matter", "ifeu"],
    ["atomic", "ifeu:liquid_sculk_matter_bucket", "ifeu"],
    ["atomic", "ifeu:liquid_malic_acid", "ifeu"],
    ["atomic", "ifeu:liquid_malic_acid_bucket", "ifeu"],
    ["atomic", "ifeu:simulated_hydroponic_bed", "ifeu"],
    ["atomic", "ifeu:platform_builder", "ifeu"],
    ["atomic", "ifeu:precision_crafting_table", "ifeu"],
    ["otherworldly", "ifeu:liquid_dragon_breath", "ifeu"],
    ["otherworldly", "ifeu:liquid_dragon_breath_bucket", "ifeu"],
    ["otherworldly", "ifeu:dragon_star", "ifeu"],
    ["otherworldly", "ifeu:dragon_star_block", "ifeu"],
    ["otherworldly", "ifeu:dragon_star_essence", "ifeu"],
    ["otherworldly", "ifeu:dragon_star_essence_bucket", "ifeu"],
    ["otherworldly", "ifeu:rough_dragon_star", "ifeu"],
    ["otherworldly", "ifeu:empty_nether_star", "ifeu"],
    ["otherworldly", "ifeu:laser_lens_dragon", "ifeu"],
    ["otherworldly", "ifeu:dragon_star_sword", "ifeu"],
    ["otherworldly", "ifeu:dragon_star_pickaxe", "ifeu"],
    ["otherworldly", "ifeu:dragon_star_axe", "ifeu"],
    ["otherworldly", "ifeu:dragon_star_shovel", "ifeu"],
    ["otherworldly", "ifeu:dragon_star_hoe", "ifeu"],
    ["otherworldly", "ifeu:dragon_star_helmet", "ifeu"],
    ["otherworldly", "ifeu:dragon_star_chestplate", "ifeu"],
    ["otherworldly", "ifeu:dragon_star_leggings", "ifeu"],
    ["otherworldly", "ifeu:dragon_star_boots", "ifeu"],
    ["otherworldly", "ifeu:thread_addon_4", "ifeu"],
    ["otherworldly", "ifeu:thread_addon_5", "ifeu"],
    ["otherworldly", "ifeu:thread_addon_6", "ifeu"],
    ["otherworldly", "ifeu:apple_addon_4", "ifeu"],
    ["otherworldly", "ifeu:apple_addon_5", "ifeu"],
    ["otherworldly", "ifeu:apple_addon_6", "ifeu"],
    ["otherworldly", "ifeu:heal_addon_4", "ifeu"],
    ["otherworldly", "ifeu:heal_addon_5", "ifeu"],
    ["otherworldly", "ifeu:heal_addon_6", "ifeu"],
    ["otherworldly", "ifeu:chance_addon_4", "ifeu"],
    ["otherworldly", "ifeu:chance_addon_5", "ifeu"],
    ["otherworldly", "ifeu:chance_addon_6", "ifeu"],
    ["otherworldly", "ifeu:energy_addon_4", "ifeu"],
    ["otherworldly", "ifeu:energy_addon_5", "ifeu"],
    ["otherworldly", "ifeu:energy_addon_6", "ifeu"],
    ["otherworldly", "ifeu:dragon_star_generator", "ifeu"],
    ["otherworldly", "ifeu:arcane_dragon_egg_forging", "ifeu"],
    ["otherworldly", "ifeu:dead_dragon_egg", "ifeu"],
    ["otherworldly", "ifeu:dragon_generator", "ifeu"],
    ["ascension", "ifeu:creative_chance_addon", "ifeu"],
    ["ascension", "ifeu:creative_addon", "ifeu"],
    ["ascension", "ifeu:creative_capacitor", "ifeu"],

    // Gaze: sparse but high-power veil/void curios and weapons. Current gear
    // audit places it as Otherworldly flavor, so lock the namespace there.
    ["otherworldly", "gaze:encyclopedia_unveiled", "gaze"],
    ["otherworldly", "gaze:adaptive_wheel", "gaze"],
    ["otherworldly", "gaze:enchantment_workbench", "gaze"],
    ["otherworldly", "gaze:spirit_channel_pouch", "gaze"],
    ["otherworldly", "gaze:spirit_saber", "gaze"],
    ["otherworldly", "gaze:swift_spiral", "gaze"],
    ["otherworldly", "gaze:sluggish_brooch", "gaze"],
    ["otherworldly", "gaze:meditation_ring", "gaze"],
    ["otherworldly", "gaze:compromise_ring", "gaze"],
    ["otherworldly", "gaze:charge_necklace", "gaze"],
    ["otherworldly", "gaze:rune_of_eir", "gaze"],
    ["otherworldly", "gaze:rune_of_fafnir", "gaze"],
    ["otherworldly", "gaze:rune_of_ymir", "gaze"],
    ["otherworldly", "gaze:rune_of_gymir", "gaze"],
    ["otherworldly", "gaze:rune_of_beyond_the_veil", "gaze"],
    ["otherworldly", "gaze:rune_of_out_of_phase", "gaze"],
    ["otherworldly", "gaze:rune_of_blighted_presence", "gaze"],
    ["otherworldly", "gaze:rune_of_touch_of_void", "gaze"],
    ["otherworldly", "gaze:geas", "gaze"],
    ["otherworldly", "gaze:soul_rapier", "gaze"],
    ["otherworldly", "gaze:splintered_world", "gaze"],
    ["otherworldly", "gaze:astral_splintered_world", "gaze"],
    ["otherworldly", "gaze:seidhr", "gaze"],
    ["otherworldly", "gaze:veil_dagger", "gaze"],
    ["otherworldly", "gaze:soul_of_the_veil_dagger", "gaze"],

    // Defensive direct locks for high-tier gear whose craft chains are mostly
    // gated but whose final items can still leak through loot, rewards, or trades.
    ["the_renaissance", "mahoutsukai:staff_emrys", "high_tier_gear"],
    ["atomic", "cataclysm:laser_gatling", "high_tier_gear"],
    // MI quantum gear is Otherworldly by recipe: quantum_upgrade -> quantum_circuit -> qubit
    // requires superconductor_wire + tritium (superconductor tier is OW, 01h:171-176). Staged OW, not atomic.
    ["otherworldly", "modern_industrialization:quantum_helmet", "high_tier_gear"],
    ["otherworldly", "modern_industrialization:quantum_chestplate", "high_tier_gear"],
    ["otherworldly", "modern_industrialization:quantum_leggings", "high_tier_gear"],
    ["otherworldly", "modern_industrialization:quantum_boots", "high_tier_gear"],
    ["otherworldly", "modern_industrialization:quantum_sword", "high_tier_gear"],
    ["otherworldly", "oritech:exo_helmet", "high_tier_gear"],
    ["otherworldly", "oritech:exo_chestplate", "high_tier_gear"],
    ["otherworldly", "oritech:exo_leggings", "high_tier_gear"],
    ["otherworldly", "oritech:exo_boots", "high_tier_gear"],
    ["industrial_revolution", "oritech:jetpack", "high_tier_gear"],
    ["otherworldly", "oritech:exo_jetpack", "high_tier_gear"],
    ["otherworldly", "oritech:jetpack_elytra", "high_tier_gear"],
    ["ascension", "oritech:jetpack_exo_elytra", "high_tier_gear"],
    ["ascension", "industrialization_overdrive:vajra", "high_tier_gear"],
    ["ascension", "avaritia:infinity_sword", "high_tier_gear"],
    ["ascension", "avaritia:infinity_pickaxe", "high_tier_gear"],
    ["ascension", "avaritia:infinity_axe", "high_tier_gear"],
    ["ascension", "avaritia:infinity_shovel", "high_tier_gear"],
    ["ascension", "avaritia:infinity_hoe", "high_tier_gear"],
    ["ascension", "avaritia:infinity_bow", "high_tier_gear"],
    ["ascension", "avaritia:infinity_helmet", "high_tier_gear"],
    ["ascension", "avaritia:infinity_chestplate", "high_tier_gear"],
    ["ascension", "avaritia:infinity_leggings", "high_tier_gear"],
    ["ascension", "avaritia:infinity_boots", "high_tier_gear"],
    ["ascension", "avaritia:skullfire_sword", "high_tier_gear"],

    // Sidecar staging-contract sweep: direct locks for high-impact items that
    // can leak through loot, reward tables, trades, or structure generation
    // even when their normal craft chains are correctly gated.
    ["otherworldly", "advanced_ae:quantum_helmet", "advanced_ae_quantum"],
    ["otherworldly", "advanced_ae:quantum_chestplate", "advanced_ae_quantum"],
    ["otherworldly", "advanced_ae:quantum_leggings", "advanced_ae_quantum"],
    ["otherworldly", "advanced_ae:quantum_boots", "advanced_ae_quantum"],
    ["otherworldly", "advanced_ae:quantum_processor", "advanced_ae_quantum"],
    ["otherworldly", "advanced_ae:printed_quantum_processor", "advanced_ae_quantum"],
    ["otherworldly", "advanced_ae:quantum_alloy", "advanced_ae_quantum"],
    ["otherworldly", "advanced_ae:quantum_alloy_plate", "advanced_ae_quantum"],
    ["otherworldly", "advanced_ae:quantum_storage_component", "advanced_ae_quantum"],
    ["otherworldly", "advanced_ae:quantum_upgrade_base", "advanced_ae_quantum"],
    ["otherworldly", "advanced_ae:shattered_singularity", "advanced_ae_quantum"],
    ["otherworldly", "advanced_ae:quantum_processor_press", "advanced_ae_quantum"],
    ["otherworldly", "advanced_ae:quantum_infused_dust", "advanced_ae_quantum"],
    ["otherworldly", "advanced_ae:quantum_infusion_bucket", "advanced_ae_quantum"],
    ["otherworldly", "advanced_ae:quantum_alloy_block", "advanced_ae_quantum"],
    ["otherworldly", "advanced_ae:quantum_alloy_slab", "advanced_ae_quantum"],
    ["otherworldly", "advanced_ae:quantum_alloy_stairs", "advanced_ae_quantum"],
    ["otherworldly", "advanced_ae:quantum_alloy_wall", "advanced_ae_quantum"],
    ["otherworldly", "draconicevolution:dislocator", "draconic_mobility"],
    ["otherworldly", "draconicevolution:p2p_dislocator", "draconic_mobility"],
    ["otherworldly", "draconicevolution:p2p_dislocator_unbound", "draconic_mobility"],
    ["otherworldly", "draconicevolution:player_dislocator", "draconic_mobility"],
    ["otherworldly", "draconicevolution:player_dislocator_unbound", "draconic_mobility"],
    ["otherworldly", "draconicevolution:dislocator_pedestal", "draconic_mobility"],
    ["otherworldly", "draconicevolution:dislocator_receptacle", "draconic_mobility"],
    ["otherworldly", "draconicevolution:wyvern_chestpiece", "draconic_mobility"],
    ["otherworldly", "cataclysm:tidal_claws", "boss_proof"],
    ["industrial_revolution", "bosses_of_mass_destruction:earthdive_spear", "bomd_utility"],
    ["industrial_revolution", "bosses_of_mass_destruction:levitation_block", "bomd_utility"],
    ["industrial_revolution", "bosses_of_mass_destruction:mob_ward", "bomd_utility"],
    ["gilded_age", "astral_dimension:amethyst_key", "astral_controls"],
    ["gilded_age", "astral_dimension:astral_transmitter", "astral_controls"],
    ["gilded_age", "astral_dimension:final_crystal", "astral_controls"],
    ["gilded_age", "astral_dimension:final_crystal_cooldown_1", "astral_controls"],
    ["gilded_age", "astral_dimension:final_crystal_cooldown_2", "astral_controls"],
    ["gilded_age", "astral_dimension:final_crystal_cooldown_3", "astral_controls"],
    ["gilded_age", "astral_dimension:final_crystal_summoning", "astral_controls"],
    // Source blocks whose block loot emits staged Astral gear/proof items.
    // Astral dimensions are Gilded, so the source blocks should be Gilded too.
    ["gilded_age", "astral_dimension:astral_altar_full", "source_block_loot"],
    ["gilded_age", "astral_dimension:astral_altar_ready", "source_block_loot"],
    ["gilded_age", "astral_dimension:burning_orb", "source_block_loot"],
    ["gilded_age", "astral_dimension:megvin_egg", "source_block_loot"],
    ["gilded_age", "astral_dimension:supreme_altar_full", "source_block_loot"],
    ["gilded_age", "astral_dimension:supreme_altar_ready", "source_block_loot"],
    ["gilded_age", "astral_dimension:anomal_present", "source_block_loot"],
    ["gilded_age", "astral_dimension:void_titan_present", "source_block_loot"],
    ["gilded_age", "astral_dimension:tower_of_malice_present", "source_block_loot"],
    ["gilded_age", "nautec:bio_reactor_part", "source_block_loot"],
    ["industrial_revolution", "oritech:tainted_refinery_block", "source_block_loot"],
    ["ascension", "draconicevolution:advanced_dislocator", "draconic_apex"],
    ["ascension", "draconicevolution:draconic_chestpiece", "draconic_apex"],
    ["ascension", "draconicevolution:chaotic_chestpiece", "draconic_apex"],
    ["atomic", "fdbosses:justice_core", "boss_proof"],

    // Storage/network completed-cell leak closure. Housings and crafting
    // blocks are covered elsewhere; final cells/components still need direct
    // locks so loot/reward/trade paths cannot skip the network ladder.
    ["atomic", "appmek:chemical_storage_cell_1k", "applied_mekanistics_cells"],
    ["atomic", "appmek:chemical_storage_cell_4k", "applied_mekanistics_cells"],
    ["atomic", "appmek:chemical_storage_cell_16k", "applied_mekanistics_cells"],
    ["atomic", "appmek:chemical_storage_cell_64k", "applied_mekanistics_cells"],
    ["atomic", "appmek:chemical_storage_cell_256k", "applied_mekanistics_cells"],
    ["gilded_age", "megacells:bulk_cell_component", "mega_cells"],
    ["gilded_age", "megacells:cell_component_1m", "mega_cells"],
    ["gilded_age", "megacells:cell_component_4m", "mega_cells"],
    ["gilded_age", "megacells:cell_component_16m", "mega_cells"],
    ["gilded_age", "megacells:cell_component_64m", "mega_cells"],
    ["atomic", "megacells:cell_component_256m", "mega_cells"],
    ["atomic", "megacells:radioactive_cell_component", "mega_cells"],
    ["gilded_age", "megacells:item_storage_cell_1m", "mega_cells"],
    ["gilded_age", "megacells:item_storage_cell_4m", "mega_cells"],
    ["gilded_age", "megacells:item_storage_cell_16m", "mega_cells"],
    ["gilded_age", "megacells:item_storage_cell_64m", "mega_cells"],
    ["atomic", "megacells:item_storage_cell_256m", "mega_cells"],
    ["gilded_age", "megacells:fluid_storage_cell_1m", "mega_cells"],
    ["gilded_age", "megacells:fluid_storage_cell_4m", "mega_cells"],
    ["gilded_age", "megacells:fluid_storage_cell_16m", "mega_cells"],
    ["gilded_age", "megacells:fluid_storage_cell_64m", "mega_cells"],
    ["atomic", "megacells:fluid_storage_cell_256m", "mega_cells"],
    ["gilded_age", "megacells:chemical_storage_cell_1m", "mega_cells"],
    ["gilded_age", "megacells:chemical_storage_cell_4m", "mega_cells"],
    ["gilded_age", "megacells:chemical_storage_cell_16m", "mega_cells"],
    ["gilded_age", "megacells:chemical_storage_cell_64m", "mega_cells"],
    ["atomic", "megacells:chemical_storage_cell_256m", "mega_cells"],
    ["gilded_age", "megacells:experience_storage_cell_1m", "mega_cells"],
    ["gilded_age", "megacells:experience_storage_cell_4m", "mega_cells"],
    ["gilded_age", "megacells:experience_storage_cell_16m", "mega_cells"],
    ["gilded_age", "megacells:experience_storage_cell_64m", "mega_cells"],
    ["atomic", "megacells:experience_storage_cell_256m", "mega_cells"],
    ["gilded_age", "megacells:mana_storage_cell_1m", "mega_cells"],
    ["gilded_age", "megacells:mana_storage_cell_4m", "mega_cells"],
    ["gilded_age", "megacells:mana_storage_cell_16m", "mega_cells"],
    ["gilded_age", "megacells:mana_storage_cell_64m", "mega_cells"],
    ["atomic", "megacells:mana_storage_cell_256m", "mega_cells"],
    ["gilded_age", "megacells:source_storage_cell_1m", "mega_cells"],
    ["gilded_age", "megacells:source_storage_cell_4m", "mega_cells"],
    ["gilded_age", "megacells:source_storage_cell_16m", "mega_cells"],
    ["gilded_age", "megacells:source_storage_cell_64m", "mega_cells"],
    ["atomic", "megacells:source_storage_cell_256m", "mega_cells"],
    ["gilded_age", "megacells:soul_storage_cell_1m", "mega_cells"],
    ["gilded_age", "megacells:soul_storage_cell_4m", "mega_cells"],
    ["gilded_age", "megacells:soul_storage_cell_16m", "mega_cells"],
    ["gilded_age", "megacells:soul_storage_cell_64m", "mega_cells"],
    ["atomic", "megacells:soul_storage_cell_256m", "mega_cells"],
    ["atomic", "megacells:portable_cell_workbench", "mega_cells_portable"],
    ["atomic", "megacells:portable_item_cell_1m", "mega_cells_portable"],
    ["atomic", "megacells:portable_item_cell_4m", "mega_cells_portable"],
    ["atomic", "megacells:portable_item_cell_16m", "mega_cells_portable"],
    ["atomic", "megacells:portable_item_cell_64m", "mega_cells_portable"],
    ["atomic", "megacells:portable_item_cell_256m", "mega_cells_portable"],
    ["atomic", "megacells:portable_fluid_cell_1m", "mega_cells_portable"],
    ["atomic", "megacells:portable_fluid_cell_4m", "mega_cells_portable"],
    ["atomic", "megacells:portable_fluid_cell_16m", "mega_cells_portable"],
    ["atomic", "megacells:portable_fluid_cell_64m", "mega_cells_portable"],
    ["atomic", "megacells:portable_fluid_cell_256m", "mega_cells_portable"],
    ["atomic", "megacells:portable_chemical_cell_1m", "mega_cells_portable"],
    ["atomic", "megacells:portable_chemical_cell_4m", "mega_cells_portable"],
    ["atomic", "megacells:portable_chemical_cell_16m", "mega_cells_portable"],
    ["atomic", "megacells:portable_chemical_cell_64m", "mega_cells_portable"],
    ["atomic", "megacells:portable_chemical_cell_256m", "mega_cells_portable"],
    ["atomic", "megacells:portable_experience_cell_1m", "mega_cells_portable"],
    ["atomic", "megacells:portable_experience_cell_4m", "mega_cells_portable"],
    ["atomic", "megacells:portable_experience_cell_16m", "mega_cells_portable"],
    ["atomic", "megacells:portable_experience_cell_64m", "mega_cells_portable"],
    ["atomic", "megacells:portable_experience_cell_256m", "mega_cells_portable"],
    ["atomic", "megacells:portable_mana_cell_1m", "mega_cells_portable"],
    ["atomic", "megacells:portable_mana_cell_4m", "mega_cells_portable"],
    ["atomic", "megacells:portable_mana_cell_16m", "mega_cells_portable"],
    ["atomic", "megacells:portable_mana_cell_64m", "mega_cells_portable"],
    ["atomic", "megacells:portable_mana_cell_256m", "mega_cells_portable"],
    ["atomic", "megacells:portable_source_cell_1m", "mega_cells_portable"],
    ["atomic", "megacells:portable_source_cell_4m", "mega_cells_portable"],
    ["atomic", "megacells:portable_source_cell_16m", "mega_cells_portable"],
    ["atomic", "megacells:portable_source_cell_64m", "mega_cells_portable"],
    ["atomic", "megacells:portable_source_cell_256m", "mega_cells_portable"],

    // F3/F4 alloy/circuit tag parity scan (2026-06-01): keep broad tier tags
    // open per policy, but directly lock outputs that consume advanced/elite/
    // ultimate alloy or advanced-circuit tags and were not independently held.
    ["atomic", "mekanism:advanced_tier_installer", "tag_parity"],
    ["atomic", "mekanism:elite_control_circuit", "tag_parity"],
    ["atomic", "mekanism:flamethrower", "tag_parity"],
    ["gilded_age", "mekanism:painting_machine", "tag_parity"],
    ["atomic", "mekanism:module_attack_amplification_unit", "tag_parity"],
    ["atomic", "mekanism:module_dosimeter_unit", "tag_parity"],
    ["atomic", "mekanism:module_electrolytic_breathing_unit", "tag_parity"],
    ["atomic", "mekanism:module_energy_unit", "tag_parity"],
    ["atomic", "mekanism:module_excavation_escalation_unit", "tag_parity"],
    ["atomic", "mekanism:module_farming_unit", "tag_parity"],
    ["atomic", "mekanism:module_geiger_unit", "tag_parity"],
    ["atomic", "mekanism:module_laser_dissipation_unit", "tag_parity"],
    ["atomic", "mekanism:module_radiation_shielding_unit", "tag_parity"],
    ["atomic", "mekanism:module_shearing_unit", "tag_parity"],
    ["atomic", "mekanism:module_charge_distribution_unit", "tag_parity"],
    ["atomic", "mekanism:module_elytra_unit", "tag_parity"],
    ["atomic", "mekanism:module_fortune_unit", "tag_parity"],
    ["atomic", "mekanism:module_frost_walker_unit", "tag_parity"],
    ["atomic", "mekanism:module_gyroscopic_stabilization_unit", "tag_parity"],
    ["atomic", "mekanism:module_hydraulic_propulsion_unit", "tag_parity"],
    ["atomic", "mekanism:module_hydrostatic_repulsor_unit", "tag_parity"],
    ["atomic", "mekanism:module_inhalation_purification_unit", "tag_parity"],
    ["atomic", "mekanism:module_jetpack_unit", "tag_parity"],
    ["atomic", "mekanism:module_locomotive_boosting_unit", "tag_parity"],
    ["atomic", "mekanism:module_magnetic_attraction_unit", "tag_parity"],
    ["atomic", "mekanism:module_motorized_servo_unit", "tag_parity"],
    ["atomic", "mekanism:module_nutritional_injection_unit", "tag_parity"],
    ["atomic", "mekanism:module_silk_touch_unit", "tag_parity"],
    ["atomic", "mekanism:module_soul_surfer_unit", "tag_parity"],
    ["atomic", "mekanism:module_vein_mining_unit", "tag_parity"],
    ["atomic", "mekanism:module_vision_enhancement_unit", "tag_parity"],
    ["atomic", "mekanism:module_blasting_unit", "tag_parity"],
    ["otherworldly", "mekanism:module_gravitational_modulating_unit", "tag_parity"],
    ["otherworldly", "mekanism:module_teleportation_unit", "tag_parity"],
    ["atomic", "mekanismgenerators:module_geothermal_generator_unit", "tag_parity"],
    ["atomic", "mekanismgenerators:module_solar_recharging_unit", "tag_parity"],
    ["atomic", "evolvedmekanism:alloyer", "tag_parity"],
    ["atomic", "evolvedmekanism:module_air_affinity_unit", "tag_parity"],
    ["atomic", "evolvedmekanism:module_aqua_affinity_unit", "tag_parity"],
    ["atomic", "evolvedmekanism:module_capturing_unit", "tag_parity"],
    ["atomic", "evolvedmekanism:module_luck_unit", "tag_parity"],
    ["atomic", "mekmm:advanced_electrolysis_core", "tag_parity"],
    ["atomic", "mekmm:recycler", "tag_parity"],
    ["atomic", "ballistix:rocketlauncher", "tag_parity"],
    ["atomic", "ballistix:tracker", "tag_parity"],
    ["gilded_age", "chemicalscience:chromotographycardcarbonmonoxide", "tag_parity"],
    ["gilded_age", "chemicalscience:chromotographycardhelium", "tag_parity"],
    ["gilded_age", "chemicalscience:chromotographycardkrypton", "tag_parity"],
    ["gilded_age", "chemicalscience:chromotographycardneon", "tag_parity"],
    ["gilded_age", "chemicalscience:chromotographycardradon", "tag_parity"],
    ["gilded_age", "chemicalscience:chromotographycardxenon", "tag_parity"],
    ["atomic", "chemicalscience:flamethrower", "tag_parity"],
    ["gilded_age", "electrodynamics:chromotographycardcarbondioxide", "tag_parity"],
    ["gilded_age", "electrodynamics:electricbaton", "tag_parity"],
    ["gilded_age", "electrodynamics:jetpack", "tag_parity"],
    ["gilded_age", "electrodynamics:nightvisiongoggles", "tag_parity"],
    ["gilded_age", "voltaic:upgradeadvancedcapacity", "tag_parity"],
    ["gilded_age", "voltaic:upgradeadvancedspeed", "tag_parity"],
    ["gilded_age", "voltaic:upgradeunbreaking", "tag_parity"],

    // ProjectE is absent, but ExtendedAE/MEGA transmutation bridge items exist.
    // Hold them with the existing Atomic `extendedae:ex_emc_interface` lock.
    ["atomic", "extendedae:emc_interface_upgrade", "emc_bridge"],
    ["atomic", "extendedae:emc_io_bus_upgrade", "emc_bridge"],
    ["atomic", "extendedae:ex_emc_export_bus_part", "emc_bridge"],
    ["atomic", "extendedae:ex_emc_import_bus_part", "emc_bridge"],
    ["atomic", "extendedae:ex_emc_interface", "emc_bridge"],
    ["atomic", "extendedae:ex_emc_interface_part", "emc_bridge"],
    ["atomic", "megacells:cable_mega_emc_interface", "emc_bridge"],
    ["atomic", "megacells:mega_emc_interface", "emc_bridge"],

    // Arsenal unique gear by tier suffix: _1 = IR, _2 = Gilded, _sw = OW.
    ["industrial_revolution", "arsenal:unique_claymore_1", "arsenal"],
    ["industrial_revolution", "arsenal:unique_dagger_1", "arsenal"],
    ["industrial_revolution", "arsenal:unique_double_axe_1", "arsenal"],
    ["industrial_revolution", "arsenal:unique_glaive_1", "arsenal"],
    ["industrial_revolution", "arsenal:unique_hammer_1", "arsenal"],
    ["industrial_revolution", "arsenal:unique_heavy_crossbow_1", "arsenal"],
    ["industrial_revolution", "arsenal:unique_longbow_1", "arsenal"],
    ["industrial_revolution", "arsenal:unique_mace_1", "arsenal"],
    ["industrial_revolution", "arsenal:unique_shield_1", "arsenal"],
    ["industrial_revolution", "arsenal:unique_sickle_1", "arsenal"],
    ["industrial_revolution", "arsenal:unique_spear_1", "arsenal"],
    ["industrial_revolution", "arsenal:unique_staff_damage_1", "arsenal"],
    ["industrial_revolution", "arsenal:unique_staff_damage_2", "arsenal"],
    ["industrial_revolution", "arsenal:unique_staff_heal_1", "arsenal"],
    ["gilded_age", "arsenal:unique_claymore_2", "arsenal"],
    ["gilded_age", "arsenal:unique_dagger_2", "arsenal"],
    ["gilded_age", "arsenal:unique_double_axe_2", "arsenal"],
    ["gilded_age", "arsenal:unique_glaive_2", "arsenal"],
    ["gilded_age", "arsenal:unique_hammer_2", "arsenal"],
    ["gilded_age", "arsenal:unique_heavy_crossbow_2", "arsenal"],
    ["gilded_age", "arsenal:unique_longbow_2", "arsenal"],
    ["gilded_age", "arsenal:unique_mace_2", "arsenal"],
    ["gilded_age", "arsenal:unique_shield_2", "arsenal"],
    ["gilded_age", "arsenal:unique_sickle_2", "arsenal"],
    ["gilded_age", "arsenal:unique_spear_2", "arsenal"],
    ["gilded_age", "arsenal:unique_staff_damage_3", "arsenal"],
    ["gilded_age", "arsenal:unique_staff_damage_4", "arsenal"],
    ["gilded_age", "arsenal:unique_staff_damage_5", "arsenal"],
    ["gilded_age", "arsenal:unique_staff_damage_6", "arsenal"],
    ["gilded_age", "arsenal:unique_staff_heal_2", "arsenal"],
    ["otherworldly", "arsenal:unique_claymore_sw", "arsenal"],
    ["otherworldly", "arsenal:unique_dagger_sw", "arsenal"],
    ["otherworldly", "arsenal:unique_double_axe_sw", "arsenal"],
    ["otherworldly", "arsenal:unique_glaive_sw", "arsenal"],
    ["otherworldly", "arsenal:unique_hammer_sw", "arsenal"],
    ["otherworldly", "arsenal:unique_heavy_crossbow_sw", "arsenal"],
    ["otherworldly", "arsenal:unique_longbow_sw", "arsenal"],
    ["otherworldly", "arsenal:unique_longsword_sw", "arsenal"],
    ["otherworldly", "arsenal:unique_mace_sw", "arsenal"],
    ["otherworldly", "arsenal:unique_shield_sw", "arsenal"],
    ["otherworldly", "arsenal:unique_sickle_sw", "arsenal"],
    ["otherworldly", "arsenal:unique_spear_sw", "arsenal"],
    ["otherworldly", "arsenal:unique_staff_damage_sw", "arsenal"],
    ["otherworldly", "arsenal:unique_staff_heal_sw", "arsenal"],

    // Relics are ambient curio loot; keep them optional, but prevent early
    // Dark/Medieval power spikes from random loot before Renaissance systems open.
    ["the_renaissance", "relics:reflective_necklace", "relics"],
    ["the_renaissance", "relics:jellyfish_necklace", "relics"],
    ["the_renaissance", "relics:kinetic_belt", "relics"],
    ["the_renaissance", "relics:springy_boot", "relics"],
    ["the_renaissance", "relics:leafy_mantle", "relics"],
    ["the_renaissance", "relics:roller_skate", "relics"],
    ["the_renaissance", "relics:midnight_mantle", "relics"],
    ["the_renaissance", "relics:chorus_staff", "relics"],
    ["the_renaissance", "relics:piglin_mask", "relics"],
    ["the_renaissance", "relics:cut_glass_boot", "relics"],
    ["the_renaissance", "relics:ring_of_the_seven_deadly_sins", "relics"],
    ["the_renaissance", "relics:sphere_of_self_sacrifice", "relics"],
    ["the_renaissance", "relics:hunting_belt", "relics"],
    ["the_renaissance", "relics:rider_flute", "relics"],
    ["the_renaissance", "relics:clot_of_time", "relics"],
    ["the_renaissance", "relics:chef_hat", "relics"],
    ["the_renaissance", "relics:raw_meatball", "relics"],
    ["the_renaissance", "relics:cooked_meatball", "relics"],
    ["the_renaissance", "relics:experience_disperser", "relics"],
    ["the_renaissance", "relics:glitchy_mantle", "relics"],
    ["the_renaissance", "relics:ghostly_mantle", "relics"],
    ["the_renaissance", "relics:shield_of_retaliation", "relics"],
    ["the_renaissance", "relics:relic_experience_bottle", "relics"],
    ["the_renaissance", "relics:golden_tooth", "relics"],
    ["the_renaissance", "relics:pet_bone", "relics"],
    ["the_renaissance", "relics:phantom_block", "relics"],

    // ZoNiEx mobs are already spawn-locked to Renaissance; lock their drops and
    // gear to the same stage so mob rewards cannot leak through chests/trades.
    ["the_renaissance", "zoniex:deathly_heart", "zoniex"],
    ["the_renaissance", "zoniex:staff_of_the_undying", "zoniex"],
    ["the_renaissance", "zoniex:distorted_vertebrae", "zoniex"],
    ["the_renaissance", "zoniex:whiplasher", "zoniex"],
    ["the_renaissance", "zoniex:deathly_onyx", "zoniex"],

    // Alex's Caves remains mostly NOT_QUESTED, but high-impact cave loot can
    // bypass Atomic/Otherworldly material and weapon pacing if found early.
    ["atomic", "alexscaves:uranium_rod", "alexscaves"],
    ["atomic", "alexscaves:fissile_core", "alexscaves"],
    ["atomic", "alexscaves:azure_neodymium_ingot", "alexscaves"],
    ["atomic", "alexscaves:scarlet_neodymium_ingot", "alexscaves"],
    ["atomic", "alexscaves:raw_azure_neodymium", "alexscaves"],
    ["atomic", "alexscaves:raw_scarlet_neodymium", "alexscaves"],
    ["atomic", "alexscaves:telecore", "alexscaves"],
    ["atomic", "alexscaves:notor_gizmo", "alexscaves"],
    ["atomic", "alexscaves:magic_conch", "alexscaves"],
    ["atomic", "alexscaves:ortholance", "alexscaves"],
    ["atomic", "alexscaves:sea_staff", "alexscaves"],
    ["atomic", "alexscaves:gazing_pearl", "alexscaves"],
    ["atomic", "alexscaves:occult_gem", "alexscaves"],
    ["atomic", "alexscaves:desolate_dagger", "alexscaves"]
  ]

  itemLocks.forEach(function (e) { softItemLock(e[0], e[1], e[2]) })

  // Create Ultimate Factory exposes broad factory shortcuts. Hold recipes at
  // IR so the pack's Create-family contracts unlock before CUF compression.
  softRecipeModLock('industrial_revolution', 'create_ultimate_factory')
})()
