// AoA KubeJS: aoa_astages_01h_modern_industrialization.js
// Machine Staging Contract pass (2026-05-28) -- Modern Industrialization family
// (modern_industrialization, extended_industrialization, industrialization_overdrive, moderndynamics).
//
// Tier signal = MI hull/casing/circuit ladder (verified from recipe/assembler_generated):
//   bronze/steel casing + analog_circuit          -> IR (steam + first electric)
//   aluminum/invar/stainless casing + electronic/digital circuit -> Gilded (petrochem core, MI's home)
//   nuclear casing + processing_unit               -> Atomic (titanium casings gilded since 2026-08-02)
//   iridium/quantum/plasma casing + superconductor -> Otherworldly (fusion/quantum)
// Oil-doc aligned: MI petrochem chain (chemical_reactor / distillation_tower / steam-cracking /
// vacuum_freezer / polymer ladder) sits at Gilded; only the LV single-block onboarding stays IR.
// All ages >= recipe ceiling (each tier built from same-or-earlier casing) -> no softlock.
// MD superconductor_cable moved to OW in the main file (was mis-staged gilded).

;(function () {
  if (typeof AStages === 'undefined') return
  function applySoftItemPolicy(r) {
    // AStages 2.5 defaults keep locked entries hidden in EMI and conceal their names.
    return r.allowInventoryStorage().allowContainerStorage().allowPickup().disableBlockInteraction()
  }
  function softItemLock(stage, item, kind) {
    if (typeof Item !== 'undefined' && typeof Item.exists === 'function' && !Item.exists(item)) {
      console.warn('[AoA AStages MI] Skipped missing item ' + item + ' (stage=' + stage + ')'); return
    }
    var id = 'aoa/item/' + kind + '/' + stage + '/' + item.replace(/[^a-zA-Z0-9_]/g, '_')
    try { applySoftItemPolicy(AStages.addRestrictionForItem(id, stage, item)) }
    catch (e) { console.warn('[AoA AStages MI] Skipped ' + item + ': ' + e) }
  }
  var itemLocks = [
    // === modern_industrialization IR (steam + first electric tier) ===
    ["industrial_revolution", "modern_industrialization:coke_oven", "block_item"],
    ["industrial_revolution", "modern_industrialization:steam_blast_furnace", "block_item"],
    ["industrial_revolution", "modern_industrialization:forge_hammer", "block_item"],
    ["industrial_revolution", "modern_industrialization:fire_clay_bricks", "block_item"],
    ["industrial_revolution", "modern_industrialization:bronze_plated_bricks", "block_item"],
    ["industrial_revolution", "modern_industrialization:bronze_boiler", "block_item"],
    ["industrial_revolution", "modern_industrialization:bronze_compressor", "block_item"],
    ["industrial_revolution", "modern_industrialization:bronze_cutting_machine", "block_item"],
    ["industrial_revolution", "modern_industrialization:bronze_furnace", "block_item"],
    ["industrial_revolution", "modern_industrialization:bronze_macerator", "block_item"],
    ["industrial_revolution", "modern_industrialization:bronze_mixer", "block_item"],
    ["industrial_revolution", "modern_industrialization:bronze_water_pump", "block_item"],
    ["industrial_revolution", "modern_industrialization:bronze_machine_casing_pipe", "block_item"],
    ["industrial_revolution", "modern_industrialization:steel_machine_casing", "block_item"],
    ["industrial_revolution", "modern_industrialization:steel_machine_casing_pipe", "block_item"],
    ["industrial_revolution", "modern_industrialization:steel_boiler", "block_item"],
    ["industrial_revolution", "modern_industrialization:steel_compressor", "block_item"],
    ["industrial_revolution", "modern_industrialization:steel_cutting_machine", "block_item"],
    ["industrial_revolution", "modern_industrialization:steel_furnace", "block_item"],
    ["industrial_revolution", "modern_industrialization:steel_macerator", "block_item"],
    ["industrial_revolution", "modern_industrialization:steel_mixer", "block_item"],
    ["industrial_revolution", "modern_industrialization:steel_packer", "block_item"],
    ["industrial_revolution", "modern_industrialization:steel_unpacker", "block_item"],
    ["industrial_revolution", "modern_industrialization:steel_water_pump", "block_item"],
    ["industrial_revolution", "modern_industrialization:steel_wiremill", "block_item"],
    ["industrial_revolution", "modern_industrialization:steam_quarry", "block_item"],
    ["industrial_revolution", "modern_industrialization:large_steam_boiler", "block_item"],
    ["industrial_revolution", "modern_industrialization:assembler", "block_item"],
    ["industrial_revolution", "modern_industrialization:basic_machine_hull", "block_item"],
    ["industrial_revolution", "modern_industrialization:electric_furnace", "block_item"],
    ["industrial_revolution", "modern_industrialization:electric_macerator", "block_item"],
    ["industrial_revolution", "modern_industrialization:electric_compressor", "block_item"],
    ["industrial_revolution", "modern_industrialization:electric_cutting_machine", "block_item"],
    ["industrial_revolution", "modern_industrialization:electric_mixer", "block_item"],
    ["industrial_revolution", "modern_industrialization:electric_packer", "block_item"],
    ["industrial_revolution", "modern_industrialization:electric_unpacker", "block_item"],
    ["industrial_revolution", "modern_industrialization:electric_water_pump", "block_item"],
    ["industrial_revolution", "modern_industrialization:electric_blast_furnace", "block_item"],
    ["industrial_revolution", "modern_industrialization:polarizer", "block_item"],
    ["industrial_revolution", "modern_industrialization:lv_diesel_generator", "block_item"],
    ["industrial_revolution", "modern_industrialization:lv_steam_turbine", "block_item"],
    ["industrial_revolution", "modern_industrialization:lv_storage_unit", "block_item"],
    ["industrial_revolution", "modern_industrialization:lv_mv_transformer", "block_item"],
    ["industrial_revolution", "modern_industrialization:configurable_chest", "block_item"],
    ["industrial_revolution", "modern_industrialization:configurable_tank", "block_item"],
    ["industrial_revolution", "modern_industrialization:large_tank", "block_item"],
    ["industrial_revolution", "modern_industrialization:large_tank_hatch", "block_item"],
    ["industrial_revolution", "modern_industrialization:trash_can", "block_item"],
    ["industrial_revolution", "modern_industrialization:bronze_fluid_input_hatch", "block_item"],
    ["industrial_revolution", "modern_industrialization:bronze_fluid_output_hatch", "block_item"],
    ["industrial_revolution", "modern_industrialization:bronze_item_input_hatch", "block_item"],
    ["industrial_revolution", "modern_industrialization:bronze_item_output_hatch", "block_item"],
    ["industrial_revolution", "modern_industrialization:steel_fluid_input_hatch", "block_item"],
    ["industrial_revolution", "modern_industrialization:steel_fluid_output_hatch", "block_item"],
    ["industrial_revolution", "modern_industrialization:steel_item_input_hatch", "block_item"],
    ["industrial_revolution", "modern_industrialization:steel_item_output_hatch", "block_item"],
    ["industrial_revolution", "modern_industrialization:lv_energy_input_hatch", "block_item"],
    ["industrial_revolution", "modern_industrialization:lv_energy_output_hatch", "block_item"],
    // === modern_industrialization Gilded (petrochem core + MV/HV + aluminum/stainless) ===
    ["gilded_age", "modern_industrialization:oil_drilling_rig", "block_item"],
    ["gilded_age", "modern_industrialization:distillery", "block_item"],
    ["gilded_age", "modern_industrialization:distillation_tower", "block_item"],
    ["gilded_age", "modern_industrialization:chemical_reactor", "block_item"],
    ["gilded_age", "modern_industrialization:electrolyzer", "block_item"],
    ["gilded_age", "modern_industrialization:centrifuge", "block_item"],
    ["gilded_age", "modern_industrialization:vacuum_freezer", "block_item"],
    ["gilded_age", "modern_industrialization:electric_quarry", "block_item"],
    ["gilded_age", "modern_industrialization:heat_exchanger", "block_item"],
    ["gilded_age", "modern_industrialization:pressurizer", "block_item"],
    ["gilded_age", "modern_industrialization:advanced_machine_casing", "block_item"],
    ["gilded_age", "modern_industrialization:advanced_machine_hull", "block_item"],
    ["gilded_age", "modern_industrialization:turbo_machine_casing", "block_item"],
    ["gilded_age", "modern_industrialization:turbo_machine_hull", "block_item"],
    ["gilded_age", "modern_industrialization:clean_stainless_steel_machine_casing", "block_item"],
    ["gilded_age", "modern_industrialization:stainless_steel_machine_casing_pipe", "block_item"],
    // titanium casings down-tiered atomic -> gilded_age (owner ruling 2026-08-02):
    // the pressurizer (gilded, quested in g5) requires titanium_machine_casing_pipe x2
    // in its only recipe; titanium ore is IR and EBF+kanthal (gilded) smelts it.
    ["gilded_age", "modern_industrialization:solid_titanium_machine_casing", "block_item"],
    ["gilded_age", "modern_industrialization:titanium_machine_casing_pipe", "block_item"],
    ["gilded_age", "modern_industrialization:heatproof_machine_casing", "block_item"],
    ["gilded_age", "modern_industrialization:frostproof_machine_casing", "block_item"],
    ["gilded_age", "modern_industrialization:cupronickel_coil", "block_item"],
    ["gilded_age", "modern_industrialization:kanthal_coil", "block_item"],
    ["gilded_age", "modern_industrialization:advanced_large_steam_boiler", "block_item"],
    ["gilded_age", "modern_industrialization:high_pressure_large_steam_boiler", "block_item"],
    ["gilded_age", "modern_industrialization:high_pressure_advanced_large_steam_boiler", "block_item"],
    ["gilded_age", "modern_industrialization:mv_steam_turbine", "block_item"],
    ["gilded_age", "modern_industrialization:hv_steam_turbine", "block_item"],
    ["gilded_age", "modern_industrialization:large_steam_turbine", "block_item"],
    ["gilded_age", "modern_industrialization:mv_diesel_generator", "block_item"],
    ["gilded_age", "modern_industrialization:hv_diesel_generator", "block_item"],
    ["gilded_age", "modern_industrialization:mv_storage_unit", "block_item"],
    ["gilded_age", "modern_industrialization:hv_storage_unit", "block_item"],
    ["gilded_age", "modern_industrialization:mv_hv_transformer", "block_item"],
    ["gilded_age", "modern_industrialization:mv_lv_transformer", "block_item"],
    ["gilded_age", "modern_industrialization:hv_mv_transformer", "block_item"],
    ["gilded_age", "modern_industrialization:mv_energy_input_hatch", "block_item"],
    ["gilded_age", "modern_industrialization:mv_energy_output_hatch", "block_item"],
    ["gilded_age", "modern_industrialization:hv_energy_input_hatch", "block_item"],
    ["gilded_age", "modern_industrialization:hv_energy_output_hatch", "block_item"],
    ["gilded_age", "modern_industrialization:advanced_fluid_input_hatch", "block_item"],
    ["gilded_age", "modern_industrialization:advanced_fluid_output_hatch", "block_item"],
    ["gilded_age", "modern_industrialization:advanced_item_input_hatch", "block_item"],
    ["gilded_age", "modern_industrialization:advanced_item_output_hatch", "block_item"],
    ["gilded_age", "modern_industrialization:turbo_fluid_input_hatch", "block_item"],
    ["gilded_age", "modern_industrialization:turbo_fluid_output_hatch", "block_item"],
    ["gilded_age", "modern_industrialization:turbo_item_input_hatch", "block_item"],
    ["gilded_age", "modern_industrialization:turbo_item_output_hatch", "block_item"],
    // === modern_industrialization Atomic (titanium/nuclear/EV) ===
    ["atomic", "modern_industrialization:large_diesel_generator", "block_item"],
    ["atomic", "modern_industrialization:implosion_compressor", "block_item"],
    ["atomic", "modern_industrialization:nuclear_reactor", "block_item"],
    ["atomic", "modern_industrialization:nuclear_casing", "block_item"],
    ["atomic", "modern_industrialization:nuclear_alloy_machine_casing_pipe", "block_item"],
    ["atomic", "modern_industrialization:nuclear_fluid_hatch", "block_item"],
    ["atomic", "modern_industrialization:nuclear_item_hatch", "block_item"],
    ["atomic", "modern_industrialization:blastproof_casing", "block_item"],
    ["atomic", "modern_industrialization:highly_advanced_machine_casing", "block_item"],
    ["atomic", "modern_industrialization:highly_advanced_machine_hull", "block_item"],
    ["atomic", "modern_industrialization:industrial_tnt", "block_item"],
    ["atomic", "modern_industrialization:nuke", "block_item"],
    ["atomic", "modern_industrialization:ev_storage_unit", "block_item"],
    ["atomic", "modern_industrialization:ev_hv_transformer", "block_item"],
    ["atomic", "modern_industrialization:hv_ev_transformer", "block_item"],
    ["atomic", "modern_industrialization:ev_energy_input_hatch", "block_item"],
    ["atomic", "modern_industrialization:ev_energy_output_hatch", "block_item"],
    ["atomic", "modern_industrialization:highly_advanced_fluid_input_hatch", "block_item"],
    ["atomic", "modern_industrialization:highly_advanced_fluid_output_hatch", "block_item"],
    ["atomic", "modern_industrialization:highly_advanced_item_input_hatch", "block_item"],
    ["atomic", "modern_industrialization:highly_advanced_item_output_hatch", "block_item"],
    // === modern_industrialization Otherworldly (fusion/plasma/quantum/superconductor) ===
    ["otherworldly", "modern_industrialization:fusion_reactor", "block_item"],
    ["otherworldly", "modern_industrialization:fusion_chamber", "block_item"],
    ["otherworldly", "modern_industrialization:plasma_turbine", "block_item"],
    ["otherworldly", "modern_industrialization:plasma_handling_iridium_machine_casing", "block_item"],
    ["otherworldly", "modern_industrialization:quantum_machine_casing", "block_item"],
    ["otherworldly", "modern_industrialization:quantum_machine_hull", "block_item"],
    ["otherworldly", "modern_industrialization:quantum_barrel", "block_item"],
    ["otherworldly", "modern_industrialization:quantum_tank", "block_item"],
    ["otherworldly", "modern_industrialization:replicator", "block_item"],
    ["otherworldly", "modern_industrialization:superconductor_coil", "block_item"],
    ["otherworldly", "modern_industrialization:superconductor_storage_unit", "block_item"],
    ["otherworldly", "modern_industrialization:superconductor_ev_transformer", "block_item"],
    ["otherworldly", "modern_industrialization:ev_superconductor_transformer", "block_item"],
    ["otherworldly", "modern_industrialization:superconductor_energy_input_hatch", "block_item"],
    ["otherworldly", "modern_industrialization:superconductor_energy_output_hatch", "block_item"],
    // === extended_industrialization IR (bronze/steel) ===
    ["industrial_revolution", "extended_industrialization:bronze_solar_boiler", "block_item"],
    ["industrial_revolution", "extended_industrialization:bronze_composter", "block_item"],
    ["industrial_revolution", "extended_industrialization:bronze_waste_collector", "block_item"],
    ["industrial_revolution", "extended_industrialization:bronze_bending_machine", "block_item"],
    ["industrial_revolution", "extended_industrialization:steel_solar_boiler", "block_item"],
    ["industrial_revolution", "extended_industrialization:steel_composter", "block_item"],
    ["industrial_revolution", "extended_industrialization:steel_waste_collector", "block_item"],
    ["industrial_revolution", "extended_industrialization:steel_bending_machine", "block_item"],
    ["industrial_revolution", "extended_industrialization:steel_canning_machine", "block_item"],
    ["industrial_revolution", "extended_industrialization:steel_honey_extractor", "block_item"],
    ["industrial_revolution", "extended_industrialization:steel_alloy_smelter", "block_item"],
    ["industrial_revolution", "extended_industrialization:large_steam_furnace", "block_item"],
    ["industrial_revolution", "extended_industrialization:large_steam_macerator", "block_item"],
    ["industrial_revolution", "extended_industrialization:steam_farmer", "block_item"],
    ["industrial_revolution", "extended_industrialization:electric_alloy_smelter", "block_item"],
    ["industrial_revolution", "extended_industrialization:electric_brewery", "block_item"],
    ["industrial_revolution", "extended_industrialization:electric_canning_machine", "block_item"],
    ["industrial_revolution", "extended_industrialization:electric_composter", "block_item"],
    ["industrial_revolution", "extended_industrialization:electric_honey_extractor", "block_item"],
    ["industrial_revolution", "extended_industrialization:electric_waste_collector", "block_item"],
    ["industrial_revolution", "extended_industrialization:electric_bending_machine", "block_item"],
    ["industrial_revolution", "extended_industrialization:lv_solar_panel", "block_item"],
    ["industrial_revolution", "extended_industrialization:universal_transformer", "block_item"],
    ["industrial_revolution", "extended_industrialization:steel_plated_bricks", "block_item"],
    ["industrial_revolution", "extended_industrialization:polished_silver_machine_casing", "block_item"],
    // === extended_industrialization Gilded (aluminum/stainless + tesla + MV/HV solar) ===
    ["gilded_age", "extended_industrialization:electric_farmer", "block_item"],
    ["gilded_age", "extended_industrialization:large_electric_furnace", "block_item"],
    ["gilded_age", "extended_industrialization:large_electric_macerator", "block_item"],
    ["gilded_age", "extended_industrialization:processing_array", "block_item"],
    ["gilded_age", "extended_industrialization:machine_chainer", "block_item"],
    ["gilded_age", "extended_industrialization:machine_chainer_relay", "block_item"],
    ["gilded_age", "extended_industrialization:mv_solar_panel", "block_item"],
    ["gilded_age", "extended_industrialization:hv_solar_panel", "block_item"],
    ["gilded_age", "extended_industrialization:tesla_coil", "block_item"],
    ["gilded_age", "extended_industrialization:lethal_tesla_coil", "block_item"],
    ["gilded_age", "extended_industrialization:tesla_tower", "block_item"],
    ["gilded_age", "extended_industrialization:tesla_particle_generator", "block_item"],
    ["gilded_age", "extended_industrialization:tesla_receiver", "block_item"],
    // lv_tesla_receiver_hatch re-tiered IR -> gilded_age (owner ruling 2026-08-02):
    // its only recipes consume tesla_receiver, which is gilded; an IR lock was
    // unreachable-at-own-stage hygiene drift (unquested, no player impact).
    ["gilded_age", "extended_industrialization:lv_tesla_receiver_hatch", "block_item"],
    ["gilded_age", "extended_industrialization:mv_tesla_receiver_hatch", "block_item"],
    ["gilded_age", "extended_industrialization:hv_tesla_receiver_hatch", "block_item"],
    ["gilded_age", "extended_industrialization:copper_tesla_winding", "block_item"],
    ["gilded_age", "extended_industrialization:annealed_copper_tesla_winding", "block_item"],
    ["gilded_age", "extended_industrialization:aluminum_tesla_winding", "block_item"],
    ["gilded_age", "extended_industrialization:electrum_tesla_winding", "block_item"],
    // === extended_industrialization Atomic / Otherworldly ===
    ["atomic", "extended_industrialization:ev_tesla_receiver_hatch", "block_item"],
    ["otherworldly", "extended_industrialization:superconductor_tesla_receiver_hatch", "block_item"],
    ["otherworldly", "extended_industrialization:superconductor_tesla_winding", "block_item"],
    // === industrialization_overdrive (multi_processing_array already locked atomic) ===
    ["gilded_age", "industrialization_overdrive:pyrolyse_oven", "block_item"],
    // === moderndynamics cables (tier with MI energy; superconductor_cable already OW in main) ===
    ["industrial_revolution", "moderndynamics:lv_cable", "block_item"],
    ["industrial_revolution", "moderndynamics:item_pipe", "block_item"],
    ["industrial_revolution", "moderndynamics:fluid_pipe", "block_item"],
    ["industrial_revolution", "moderndynamics:machine_extender", "block_item"],
    ["gilded_age", "moderndynamics:mv_cable", "block_item"],
    ["gilded_age", "moderndynamics:hv_cable", "block_item"],
    ["atomic", "moderndynamics:ev_cable", "block_item"],
  ]
  itemLocks.forEach(function (e) { softItemLock(e[0], e[1], e[2]) })
})()
